### ISSUE TITLE
Running setup.py install for torch-ipex ... error

### ISSUE THREAD

**Issue by C24IO** [intel/intel-extension-for-pytorch#156]
[ 93%] Built target benchmark
    [ 93%] Built target dnnl_cpu_x64

    [ 93%] Built target dnnl_cpu
    make: *** [Makefile:130: all] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-ra14_dqo/setup.py", line 288, in <module>
        setup(
      File "/opt/conda/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/opt/conda/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/opt/conda/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/opt/conda/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/opt/conda/lib/python3.8/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/opt/conda/lib/python3.8/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/opt/conda/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/opt/conda/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/opt/conda/lib/python3.8/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/opt/conda/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/opt/conda/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-req-build-ra14_dqo/setup.py", line 204, in run
        self.build_extension(ext)
      File "/tmp/pip-req-build-ra14_dqo/setup.py", line 262, in build_extension
        check_call(['make'] + build_args, cwd=ext.build_dir, env=env)
      File "/opt/conda/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['make', '-j', '36']' returned non-zero exit status 2.
    Running setup.py install for torch-ipex ... error
ERROR: Command errored out with exit status 1: /opt/conda/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-ra14_dqo/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-ra14_dqo/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-og5hba8b/install-record.txt --single-version-externally-managed --compile --install-headers /opt/conda/include/python3.8/torch-ipex Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 838, in install
    success = install_legacy(
  File "/opt/conda/lib/python3.8/site-packages/pip/_internal/operations/install/legacy.py", line 86, in install
    raise LegacyInstallFailure
pip._internal.operations.install.legacy.LegacyInstallFailure

During handling of the above exception, another exception occurred:

**Comment by jingxu10** [comment]
Please share your compilation steps to help identify the problem.

**Comment by mingxiaoh** [comment]
PREPARE:
    wget https://repo.continuum.io/archive/Anaconda3-5.0.0-Linux-x86_64.sh -O anaconda3.sh
    chmod +x anaconda3.sh
    ./anaconda3.sh -b -p ~/anaconda3
    ./anaconda3/bin/conda create -yn pytorch
    export PATH=~/anaconda3/bin:$PATH
    source ./anaconda3/bin/activate pytorch
    pip install sklearn onnx
    conda config --add channels intel
    conda install ninja pyyaml setuptools cmake cffi typing intel-openmp          
    conda install mkl mkl-include numpy -c intel --no-update-deps
    source /opt/rh/devtoolset-7/enable

  #build pytorch and intel-pytorch-extension
    git clone https://github.com/pytorch/pytorch.git
    cd pytorch
    git checkout v1.5.0-rc3
    git submodule sync
    git submodule update --init --recursive
    pip install -r requirements.txt

    cd ..
    git clone https://github.com/intel/intel-extension-for-pytorch.git
    cd intel-extension-for-pytorch
    git submodule sync
    git submodule update --init --recursive
    pip install lark-parser hypothesis

    cp torch_patches/dpcpp-v1.5-rc3.patch ../pytorch/
    cd ../pytorch
    git apply dpcpp-v1.5-rc3.patch
    python setup.py install

    cd ../ipex-cpu-dev
    python setup.py install


this is the old bkc when I was in this team half a year ago, if not work, contact owner @EikanWang  please.

**Comment by C24IO** [comment]
https://github.com/intel/intel-extension-for-pytorch/blob/master/docker/Dockerfile is the docker build I was following.

**Comment by zzzbosss1997** [comment]
a terrible project

**Comment by zzzbosss1997** [comment]
no one answer

**Comment by jingxu10** [comment]
Please follow instructions here -> https://github.com/intel/intel-extension-for-pytorch/issues/156#issuecomment-814579022
