### ISSUE TITLE
torchipex build error  in Centos 7 with gcc version 7.3.1

### ISSUE THREAD

**Issue by tiashlee** [intel/intel-extension-for-pytorch#174]
On running python setup.py install , I get the following error.Can anyone please help me with the issue ?
/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/ld: /tmp/cc5dC3nP.ltrans2.ltrans.o: relocation R_X86_64_PC32 against undefined symbol `_ZNSt10shared_ptrIN3c108ListTypeEED1Ev' can not be used when making a shared object; recompile with -fPIC
/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/_torch_ipex.dir/build.make:765: lib.linux-x86_64-3.8/_torch_ipex.cpython-38-x86_64-linux-gnu.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:485: CMakeFiles/_torch_ipex.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
Traceback (most recent call last):
  File "setup.py", line 370, in <module>
    setup(
  File "/nfs/site/home/ashleeti/anaconda3/envs/work/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/nfs/site/home/ashleeti/anaconda3/envs/work/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/nfs/site/home/ashleeti/anaconda3/envs/work/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/nfs/site/home/ashleeti/anaconda3/envs/work/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/nfs/site/home/ashleeti/anaconda3/envs/work/lib/python3.8/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/nfs/site/home/ashleeti/anaconda3/envs/work/lib/python3.8/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/nfs/site/home/ashleeti/anaconda3/envs/work/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/nfs/site/home/ashleeti/anaconda3/envs/work/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/nfs/site/home/ashleeti/anaconda3/envs/work/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/nfs/site/home/ashleeti/anaconda3/envs/work/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/nfs/site/home/ashleeti/anaconda3/envs/work/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/nfs/site/home/ashleeti/anaconda3/envs/work/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/nfs/site/home/ashleeti/anaconda3/envs/work/lib/python3.8/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/nfs/site/home/ashleeti/anaconda3/envs/work/lib/python3.8/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/nfs/site/home/ashleeti/anaconda3/envs/work/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/nfs/site/home/ashleeti/anaconda3/envs/work/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 286, in run
    self.build_extension(ext)
  File "setup.py", line 345, in build_extension
    check_call(['make'] + build_args, cwd=ext.build_dir, env=env)
  File "/nfs/site/home/ashleeti/anaconda3/envs/work/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-j', '96']' returned non-zero exit status 2.

**Comment by EikanWang** [comment]
@tiashlee , we released the binaries. you can directly install IPEX via pip now. Could you help to check if you will still encounter any problems?

**Comment by EikanWang** [comment]
I suppose this issue has been fixed on the release/1.10 branch. Please feel free to reopen it if not.
