### ISSUE TITLE
RuntimeError: Expected one of cpu, cuda, xpu, mkldnn, opengl, opencl, ideep, hip, msnpu, xla, vulkan device type at start of device string: dpcpp

### ISSUE THREAD

**Issue by zhuguiqian** [intel/intel-extension-for-pytorch#191]
when run "sh quickstart/bf16_online_inference.sh" in docker
report infos with error

`root@180372488f65:/pytorch-resnet50-bfloat16-inference/pytorch-resnet50-bfloat16-inference# sh quickstart/bf16_online_inference.sh 
Running '8' instance
2021-10-28 07:03:34,111 - __main__ - WARNING - Unable to find the TCmalloc library file libtcmalloc.so in $CONDA_PREFIX/lib or  /.local/lib/ or /usr/local/lib/ or /usr/local/lib64/ or /usr/lib or /usr/lib64 or ~/.local/lib/ so the LD_PRELOAD environment variable will not be set.
2021-10-28 07:03:34,112 - __main__ - INFO - OMP_NUM_THREADS=1 
2021-10-28 07:03:34,112 - __main__ - INFO - KMP_AFFINITY=granularity=fine,compact,1,0
2021-10-28 07:03:34,112 - __main__ - INFO - KMP_BLOCKTIME=1
2021-10-28 07:03:34,112 - __main__ - INFO - DNNL_PRIMITIVE_CACHE_CAPACITY=1024
Namespace(arch='resnet50', batch_size=1, cuda=False, data=None, dist_backend='nccl', dist_url='tcp://224.66.41.62:23456', dummy=True, epochs=90, evaluate=True, gpu=None, ipex=True, jit=True, lr=0.1, momentum=0.9, multiprocessing_distributed=False, no_cuda=False, precision='bf16', pretrained=False, print_freq=10, rank=-1, resume='', seed=None, start_epoch=0, warmup_iterations=30, weight_decay=0.0001, workers=4, world_size=-1)
Namespace(arch='resnet50', batch_size=1, cuda=False, data=None, dist_backend='nccl', dist_url='tcp://224.66.41.62:23456', dummy=True, epochs=90, evaluate=True, gpu=None, ipex=True, jit=True, lr=0.1, momentum=0.9, multiprocessing_distributed=False, no_cuda=False, precision='bf16', pretrained=False, print_freq=10, rank=-1, resume='', seed=None, start_epoch=0, warmup_iterations=30, weight_decay=0.0001, workers=4, world_size=-1)
Namespace(arch='resnet50', batch_size=1, cuda=False, data=None, dist_backend='nccl', dist_url='tcp://224.66.41.62:23456', dummy=True, epochs=90, evaluate=True, gpu=None, ipex=True, jit=True, lr=0.1, momentum=0.9, multiprocessing_distributed=False, no_cuda=False, precision='bf16', pretrained=False, print_freq=10, rank=-1, resume='', seed=None, start_epoch=0, warmup_iterations=30, weight_decay=0.0001, workers=4, world_size=-1)
enabling intel pytorch extension path will get good performance
enabling intel pytorch extension path will get good performance
enabling intel pytorch extension path will get good performance
Namespace(arch='resnet50', batch_size=1, cuda=False, data=None, dist_backend='nccl', dist_url='tcp://224.66.41.62:23456', dummy=True, epochs=90, evaluate=True, gpu=None, ipex=True, jit=True, lr=0.1, momentum=0.9, multiprocessing_distributed=False, no_cuda=False, precision='bf16', pretrained=False, print_freq=10, rank=-1, resume='', seed=None, start_epoch=0, warmup_iterations=30, weight_decay=0.0001, workers=4, world_size=-1)
Namespace(arch='resnet50', batch_size=1, cuda=False, data=None, dist_backend='nccl', dist_url='tcp://224.66.41.62:23456', dummy=True, epochs=90, evaluate=True, gpu=None, ipex=True, jit=True, lr=0.1, momentum=0.9, multiprocessing_distributed=False, no_cuda=False, precision='bf16', pretrained=False, print_freq=10, rank=-1, resume='', seed=None, start_epoch=0, warmup_iterations=30, weight_decay=0.0001, workers=4, world_size=-1)
enabling intel pytorch extension path will get good performance
enabling intel pytorch extension path will get good performance
enabling intel pytorch extension mix precision(fp32+bf16)path
enabling intel pytorch extension mix precision(fp32+bf16)path
enabling intel pytorch extension mix precision(fp32+bf16)path
=> creating model 'resnet50'
=> creating model 'resnet50'
=> creating model 'resnet50'
Namespace(arch='resnet50', batch_size=1, cuda=False, data=None, dist_backend='nccl', dist_url='tcp://224.66.41.62:23456', dummy=True, epochs=90, evaluate=True, gpu=None, ipex=True, jit=True, lr=0.1, momentum=0.9, multiprocessing_distributed=False, no_cuda=False, precision='bf16', pretrained=False, print_freq=10, rank=-1, resume='', seed=None, start_epoch=0, warmup_iterations=30, weight_decay=0.0001, workers=4, world_size=-1)
enabling intel pytorch extension path will get good performance
Namespace(arch='resnet50', batch_size=1, cuda=False, data=None, dist_backend='nccl', dist_url='tcp://224.66.41.62:23456', dummy=True, epochs=90, evaluate=True, gpu=None, ipex=True, jit=True, lr=0.1, momentum=0.9, multiprocessing_distributed=False, no_cuda=False, precision='bf16', pretrained=False, print_freq=10, rank=-1, resume='', seed=None, start_epoch=0, warmup_iterations=30, weight_decay=0.0001, workers=4, world_size=-1)
enabling intel pytorch extension path will get good performance
enabling intel pytorch extension mix precision(fp32+bf16)path
enabling intel pytorch extension mix precision(fp32+bf16)path
=> creating model 'resnet50'
=> creating model 'resnet50'
Namespace(arch='resnet50', batch_size=1, cuda=False, data=None, dist_backend='nccl', dist_url='tcp://224.66.41.62:23456', dummy=True, epochs=90, evaluate=True, gpu=None, ipex=True, jit=True, lr=0.1, momentum=0.9, multiprocessing_distributed=False, no_cuda=False, precision='bf16', pretrained=False, print_freq=10, rank=-1, resume='', seed=None, start_epoch=0, warmup_iterations=30, weight_decay=0.0001, workers=4, world_size=-1)
enabling intel pytorch extension path will get good performance
enabling intel pytorch extension mix precision(fp32+bf16)path
enabling intel pytorch extension mix precision(fp32+bf16)path
=> creating model 'resnet50'
=> creating model 'resnet50'
enabling intel pytorch extension mix precision(fp32+bf16)path
=> creating model 'resnet50'
using CPU, this will be slow
Traceback (most recent call last):
  File "models/image_recognition/pytorch/common/main.py", line 594, in <module>
    main()
  File "models/image_recognition/pytorch/common/main.py", line 193, in main
    main_worker(args.gpu, ngpus_per_node, args)
  File "models/image_recognition/pytorch/common/main.py", line 259, in main_worker
    model = model.to(device = 'dpcpp:0')
  File "/opt/conda/lib/python3.8/site-packages/intel_pytorch_extension/ops/to.py", line 13, in to
    m = torch_to(module, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 654, in to
    device, dtype, non_blocking, convert_to_format = torch._C._nn._parse_to(*args, **kwargs)
RuntimeError: Expected one of cpu, cuda, xpu, mkldnn, opengl, opencl, ideep, hip, msnpu, xla, vulkan device type at start of device string: dpcpp
using CPU, this will be slow
using CPU, this will be slow
Traceback (most recent call last):
  File "models/image_recognition/pytorch/common/main.py", line 594, in <module>
    main()
  File "models/image_recognition/pytorch/common/main.py", line 193, in main
    main_worker(args.gpu, ngpus_per_node, args)
Traceback (most recent call last):
  File "models/image_recognition/pytorch/common/main.py", line 259, in main_worker
  File "models/image_recognition/pytorch/common/main.py", line 594, in <module>
    model = model.to(device = 'dpcpp:0')
  File "/opt/conda/lib/python3.8/site-packages/intel_pytorch_extension/ops/to.py", line 13, in to
    m = torch_to(module, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 654, in to
    main()
  File "models/image_recognition/pytorch/common/main.py", line 193, in main
    device, dtype, non_blocking, convert_to_format = torch._C._nn._parse_to(*args, **kwargs)
RuntimeError: Expected one of cpu, cuda, xpu, mkldnn, opengl, opencl, ideep, hip, msnpu, xla, vulkan device type at start of device string: dpcpp
    main_worker(args.gpu, ngpus_per_node, args)
  File "models/image_recognition/pytorch/common/main.py", line 259, in main_worker
    model = model.to(device = 'dpcpp:0')
  File "/opt/conda/lib/python3.8/site-packages/intel_pytorch_extension/ops/to.py", line 13, in to
    m = torch_to(module, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 654, in to
    device, dtype, non_blocking, convert_to_format = torch._C._nn._parse_to(*args, **kwargs)
RuntimeError: Expected one of cpu, cuda, xpu, mkldnn, opengl, opencl, ideep, hip, msnpu, xla, vulkan device type at start of device string: dpcpp
using CPU, this will be slow
Traceback (most recent call last):
  File "models/image_recognition/pytorch/common/main.py", line 594, in <module>
    main()
  File "models/image_recognition/pytorch/common/main.py", line 193, in main
    main_worker(args.gpu, ngpus_per_node, args)
  File "models/image_recognition/pytorch/common/main.py", line 259, in main_worker
    model = model.to(device = 'dpcpp:0')
  File "/opt/conda/lib/python3.8/site-packages/intel_pytorch_extension/ops/to.py", line 13, in to
    m = torch_to(module, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 654, in to
    device, dtype, non_blocking, convert_to_format = torch._C._nn._parse_to(*args, **kwargs)
RuntimeError: Expected one of cpu, cuda, xpu, mkldnn, opengl, opencl, ideep, hip, msnpu, xla, vulkan device type at start of device string: dpcpp
using CPU, this will be slow
Traceback (most recent call last):
  File "models/image_recognition/pytorch/common/main.py", line 594, in <module>
    main()
  File "models/image_recognition/pytorch/common/main.py", line 193, in main
    main_worker(args.gpu, ngpus_per_node, args)
  File "models/image_recognition/pytorch/common/main.py", line 259, in main_worker
    model = model.to(device = 'dpcpp:0')
  File "/opt/conda/lib/python3.8/site-packages/intel_pytorch_extension/ops/to.py", line 13, in to
    m = torch_to(module, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 654, in to
    device, dtype, non_blocking, convert_to_format = torch._C._nn._parse_to(*args, **kwargs)
RuntimeError: Expected one of cpu, cuda, xpu, mkldnn, opengl, opencl, ideep, hip, msnpu, xla, vulkan device type at start of device string: dpcpp
using CPU, this will be slow
Traceback (most recent call last):
  File "models/image_recognition/pytorch/common/main.py", line 594, in <module>
    main()
  File "models/image_recognition/pytorch/common/main.py", line 193, in main
    main_worker(args.gpu, ngpus_per_node, args)
  File "models/image_recognition/pytorch/common/main.py", line 259, in main_worker
    model = model.to(device = 'dpcpp:0')
  File "/opt/conda/lib/python3.8/site-packages/intel_pytorch_extension/ops/to.py", line 13, in to
    m = torch_to(module, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 654, in to
    device, dtype, non_blocking, convert_to_format = torch._C._nn._parse_to(*args, **kwargs)
RuntimeError: Expected one of cpu, cuda, xpu, mkldnn, opengl, opencl, ideep, hip, msnpu, xla, vulkan device type at start of device string: dpcpp
using CPU, this will be slow
Traceback (most recent call last):
  File "models/image_recognition/pytorch/common/main.py", line 594, in <module>
    main()
  File "models/image_recognition/pytorch/common/main.py", line 193, in main
    main_worker(args.gpu, ngpus_per_node, args)
  File "models/image_recognition/pytorch/common/main.py", line 259, in main_worker
    model = model.to(device = 'dpcpp:0')
  File "/opt/conda/lib/python3.8/site-packages/intel_pytorch_extension/ops/to.py", line 13, in to
    m = torch_to(module, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 654, in to
    device, dtype, non_blocking, convert_to_format = torch._C._nn._parse_to(*args, **kwargs)
RuntimeError: Expected one of cpu, cuda, xpu, mkldnn, opengl, opencl, ideep, hip, msnpu, xla, vulkan device type at start of device string: dpcpp
using CPU, this will be slow
Traceback (most recent call last):
  File "models/image_recognition/pytorch/common/main.py", line 594, in <module>
    main()
  File "models/image_recognition/pytorch/common/main.py", line 193, in main
    main_worker(args.gpu, ngpus_per_node, args)
  File "models/image_recognition/pytorch/common/main.py", line 259, in main_worker
    model = model.to(device = 'dpcpp:0')
  File "/opt/conda/lib/python3.8/site-packages/intel_pytorch_extension/ops/to.py", line 13, in to
    m = torch_to(module, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 654, in to
    device, dtype, non_blocking, convert_to_format = torch._C._nn._parse_to(*args, **kwargs)
RuntimeError: Expected one of cpu, cuda, xpu, mkldnn, opengl, opencl, ideep, hip, msnpu, xla, vulkan device type at start of device string: dpcpp
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.8/site-packages/intel_pytorch_extension/launch.py", line 649, in <module>
    main()
  File "/opt/conda/lib/python3.8/site-packages/intel_pytorch_extension/launch.py", line 643, in main
    launch(args)
  File "/opt/conda/lib/python3.8/site-packages/intel_pytorch_extension/launch.py", line 385, in launch
    raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command '['numactl', '-C', '14', '/opt/conda/bin/python3', 'models/image_recognition/pytorch/common/main.py', '--arch', 'resnet50', '--evaluate', '--ipex', '--jit', '--precision', 'bf16', '--batch-size', '1', '--dummy']' returned non-zero exit status 1.`

**Comment by EikanWang** [comment]
I wonder if you could verify the IPEX 1.10 pre-release version.

- Install PyTorch 1.10
- Switch IPEX to the `release/1.10` branch and then build from source

**Comment by EikanWang** [comment]
I suppose this issue has been fixed because we have changed the underhood device from XPU to CPU for the CPU devices. Please feel free to reopen it if not.
