### ISSUE TITLE
Can't install intel extension for pytorch

### ISSUE THREAD

**Issue by EdenBelouadah** [intel/intel-extension-for-pytorch#197]
Hello,
I am trying to install "intel extension for pytorch" following the readme of this repository. I am getting the following error when I run the "python setup.py install" command:

```
[ 83%] Built target dnnl_cpu_x64
[ 83%] Linking CXX static library ../../../../../packages/intel_extension_for_pytorch/lib/libdnnl.a
[ 83%] Built target dnnl
[ 83%] Linking CXX shared library ../../../packages/intel_extension_for_pytorch/lib/libdnnl_graph.so
[ 83%] Built target dnnl_graph
Consolidate compiler generated dependencies of target intel-ext-pt-cpu
[ 83%] Building CXX object CMakeFiles/intel-ext-pt-cpu.dir/torch_ipex/csrc/version.cpp.o
[ 83%] Building CXX object CMakeFiles/intel-ext-pt-cpu.dir/torch_ipex/csrc/utils.cpp.o
[ 83%] Building CXX object CMakeFiles/intel-ext-pt-cpu.dir/torch_ipex/csrc/verbose.cpp.o
[ 83%] Building CXX object CMakeFiles/intel-ext-pt-cpu.dir/torch_ipex/csrc/autocast_mode.cpp.o
[ 84%] Building CXX object CMakeFiles/intel-ext-pt-cpu.dir/torch_ipex/csrc/LlgaTensorImpl.cpp.o
[ 84%] Building CXX object CMakeFiles/intel-ext-pt-cpu.dir/torch_ipex/csrc/autocast_kernel.cpp.o
[ 84%] Building CXX object CMakeFiles/intel-ext-pt-cpu.dir/torch_ipex/csrc/autocast_verbose.cpp.o
[ 84%] Building CXX object CMakeFiles/intel-ext-pt-cpu.dir/torch_ipex/csrc/quantization/AutoCast.cpp.o
[ 84%] Building CXX object CMakeFiles/intel-ext-pt-cpu.dir/torch_ipex/csrc/quantization/AutoCast_utils.cpp.o
[ 85%] Building CXX object CMakeFiles/intel-ext-pt-cpu.dir/torch_ipex/csrc/quantization/Common.cpp.o
In file included from /home/eden/Downloads/intel-extension-for-pytorch/ideep/ideep/computations.hpp:20,
                 from /home/eden/Downloads/intel-extension-for-pytorch/ideep/ideep.hpp:41,
                 from /home/eden/Downloads/intel-extension-for-pytorch/torch_ipex/csrc/cpu/mkldnn/MKLDNNCommon.h:6,
                 from /home/eden/Downloads/intel-extension-for-pytorch/torch_ipex/csrc/verbose.cpp:3:
/home/eden/Downloads/intel-extension-for-pytorch/ideep/ideep/operators/matmul.hpp: In static member function ‘static ideep::tensor::desc ideep::matmul_forward::expected_weights_desc(const dims&, ideep::data_type, ideep::data_type, const ideep::engine&)’:
/home/eden/Downloads/intel-extension-for-pytorch/ideep/ideep/operators/matmul.hpp:85:54: warning: assignment from temporary initializer_list does not extend the lifetime of the underlying array [-Winit-list-lifetime]
   85 |       y_dims = {x_dims[0], x_dims[1], weights_dims[2]};
      |                                                      ^
/home/eden/Downloads/intel-extension-for-pytorch/torch_ipex/csrc/autocast_mode.cpp: In function ‘void torch_ipex::autocast::TORCH_LIBRARY_IMPL_init_aten_AutocastCPU_82(torch::Library&)’:
/home/eden/Downloads/intel-extension-for-pytorch/torch_ipex/csrc/autocast_mode.cpp:172:72: error: could not convert template argument ‘& at::linalg_matrix_rank’ from ‘<unresolved overloaded function type>’ to ‘at::Tensor (*)(const at::Tensor&, double, bool)’
  172 |         &CPU_WrapFunction<DtypeCastPolicy::CAST_POLICY, SIG, SIG, &FUNC>:: \
      |                                                                        ^
/home/eden/Downloads/intel-extension-for-pytorch/torch_ipex/csrc/autocast_mode.cpp:443:1: note: in expansion of macro ‘MAKE_REGISTER_FUNC’
  443 | MAKE_REGISTER_FUNC(
      | ^~~~~~~~~~~~~~~~~~
/home/eden/Downloads/intel-extension-for-pytorch/torch_ipex/csrc/autocast_mode.cpp:173:13: error: ‘<expression error>::type’ has not been declared
  173 |             type::call);                                                   \
      |             ^~~~
/home/eden/Downloads/intel-extension-for-pytorch/torch_ipex/csrc/autocast_mode.cpp:173:13: note: in definition of macro ‘MAKE_REGISTER_FUNC’
  173 |             type::call);                                                   \
      |             ^~~~
/home/eden/Downloads/intel-extension-for-pytorch/torch_ipex/csrc/autocast_mode.cpp: At global scope:
/home/eden/Downloads/intel-extension-for-pytorch/torch_ipex/csrc/autocast_mode.cpp:176:15: error: template-id ‘get_op_name<at::Tensor(const at::Tensor&, double, bool), at::linalg_matrix_rank>’ for ‘std::string torch_ipex::autocast::get_op_name()’ does not match any template declaration
  176 |   std::string get_op_name<SIG, FUNC>() {                                   \
      |               ^~~~~~~~~~~~~~~~~~~~~~
/home/eden/Downloads/intel-extension-for-pytorch/torch_ipex/csrc/autocast_mode.cpp:176:15: note: in definition of macro ‘MAKE_REGISTER_FUNC’
  176 |   std::string get_op_name<SIG, FUNC>() {                                   \
      |               ^~~~~~~~~~~
In file included from /home/eden/Downloads/intel-extension-for-pytorch/torch_ipex/csrc/autocast_mode.cpp:1:
/home/eden/Downloads/intel-extension-for-pytorch/torch_ipex/csrc/autocast_mode.h:150:13: note: candidate is: ‘template<class Redispatch, Redispatch* F> std::string torch_ipex::autocast::get_op_name()’
  150 | std::string get_op_name() {
      |             ^~~~~~~~~~~
/home/eden/Downloads/intel-extension-for-pytorch/torch_ipex/csrc/autocast_mode.cpp: In function ‘void torch_ipex::autocast::TORCH_LIBRARY_IMPL_init_aten_AutocastCPU_83(torch::Library&)’:
/home/eden/Downloads/intel-extension-for-pytorch/torch_ipex/csrc/autocast_mode.cpp:172:72: error: could not convert template argument ‘& at::linalg_matrix_rank’ from ‘<unresolved overloaded function type>’ to ‘at::Tensor (*)(const at::Tensor&, const c10::optional<at::Tensor>&, const c10::optional<at::Tensor>&, bool)’
  172 |         &CPU_WrapFunction<DtypeCastPolicy::CAST_POLICY, SIG, SIG, &FUNC>:: \
      |                                                                        ^
/home/eden/Downloads/intel-extension-for-pytorch/torch_ipex/csrc/autocast_mode.cpp:448:1: note: in expansion of macro ‘MAKE_REGISTER_FUNC’
  448 | MAKE_REGISTER_FUNC(
      | ^~~~~~~~~~~~~~~~~~
/home/eden/Downloads/intel-extension-for-pytorch/torch_ipex/csrc/autocast_mode.cpp:173:13: error: ‘<expression error>::type’ has not been declared
  173 |             type::call);                                                   \
      |             ^~~~
/home/eden/Downloads/intel-extension-for-pytorch/torch_ipex/csrc/autocast_mode.cpp:173:13: note: in definition of macro ‘MAKE_REGISTER_FUNC’
  173 |             type::call);                                                   \
      |             ^~~~
/home/eden/Downloads/intel-extension-for-pytorch/torch_ipex/csrc/autocast_mode.cpp: At global scope:
/home/eden/Downloads/intel-extension-for-pytorch/torch_ipex/csrc/autocast_mode.cpp:176:15: error: template-id ‘get_op_name<at::Tensor(const at::Tensor&, const c10::optional<at::Tensor>&, const c10::optional<at::Tensor>&, bool), at::linalg_matrix_rank>’ for ‘std::string torch_ipex::autocast::get_op_name()’ does not match any template declaration
  176 |   std::string get_op_name<SIG, FUNC>() {                                   \
      |               ^~~~~~~~~~~~~~~~~~~~~~
/home/eden/Downloads/intel-extension-for-pytorch/torch_ipex/csrc/autocast_mode.cpp:176:15: note: in definition of macro ‘MAKE_REGISTER_FUNC’
  176 |   std::string get_op_name<SIG, FUNC>() {                                   \
      |               ^~~~~~~~~~~
In file included from /home/eden/Downloads/intel-extension-for-pytorch/torch_ipex/csrc/autocast_mode.cpp:1:
/home/eden/Downloads/intel-extension-for-pytorch/torch_ipex/csrc/autocast_mode.h:150:13: note: candidate is: ‘template<class Redispatch, Redispatch* F> std::string torch_ipex::autocast::get_op_name()’
  150 | std::string get_op_name() {
      |             ^~~~~~~~~~~
/home/eden/Downloads/intel-extension-for-pytorch/torch_ipex/csrc/autocast_mode.cpp: In function ‘void torch_ipex::autocast::TORCH_LIBRARY_IMPL_init_aten_AutocastCPU_84(torch::Library&)’:
/home/eden/Downloads/intel-extension-for-pytorch/torch_ipex/csrc/autocast_mode.cpp:172:72: error: could not convert template argument ‘& at::linalg_matrix_rank’ from ‘<unresolved overloaded function type>’ to ‘at::Tensor (*)(const at::Tensor&, c10::optional<double>, c10::optional<double>, bool)’
  172 |         &CPU_WrapFunction<DtypeCastPolicy::CAST_POLICY, SIG, SIG, &FUNC>:: \
      |                                                                        ^
/home/eden/Downloads/intel-extension-for-pytorch/torch_ipex/csrc/autocast_mode.cpp:457:1: note: in expansion of macro ‘MAKE_REGISTER_FUNC’
  457 | MAKE_REGISTER_FUNC(
      | ^~~~~~~~~~~~~~~~~~
/home/eden/Downloads/intel-extension-for-pytorch/torch_ipex/csrc/autocast_mode.cpp:173:13: error: ‘<expression error>::type’ has not been declared
  173 |             type::call);                                                   \
      |             ^~~~
/home/eden/Downloads/intel-extension-for-pytorch/torch_ipex/csrc/autocast_mode.cpp:173:13: note: in definition of macro ‘MAKE_REGISTER_FUNC’
  173 |             type::call);                                                   \
      |             ^~~~
/home/eden/Downloads/intel-extension-for-pytorch/torch_ipex/csrc/autocast_mode.cpp: At global scope:
/home/eden/Downloads/intel-extension-for-pytorch/torch_ipex/csrc/autocast_mode.cpp:176:15: error: template-id ‘get_op_name<at::Tensor(const at::Tensor&, c10::optional<double>, c10::optional<double>, bool), at::linalg_matrix_rank>’ for ‘std::string torch_ipex::autocast::get_op_name()’ does not match any template declaration
  176 |   std::string get_op_name<SIG, FUNC>() {                                   \
      |               ^~~~~~~~~~~~~~~~~~~~~~
/home/eden/Downloads/intel-extension-for-pytorch/torch_ipex/csrc/autocast_mode.cpp:176:15: note: in definition of macro ‘MAKE_REGISTER_FUNC’
  176 |   std::string get_op_name<SIG, FUNC>() {                                   \
      |               ^~~~~~~~~~~
In file included from /home/eden/Downloads/intel-extension-for-pytorch/torch_ipex/csrc/autocast_mode.cpp:1:
/home/eden/Downloads/intel-extension-for-pytorch/torch_ipex/csrc/autocast_mode.h:150:13: note: candidate is: ‘template<class Redispatch, Redispatch* F> std::string torch_ipex::autocast::get_op_name()’
  150 | std::string get_op_name() {
      |             ^~~~~~~~~~~
In file included from /home/eden/Downloads/intel-extension-for-pytorch/ideep/ideep/computations.hpp:20,
                 from /home/eden/Downloads/intel-extension-for-pytorch/ideep/ideep.hpp:41,
                 from /home/eden/Downloads/intel-extension-for-pytorch/torch_ipex/csrc/cpu/BatchNorm.h:7,
                 from /home/eden/Downloads/intel-extension-for-pytorch/torch_ipex/csrc/autocast_kernel.cpp:4:
/home/eden/Downloads/intel-extension-for-pytorch/ideep/ideep/operators/matmul.hpp: In static member function ‘static ideep::tensor::desc ideep::matmul_forward::expected_weights_desc(const dims&, ideep::data_type, ideep::data_type, const ideep::engine&)’:
/home/eden/Downloads/intel-extension-for-pytorch/ideep/ideep/operators/matmul.hpp:85:54: warning: assignment from temporary initializer_list does not extend the lifetime of the underlying array [-Winit-list-lifetime]
   85 |       y_dims = {x_dims[0], x_dims[1], weights_dims[2]};
      |                                                      ^
[ 85%] Building CXX object CMakeFiles/intel-ext-pt-cpu.dir/torch_ipex/csrc/quantization/Config.cpp.o
[ 85%] Building CXX object CMakeFiles/intel-ext-pt-cpu.dir/torch_ipex/csrc/cpu/AdaptiveAveragePooling.cpp.o
[ 85%] Building CXX object CMakeFiles/intel-ext-pt-cpu.dir/torch_ipex/csrc/cpu/AdaptiveMaxPooling.cpp.o
make[2]: *** [CMakeFiles/intel-ext-pt-cpu.dir/build.make:118: CMakeFiles/intel-ext-pt-cpu.dir/torch_ipex/csrc/autocast_mode.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:468: CMakeFiles/intel-ext-pt-cpu.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
Traceback (most recent call last):
  File "/home/eden/Downloads/intel-extension-for-pytorch/setup.py", line 585, in <module>
    setup(
  File "/home/eden/installs/anaconda3/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/eden/installs/anaconda3/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/eden/installs/anaconda3/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/eden/installs/anaconda3/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/eden/installs/anaconda3/lib/python3.9/distutils/command/install.py", line 546, in run
    self.run_command('build')
  File "/home/eden/installs/anaconda3/lib/python3.9/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/eden/installs/anaconda3/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/eden/installs/anaconda3/lib/python3.9/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/eden/installs/anaconda3/lib/python3.9/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/eden/installs/anaconda3/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/eden/Downloads/intel-extension-for-pytorch/setup.py", line 496, in run
    check_call(['make'] + build_args, cwd=build_type_dir, env=env)
  File "/home/eden/installs/anaconda3/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-j', '8']' returned non-zero exit status 2.
(base) eden@eden-Inspiron-15-5510:~/Downloads/intel-extension-for-pytorch$ 

```
Some elements that can help: 

```
(base) eden@eden-Inspiron-15-5510:~/Downloads/intel-extension-for-pytorch$ gcc --version
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

(base) eden@eden-Inspiron-15-5510:~/Downloads/intel-extension-for-pytorch$ python
Python 3.9.7 (default, Sep 16 2021, 13:09:58) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'1.10.0'

```

Thank you for your help.

**Comment by michele-arrival** [comment]
same here, lots of template erros in autocast_mode.cpp :(

```
[ 83%] Building CXX object CMakeFiles/intel-ext-pt-cpu.dir/torch_ipex/csrc/autocast_mode.cpp.o
/home/michele/workspace/intel-extension-for-pytorch/torch_ipex/csrc/autocast_mode.cpp: In function ‘void torch_ipex::autocast::TORCH_LIBRARY_IMPL_init_aten_AutocastCPU_82(torch::Library&)’:
/home/michele/workspace/intel-extension-for-pytorch/torch_ipex/csrc/autocast_mode.cpp:172:72: error: could not convert template argument ‘& at::linalg_matrix_rank’ from ‘<unresolved overloaded function type>’ to ‘at::Tensor (*)(const at::Tensor&, double, bool)’
         &CPU_WrapFunction<DtypeCastPolicy::CAST_POLICY, SIG, SIG, &FUNC>:: \
                                                                        ^
/home/michele/workspace/intel-extension-for-pytorch/torch_ipex/csrc/autocast_mode.cpp:443:1: note: in expansion of macro ‘MAKE_REGISTER_FUNC’
 MAKE_REGISTER_FUNC(
 ^~~~~~~~~~~~~~~~~~
/home/michele/workspace/intel-extension-for-pytorch/torch_ipex/csrc/autocast_mode.cpp:173:13: error: ‘<expression error>::type’ has not been declared
             type::call);                                                   \
             ^~~~
/home/michele/workspace/intel-extension-for-pytorch/torch_ipex/csrc/autocast_mode.cpp:173:13: note: in definition of macro ‘MAKE_REGISTER_FUNC’
             type::call);                                                   \
             ^~~~
/home/michele/workspace/intel-extension-for-pytorch/torch_ipex/csrc/autocast_mode.cpp: At global scope:
/home/michele/workspace/intel-extension-for-pytorch/torch_ipex/csrc/autocast_mode.cpp:176:15: error: template-id ‘get_op_name<at::Tensor(const at::Tensor&, double, bool), at::linalg_matrix_rank>’ for ‘std::string torch_ipex::autocast::get_op_name()’ does not match any template declaration
   std::string get_op_name<SIG, FUNC>() {                                   \
               ^~~~~~~~~~~~~~~~~~~~~~
/home/michele/workspace/intel-extension-for-pytorch/torch_ipex/csrc/autocast_mode.cpp:176:15: note: in definition of macro ‘MAKE_REGISTER_FUNC’
   std::string get_op_name<SIG, FUNC>() {                                   \
               ^~~~~~~~~~~
In file included from /home/michele/workspace/intel-extension-for-pytorch/torch_ipex/csrc/autocast_mode.cpp:1:
/home/michele/workspace/intel-extension-for-pytorch/torch_ipex/csrc/autocast_mode.h:150:13: note: candidate is: ‘template<class Redispatch, Redispatch* F> std::string torch_ipex::autocast::get_op_name()’
 std::string get_op_name() {
             ^~~~~~~~~~~
/home/michele/workspace/intel-extension-for-pytorch/torch_ipex/csrc/autocast_mode.cpp: In function ‘void torch_ipex::autocast::TORCH_LIBRARY_IMPL_init_aten_AutocastCPU_83(torch::Library&)’:
/home/michele/workspace/intel-extension-for-pytorch/torch_ipex/csrc/autocast_mode.cpp:172:72: error: could not convert template argument ‘& at::linalg_matrix_rank’ from ‘<unresolved overloaded function type>’ to ‘at::Tensor (*)(const at::Tensor&, const c10::optional<at::Tensor>&, const c10::optional<at::Tensor>&, bool)’
         &CPU_WrapFunction<DtypeCastPolicy::CAST_POLICY, SIG, SIG, &FUNC>:: \
                                                                        ^
/home/michele/workspace/intel-extension-for-pytorch/torch_ipex/csrc/autocast_mode.cpp:448:1: note: in expansion of macro ‘MAKE_REGISTER_FUNC’
 MAKE_REGISTER_FUNC(
 ^~~~~~~~~~~~~~~~~~
/home/michele/workspace/intel-extension-for-pytorch/torch_ipex/csrc/autocast_mode.cpp:173:13: error: ‘<expression error>::type’ has not been declared
             type::call);                                                   \
             ^~~~
/home/michele/workspace/intel-extension-for-pytorch/torch_ipex/csrc/autocast_mode.cpp:173:13: note: in definition of macro ‘MAKE_REGISTER_FUNC’
             type::call);                                                   \
             ^~~~
/home/michele/workspace/intel-extension-for-pytorch/torch_ipex/csrc/autocast_mode.cpp: At global scope:
/home/michele/workspace/intel-extension-for-pytorch/torch_ipex/csrc/autocast_mode.cpp:176:15: error: template-id ‘get_op_name<at::Tensor(const at::Tensor&, const c10::optional<at::Tensor>&, const c10::optional<at::Tensor>&, bool), at::linalg_matrix_rank>’ for ‘std::string torch_ipex::autocast::get_op_name()’ does not match any template declaration
   std::string get_op_name<SIG, FUNC>() {                                   \
               ^~~~~~~~~~~~~~~~~~~~~~
/home/michele/workspace/intel-extension-for-pytorch/torch_ipex/csrc/autocast_mode.cpp:176:15: note: in definition of macro ‘MAKE_REGISTER_FUNC’
   std::string get_op_name<SIG, FUNC>() {                                   \
               ^~~~~~~~~~~
In file included from /home/michele/workspace/intel-extension-for-pytorch/torch_ipex/csrc/autocast_mode.cpp:1:
/home/michele/workspace/intel-extension-for-pytorch/torch_ipex/csrc/autocast_mode.h:150:13: note: candidate is: ‘template<class Redispatch, Redispatch* F> std::string torch_ipex::autocast::get_op_name()’
 std::string get_op_name() {
             ^~~~~~~~~~~
/home/michele/workspace/intel-extension-for-pytorch/torch_ipex/csrc/autocast_mode.cpp: In function ‘void torch_ipex::autocast::TORCH_LIBRARY_IMPL_init_aten_AutocastCPU_84(torch::Library&)’:
/home/michele/workspace/intel-extension-for-pytorch/torch_ipex/csrc/autocast_mode.cpp:172:72: error: could not convert template argument ‘& at::linalg_matrix_rank’ from ‘<unresolved overloaded function type>’ to ‘at::Tensor (*)(const at::Tensor&, c10::optional<double>, c10::optional<double>, bool)’
         &CPU_WrapFunction<DtypeCastPolicy::CAST_POLICY, SIG, SIG, &FUNC>:: \
                                                                        ^
/home/michele/workspace/intel-extension-for-pytorch/torch_ipex/csrc/autocast_mode.cpp:457:1: note: in expansion of macro ‘MAKE_REGISTER_FUNC’
 MAKE_REGISTER_FUNC(
 ^~~~~~~~~~~~~~~~~~
/home/michele/workspace/intel-extension-for-pytorch/torch_ipex/csrc/autocast_mode.cpp:173:13: error: ‘<expression error>::type’ has not been declared
             type::call);                                                   \
             ^~~~
/home/michele/workspace/intel-extension-for-pytorch/torch_ipex/csrc/autocast_mode.cpp:173:13: note: in definition of macro ‘MAKE_REGISTER_FUNC’
             type::call);                                                   \
             ^~~~
/home/michele/workspace/intel-extension-for-pytorch/torch_ipex/csrc/autocast_mode.cpp: At global scope:
/home/michele/workspace/intel-extension-for-pytorch/torch_ipex/csrc/autocast_mode.cpp:176:15: error: template-id ‘get_op_name<at::Tensor(const at::Tensor&, c10::optional<double>, c10::optional<double>, bool), at::linalg_matrix_rank>’ for ‘std::string torch_ipex::autocast::get_op_name()’ does not match any template declaration
   std::string get_op_name<SIG, FUNC>() {                                   \
               ^~~~~~~~~~~~~~~~~~~~~~
/home/michele/workspace/intel-extension-for-pytorch/torch_ipex/csrc/autocast_mode.cpp:176:15: note: in definition of macro ‘MAKE_REGISTER_FUNC’
   std::string get_op_name<SIG, FUNC>() {                                   \
               ^~~~~~~~~~~
In file included from /home/michele/workspace/intel-extension-for-pytorch/torch_ipex/csrc/autocast_mode.cpp:1:
/home/michele/workspace/intel-extension-for-pytorch/torch_ipex/csrc/autocast_mode.h:150:13: note: candidate is: ‘template<class Redispatch, Redispatch* F> std::string torch_ipex::autocast::get_op_name()’
 std::string get_op_name() {
             ^~~~~~~~~~~
make[2]: *** [CMakeFiles/intel-ext-pt-cpu.dir/build.make:118: CMakeFiles/intel-ext-pt-cpu.dir/torch_ipex/csrc/autocast_mode.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:468: CMakeFiles/intel-ext-pt-cpu.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

Using: 
```
gcc-10 (Ubuntu 10.3.0-1ubuntu1~20.04) 10.3.0

Python 3.7.11 (default, Jul 27 2021, 14:32:16) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
```

Any ideas? thanks!

**Comment by EikanWang** [comment]
@EdenBelouadah , @michele-arrival , Could you please switch the code to the [release/1.10](https://github.com/intel-innersource/frameworks.ai.pytorch.ipex-cpu/tree/release/1.10) branch and install PyTorch 1.10.

**Comment by EikanWang** [comment]
@EdenBelouadah @michele-arrival , we have released the binary, you can install via pip directly now. https://intel.github.io/intel-extension-for-pytorch/tutorials/installation.html#

**Comment by EdenBelouadah** [comment]
@EikanWang 
Thank you very much. It is working perfectly using the new installation guide. 
One last (dummy) question please. What is the equivalent of 'nvidia-smi' in this graphical card? (Mesa Intel® Xe Graphics (TGL GT2)), to check how much gpu my model is occupying? 

Thank you very much again

**Comment by michele-arrival** [comment]
> @EdenBelouadah @michele-arrival , we have released the binary, you can install via pip directly now. https://intel.github.io/intel-extension-for-pytorch/tutorials/installation.html#

Thanks it works compiling from release branch! 

how experimental is AVX2 now that 1.10 has been released?

cheers

**Comment by EikanWang** [comment]
@EdenBelouadah , What's your mean of "this graph card"? Currently, the IPEX has not supported Intel GPU yet.

**Comment by EikanWang** [comment]
@michele-arrival , you can install AVX2 1.10 from the source -  `AVX2=1 python setup.py install`.

**Comment by michele-arrival** [comment]
Thanks @EikanWang  I was able to do that whitout issue. 

I was wondering though, how much should I AVX2 experimental in this release or if i should trust it's stable?

I've run the Inference - BFloat16 - Resnet example from here: https://intel.github.io/intel-extension-for-pytorch/tutorials/examples.html#id7 after compiling for AVX2 and i see this error: 

```Traceback (most recent call last):
  File "/home/michele/.config/JetBrains/PyCharmCE2021.3/scratches/scratch_4.py", line 10, in <module>
    model = ipex.optimize(model, dtype=torch.bfloat16)
  File "/home/michele/anaconda3/envs/legged/lib/python3.7/site-packages/intel_extension_for_pytorch/frontend.py", line 270, in optimize
    optimized_model, optimized_optimizer, params_attr, opt_properties.auto_kernel_selection)
  File "/home/michele/anaconda3/envs/legged/lib/python3.7/site-packages/intel_extension_for_pytorch/nn/utils/_weight_prepack.py", line 362, in weight_prepack_with_ipex
    opt_model, opt_optmizer, params_attr = convert_rec(module, auto_kernel_selection), optimizer, params_attr
  File "/home/michele/anaconda3/envs/legged/lib/python3.7/site-packages/intel_extension_for_pytorch/nn/utils/_weight_prepack.py", line 359, in convert_rec
    setattr(new_m, name, convert_rec(sub_m, auto_kernel_selection))
  File "/home/michele/anaconda3/envs/legged/lib/python3.7/site-packages/intel_extension_for_pytorch/nn/utils/_weight_prepack.py", line 357, in convert_rec
    new_m = convert(m, auto_kernel_selection)
  File "/home/michele/anaconda3/envs/legged/lib/python3.7/site-packages/intel_extension_for_pytorch/nn/utils/_weight_prepack.py", line 298, in convert
    new_m = _IPEXConv2d(m)
  File "/home/michele/anaconda3/envs/legged/lib/python3.7/site-packages/intel_extension_for_pytorch/nn/utils/_weight_prepack.py", line 48, in __init__
    self.groups))
RuntimeError: could not create a primitive descriptor iterator```

cheers
