### ISSUE TITLE
Runtime error during inference of optimised ipex_prepack

### ISSUE THREAD

**Issue by xsacha** [intel/intel-extension-for-pytorch#202]
```Python
Traceback (most recent call last):
  File "detect_quantized.py", line 341, in <module>
    test(net, device, args)
  File "detect_quantized.py", line 101, in test
    feature = model(img)  # forward pass
  File "/home/sacha/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
    graph(%input, %weight, %bias, %accumu, %alpha, %stride:int[], %padding:int[], %dilation:int[], %kernel_size:int[], %groups:int, %output_channel:int, %weight_is_channels_last:bool, %weight_is_prepacked:bool, %input_size:int[]):
        %packed_weight = ipex_prepack::convolution_prepack(%weight, %bias, %stride, %padding, %dilation, %kernel_size, %groups, %output_channel, %weight_is_channels_last, %weight_is_prepacked, %input_size)
        %res = ipex_prepack::convolution_add_run(%input, %accumu, %alpha, %packed_weight)
               ~~~~~~~~~~~~ <--- HERE
        return (%res)
RuntimeError: input and output need has same format for convolution_kernel_output
```

CPU: i7-6850K AVX2
Version: 1.10

Update: If I do not run 'optimize' and do not use channels-last, then I do not get this error. I think because prepack is only run during optimize or channels-last?

As far as I can tell, the only thing special about the models that fail in this way is that they use PReLU and BatchNorm1D.

**Comment by EikanWang** [comment]
@XiaobingSuper , could you please take a look at this error?

**Comment by EikanWang** [comment]
@xsacha , it is an issue of IPEX. Please refer to https://github.com/intel/intel-extension-for-pytorch/commit/51fde78317f678ab5832ee12959e710e04f26bbc

**Comment by xsacha** [comment]
Thanks. Works now.
