### ISSUE TITLE
Error while running IntelAI models script

### ISSUE THREAD

**Issue by eralmual** [intel/intel-extension-for-pytorch#227]
Hi! I've been trying to setup one of the models provided in [Intel AI git repo](https://github.com/IntelAI/models)(tested on branch _pytorch-r1.11-models_ and _r2.7,_) I've tried building Pytorch, IPEX and everything else following their [Bare Metal set up](https://github.com/IntelAI/models/blob/pytorch-r1.11-models/docs/general/pytorch/BareMetalSetup.md) and once more using pip to install all the required libraries in case I was messing up the builds.

The error happens when I try to run the inference_throughput.sh in [here](https://github.com/IntelAI/models/blob/r2.7/quickstart/object_detection/pytorch/ssd-resnet34/inference/cpu/inference_throughput.sh), and the message shows:

```
$ bash inference_throughput.sh fp32
### running fp32 datatype
/home/erick/anaconda3/envs/pip_ipex/lib/python3.7/runpy.py:125: RuntimeWarning: 'intel_extension_for_pytorch.cpu.launch' found in sys.modules after import of package 'intel_extension_for_pytorch.cpu', but prior to execution of 'intel_extension_for_pytorch.cpu.launch'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
Traceback (most recent call last):
  File "/home/erick/anaconda3/envs/pip_ipex/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/erick/anaconda3/envs/pip_ipex/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/erick/anaconda3/envs/pip_ipex/lib/python3.7/site-packages/intel_extension_for_pytorch/cpu/launch.py", line 805, in <module>
    main()
  File "/home/erick/anaconda3/envs/pip_ipex/lib/python3.7/site-packages/intel_extension_for_pytorch/cpu/launch.py", line 753, in main
    args = parse_args()
  File "/home/erick/anaconda3/envs/pip_ipex/lib/python3.7/site-packages/intel_extension_for_pytorch/cpu/launch.py", line 736, in parse_args
    add_distributed_training_params(parser)
  File "/home/erick/anaconda3/envs/pip_ipex/lib/python3.7/site-packages/intel_extension_for_pytorch/cpu/launch.py", line 617, in add_distributed_training_params
    cpuinfo = CPUinfo()
  File "/home/erick/anaconda3/envs/pip_ipex/lib/python3.7/site-packages/intel_extension_for_pytorch/cpu/launch.py", line 141, in __init__
    self.get_socket_info()
  File "/home/erick/anaconda3/envs/pip_ipex/lib/python3.7/site-packages/intel_extension_for_pytorch/cpu/launch.py", line 150, in get_socket_info
    self.nodes = int(max([line[3] for line in self.cpuinfo])) + 1
ValueError: invalid literal for int() with base 10: ''
awk: cmd. line:11: fatal: division by zero attempted
SSD-RN34;throughput;fp32; 112;
```

I'm running this on Windows 10 WSL2 Ubuntu 20.04, could that be the problem? The error appears both when I try to build from source and when I install from pip.

I'm using pytorch 1.11.0 and IPEX 1.11.0, I've tried using python 3.9 and 3.7 but the error persists.

**Comment by jingxu10** [comment]
Behavior of lscpu on WSL is a little bit different than that on a real Linux system. As a workaround, you can change `line[3]` to `line[2]` in `/home/erick/anaconda3/envs/pip_ipex/lib/python3.7/site-packages/intel_extension_for_pytorch/cpu/launch.py`. We will fix this soon.

Output of `lscpu --parse=CPU,Core,Socket,Node` is expected to contain 4 columns, but on WSL, only the leading 3 are available...
```
$ lscpu --parse=CPU,Core,Socket,Node
# The following is the parsable format, which can be fed to other
# programs. Each different item in every column has an unique ID
# starting from zero.
# CPU,Core,Socket,Node
0,0,0,
1,0,0,
2,1,0,
3,1,0,
4,2,0,
5,2,0,
6,3,0,
7,3,0,
```

Expected output:
```
$ lscpu --parse=CPU,Core,Socket,Node
# The following is the parsable format, which can be fed to other
# programs. Each different item in every column has an unique ID
# starting from zero.
# CPU,Core,Socket,Node
0,0,0,0
1,0,0,0
2,1,0,0
3,1,0,0
4,2,0,0
5,2,0,0
6,3,0,0
7,3,0,0
```
