### ISSUE TITLE
detectron2: symbolically traced variables cannot be used as inputs to control flow

### ISSUE THREAD

**Issue by mbergal** [intel/intel-extension-for-pytorch#238]
I am using version 1.9.0
```
Traceback (most recent call last):
  File "./timing.py", line 106, in <module>
    ipex.optimize(model.backbone)        
  File "/data/home/ubuntu/projects/ai-general/ml/.venv/lib/python3.8/site-packages/intel_extension_for_pytorch/frontend.py", line 238, in optimize
    optimized_model = optimization.fuse(optimized_model, inplace=inplace)
  File "/data/home/ubuntu/projects/ai-general/ml/.venv/lib/python3.8/site-packages/torch/fx/experimental/optimization.py", line 60, in fuse
    fx_model = fx.symbolic_trace(model)
  File "/data/home/ubuntu/projects/ai-general/ml/.venv/lib/python3.8/site-packages/torch/fx/_symbolic_trace.py", line 907, in symbolic_trace
    graph = tracer.trace(root, concrete_args)
  File "/data/home/ubuntu/projects/ai-general/ml/.venv/lib/python3.8/site-packages/torch/fx/_symbolic_trace.py", line 615, in trace
    self.create_node('output', 'output', (self.create_arg(fn(*args)),), {},
  File "/data/home/ubuntu/projects/ai-general/ml/.venv/lib/python3.8/site-packages/detectron2/modeling/backbone/fpn.py", line 126, in forward
    bottom_up_features = self.bottom_up(x)
  File "/data/home/ubuntu/projects/ai-general/ml/.venv/lib/python3.8/site-packages/torch/fx/_symbolic_trace.py", line 604, in module_call_wrapper
    return self.call_module(mod, forward, args, kwargs)
  File "/data/home/ubuntu/projects/ai-general/ml/.venv/lib/python3.8/site-packages/torch/fx/_symbolic_trace.py", line 422, in call_module
    return forward(*args, **kwargs)
  File "/data/home/ubuntu/projects/ai-general/ml/.venv/lib/python3.8/site-packages/torch/fx/_symbolic_trace.py", line 600, in forward
    return _orig_module_call(mod, *args, **kwargs)
  File "/data/home/ubuntu/projects/ai-general/ml/.venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/home/ubuntu/projects/ai-general/ml/.venv/lib/python3.8/site-packages/detectron2/modeling/backbone/resnet.py", line 443, in forward
    assert x.dim() == 4, f"ResNet takes an input of shape (N, C, H, W). Got {x.shape} instead!"
  File "/data/home/ubuntu/projects/ai-general/ml/.venv/lib/python3.8/site-packages/torch/fx/proxy.py", line 251, in __bool__
    return self.tracer.to_bool(self)
  File "/data/home/ubuntu/projects/ai-general/ml/.venv/lib/python3.8/site-packages/torch/fx/proxy.py", line 152, in to_bool
    raise TraceError('symbolically traced variables cannot be used as inputs to control flow')
torch.fx.proxy.TraceError: symbolically traced variables cannot be used as inputs to control flow
```

**Comment by jingxu10** [comment]
Hi, We have just release 1.12.100 today. There are many changes since 1.9. Would you please try the latest version? Thank you.
