### ISSUE TITLE
Max pool issue on 1.13.0+cpu

### ISSUE THREAD

**Issue by xsacha** [intel/intel-extension-for-pytorch#261]
By linking the intel-extension-pt.so to my application and freezing models at runtime, I get this error on some models:

> Traceback of TorchScript (most recent call last):
> 
>       graph(%a, %kernel_size:int[], %stride:int[], %padding:int[], %dilation:int[], %ceil_mode:bool):
>         %res = ipex::max_pool2d(%a, %kernel_size, %stride, %padding, %dilation, %ceil_mode)
>                ~~~~ <--- HERE
>         return (%res) 
> RuntimeError: itensor_view_from_dense expects dense tensor input

I wonder is it possible to disable ipex just for that model but leave it enabled for the rest? I never actually ask for ipex to be used for any of the models.

**Comment by ZailiWang** [comment]
Hi @xsacha would you please provide the model in which the error occurs? In addition re-producing codes would be more helpful, thanks. And is the model run on CPU or Intel GPU?
Normally ipex is used to optimize PyTorch models in a respective manner (you call ipex.optimize( ) for each of the models), so basically answer to you 2nd question is YES.

**Comment by xsacha** [comment]
C++ usage. Is there an equivalent ipex.optimize() in C++? I have just been relying on freeze and optimize_for_inference, which appears to utilise ipex anyway.

Is the torchscript enough?
Optimised: https://pastebin.com/hPs4cVYc

**Comment by jingxu10** [comment]
for C++ usage, once libipex.so is linked, it will apply optimizations automatically to all operators. Currently there are no filters to choose which operator should be optimized, which not.
Does this error occur in python interface as well?

**Comment by xsacha** [comment]
@jingxu10 Yes, the same issue happens in Python with that model. On the second run.

```
>>> import torch
>>> import intel_extension_for_pytorch as ipex
>>> x=torch.jit.load('face_model_68.dat')
>>> x=torch.jit.freeze(x)
>>> x=torch.jit.optimize_for_inference(x)
>>> inp=torch.randn(1,3,112,112)
>>> x(inp)
tensor([[-1.0128e-01,  3.8481e-01,  5.5185e-01,  6.1985e-01, -3.1513e-01, ...
>>> x(inp)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/deep/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):

      graph(%a, %kernel_size:int[], %stride:int[], %padding:int[], %dilation:int[], %ceil_mode:bool):
        %res = ipex::max_pool2d(%a, %kernel_size, %stride, %padding, %dilation, %ceil_mode)
               ~~~~ <--- HERE
        return (%res) 
RuntimeError: itensor_view_from_dense expects dense tensor input
```

**Comment by jingxu10** [comment]
As indicated in the error message, would you check if the input data is a dense tensor or a sparse tensor?

**Comment by xsacha** [comment]
There's no sparse tensors.
However, the optimize function will inject .to(mkldnn) as seen in the optimised torchscript.
Is IPEX incompatible with torch.jit.optimize_for_inference ?

**Comment by jingxu10** [comment]
Thanks for sharing the workaround.
IPEX should be compatible to optimize_for_inference, but we haven't verified this kind of usage. Since both of them work on the same target, it is not necessary to use them both. We would recommend to just use IPEX in this scenario.

**Comment by xsacha** [comment]
OK. In every model I've tested I appear to get better performance from optimize_for_inference instead of using IPEX though.
So I'll probably just use this workaround for now so I can do both.

**Comment by jingxu10** [comment]
Workaround: torch._C._jit_set_profiling_mode(False) This issue should already have been fixed in IPEX 1.13. Would you help to have a try?

**Comment by xsacha** [comment]
Yes, I tested this with IPEX 1.13. This is the version I am currently using.
I did go back and test 1.12 and 1.11 as well and can confirm the issue existed there as well.

**Comment by xsacha** [comment]
Update: This issue doesn't occur on IPEX 1.10
Reproducer:

```Python
import torch
import torch.nn as nn
import intel_extension_for_pytorch as ipex

class Backbone(nn.Module):
    def __init__(self):
        super(Backbone, self).__init__()
        self.input_layer = nn.Sequential(nn.Conv2d(3, 64, (3, 3), 1, 1, bias=False),
                                      nn.BatchNorm2d(64),
                                      nn.PReLU(64))
        self.residual_block1 = nn.MaxPool2d(1, 2)

    def forward(self, x):
        out = self.input_layer(x)
        out = self.residual_block1(out)
        return out

if __name__ == '__main__':
    x = Backbone()
    inp = torch.randn(64,3,112,112)
    traced = torch.jit.trace(x, inp)
    opt = torch.jit.optimize_for_inference(traced)
    # Run twice
    out = opt(inp)
    out = opt(inp)
```
