### ISSUE TITLE
Internal asset running model on Intel Arc GPU (1.10+gpu)

### ISSUE THREAD

**Issue by xsacha** [intel/intel-extension-for-pytorch#262]
```Python
import torch
import time
import intel_extension_for_pytorch as ipex
x=torch.jit.load('/usr/local/share/Imagus/face_model_137.dat', map_location='cpu')
inp=torch.randn(64,3,112,112)
x = x.to('xpu')
inp = inp.to('xpu')
with torch.no_grad():
  x(inp)
```

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
RuntimeError: isTuple()INTERNAL ASSERT FAILED at "/home/guizili/zhongruijie/frameworks.ai.pytorch.private-gpu/aten/src/ATen/core/ivalue_inl.h":1400, please report a bug to PyTorch. Expected Tuple but got String

**Comment by jingxu10** [comment]
Could you share a reproducer to us for investigation?

**Comment by xsacha** [comment]
The model in Python doesn't trace in torch 1.10.
I can provide the pre-traced model.
It will take me a while to find a minimal sample to reproduce the problem, especially as I encounter other bugs along the way.

**Comment by xsacha** [comment]
@kta-intel issue is persistent. No small reproducer but the model I provided reproduces it.
Awaiting the 1.13 release

**Comment by kta-intel** [comment]
Oh I see, the links you provided in #261 for your model are no longer available. Would you also be able to provide some information on how you generated the problematic model, as well, since you mention that some of your other models don't seem to run into this issue?

**Comment by xsacha** [comment]
The model uses a feature that was broken in MKLDNN before 1.12 so I can't trace it from 1.10. I'm not sure if that also causes an issue in XPU but I was waiting for the 1.13 release to see if that just fixes it.

**Comment by kta-intel** [comment]
@xsacha Hi, just wanted to update you that we recently released ipex 1.13.10+xpu

https://intel.github.io/intel-extension-for-pytorch/xpu/1.13.10+xpu/tutorials/installation.html

**Comment by xsacha** [comment]
Thanks :) I saw that and am testing it out already.

**Comment by kta-intel** [comment]
Unfortunately, there are no C++ only binary releases yet, but you may find this helpful:
https://intel.github.io/intel-extension-for-pytorch/xpu/latest/tutorials/features/DPC++_Extension.html

**Comment by jingxu10** [comment]
It's the same thing. Please extract them from the wheel at this moment.
We also have released the patched version of pytorch, you can just use that as well.
