### ISSUE TITLE
Errors when using torch.nn.DataParallel

### ISSUE THREAD

**Issue by yohnk** [intel/intel-extension-for-pytorch#271]
I'm using v1.10.200+gpu with two Arc A770s. I'm hoping to utilize them both during model training.

I attempted to use torch.nn.DataParallel but get the following error when calling my model.

> Traceback (most recent call last):
  File "/home/ryanyohnk/dev/intel-data-parallel/main.py", line 34, in <module>
    main()
  File "/home/ryanyohnk/dev/intel-data-parallel/main.py", line 23, in main
    output = model(x)
  File "/home/ryanyohnk/.conda/envs/intel_data_parallel/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ryanyohnk/.conda/envs/intel_data_parallel/lib/python3.9/site-packages/torch/nn/parallel/data_parallel.py", line 158, in forward
    inputs, kwargs = self.scatter(inputs, kwargs, self.device_ids)
  File "/home/ryanyohnk/.conda/envs/intel_data_parallel/lib/python3.9/site-packages/torch/nn/parallel/data_parallel.py", line 175, in scatter
    return scatter_kwargs(inputs, kwargs, device_ids, dim=self.dim)
  File "/home/ryanyohnk/.conda/envs/intel_data_parallel/lib/python3.9/site-packages/torch/nn/parallel/scatter_gather.py", line 44, in scatter_kwargs
    inputs = scatter(inputs, target_gpus, dim) if inputs else []
  File "/home/ryanyohnk/.conda/envs/intel_data_parallel/lib/python3.9/site-packages/torch/nn/parallel/scatter_gather.py", line 36, in scatter
    res = scatter_map(inputs)
  File "/home/ryanyohnk/.conda/envs/intel_data_parallel/lib/python3.9/site-packages/torch/nn/parallel/scatter_gather.py", line 23, in scatter_map
    return list(zip(*map(scatter_map, obj)))
  File "/home/ryanyohnk/.conda/envs/intel_data_parallel/lib/python3.9/site-packages/torch/nn/parallel/scatter_gather.py", line 19, in scatter_map
    return Scatter.apply(target_gpus, None, dim, obj)
  File "/home/ryanyohnk/.conda/envs/intel_data_parallel/lib/python3.9/site-packages/torch/nn/parallel/_functions.py", line 99, in forward
    outputs = comm.scatter(input, target_gpus, chunk_sizes, ctx.dim, streams)
  File "/home/ryanyohnk/.conda/envs/intel_data_parallel/lib/python3.9/site-packages/torch/nn/parallel/comm.py", line 189, in scatter
    return tuple(torch._C._scatter(tensor, devices, chunk_sizes, dim, streams))
AttributeError: module 'torch._C' has no attribute '_scatter'

I also attempted to use the data_parallel method example from PyTorch's "[Multi-GPU Examples](https://pytorch.org/tutorials/beginner/former_torchies/parallelism_tutorial.html)". I get a similar error, but this one states...

> (...) AttributeError: module 'torch._C' has no attribute '_broadcast_coalesced'

An simple example script along with my environment (conda & env variables) and logs can be found [here](https://github.com/yohnk/intel-data-parallel).

**Comment by jingxu10** [comment]
Hi, DP is not supported in IPEX. It will also be deprecated in PyTorch as well.

**Comment by yohnk-edu** [comment]
Thanks @jingxu10 - Is there a suggested alternative?

**Comment by yohnk** [comment]
Thanks @jingxu10 - Is there a suggested alternative to accomplish multi-gpu training?

**Comment by edward-io** [comment]
@yohnk Distributed Data Parallel (DDP) is currently the standard for multi-GPU training.

**Comment by yohnk-edu** [comment]
Thanks @edward-io!

I'll give [this tutorial](https://pytorch.org/tutorials/intermediate/ddp_tutorial.html) a try, see how that goes. For now I'll close the ticket.

**Comment by yohnk** [comment]
Thanks @edward-io!

I'll give [this tutorial](https://pytorch.org/tutorials/intermediate/ddp_tutorial.html) a try, see how that goes. For now I'll close the ticket.

**Comment by deepakmeena635** [comment]
@yohnk how did it go?
