### ISSUE TITLE
Bus error (core dumped) calling `ipex.optimize` on Arc A770

### ISSUE THREAD

**Issue by edward-io** [intel/intel-extension-for-pytorch#274]
The test example code given fails when attempting to call `ipex.optimize`. The code works when commenting out this line:

```
import torch
import torchvision.models as models
import intel_extension_for_pytorch as ipex

model = models.resnet50(pretrained=True)
model.eval()
data = torch.rand(1, 3, 224, 224)

model = model.to('xpu')
data = data.to('xpu')
# model = ipex.optimize(model)

out = model(data)
print(out.shape)
```

Environment:

- Ubuntu 22.04
- ipex.__version__ == '1.10.200+gpu'
-  torch.__version__ == '1.10.0a0+git3d5f2d4'

```
➜  ~ sycl-ls
[opencl:acc:0] Intel(R) FPGA Emulation Platform for OpenCL(TM), Intel(R) FPGA Emulation Device 1.2 [2022.14.10.0.20_160000.xmain-hotfix]
[opencl:cpu:1] Intel(R) OpenCL, AMD EPYC 7443P 24-Core Processor                3.0 [2022.14.10.0.20_160000.xmain-hotfix]
[opencl:gpu:2] Intel(R) OpenCL HD Graphics, Intel(R) Graphics [0x56a0] 3.0 [22.32.23937]
[ext_oneapi_level_zero:gpu:0] Intel(R) Level-Zero, Intel(R) Graphics [0x56a0] 1.3 [1.3.23937]
[host:host:0] SYCL host platform, SYCL host device 1.2 [1.2]

**Comment by ZailiWang** [comment]
Hi, We will look into the issue.

**Comment by edward-io** [comment]
@ZailiWang Thanks! I'm encountering this issue with the intel extension for tensorflow as well. Possibly driver issue?

**Comment by jingxu10** [comment]
Probably it is a driver issue.
https://intel.github.io/intel-extension-for-pytorch/xpu/latest/tutorials/installation.html
The [419.40 driver](https://dgpu-docs.intel.com/releases/stable_419_40_20220914.html) we verified doesn't support Ubuntu 22.04.
We will release the next version soon. The new version supports Ubuntu 22.04. Would you have a try later on with this new version?

**Comment by diegomontoya** [comment]
@jingxu10 is there a alpha or beta 22.04 driver we can test in the mean time？

**Comment by jingxu10** [comment]
Would you check https://dgpu-docs.intel.com/releases/index.html? We didn't verified on other driver versions.

**Comment by edward-io** [comment]
@jingxu10 Unfortunately I've returned the GPU because ipex wasn't working. Hope others can test it out.

**Comment by jingxu10** [comment]
Oh, sorry to hear that. We hope to have opportunity to serve you better in the future.

**Comment by Gentoli** [comment]
I think this the same issue that causes a system reset (no BSOD/logs) when I am running the some workload under WSL2. I did tried lowing the bus to PCIe Gen3 but it's the same result.

Switching to linux I got a Bus error instead of a crash.

Let me know if I can help collect any additional logs.

Versions:
```
torch==1.13.0a0
torchvision==0.14.1a0
intel_extension_for_pytorch==1.13.10+xpu

[opencl:acc:0] Intel(R) FPGA Emulation Platform for OpenCL(TM), Intel(R) FPGA Emulation Device 1.2 [2022.15.12.0.01_081451]
[opencl:cpu:1] Intel(R) OpenCL, AMD Ryzen 9 3950X 16-Core Processor             3.0 [2022.15.12.0.01_081451]
[opencl:cpu:2] Intel(R) OpenCL, AMD Ryzen 9 3950X 16-Core Processor             3.0 [2022.15.12.0.01_081451]
[opencl:acc:3] Intel(R) FPGA Emulation Platform for OpenCL(TM), Intel(R) FPGA Emulation Device 1.2 [2022.15.12.0.01_081451]
[opencl:gpu:4] Intel(R) OpenCL HD Graphics, Intel(R) Graphics [0x56a0] 3.0 [22.49.25018.23]
[ext_oneapi_level_zero:gpu:0] Intel(R) Level-Zero, Intel(R) Graphics [0x56a0] 1.3 [1.3.25018]
```


The backtrace looks similar to the original post:
```
Thread 83 "python" received signal SIGBUS, Bus error.
[Switching to LWP 30076]
0x00007ffe785725a0 in ?? () from /lib/x86_64-linux-gnu/libze_intel_gpu.so.1
(gdb) bt
#0  0x00007ffe785725a0 in ?? () from /lib/x86_64-linux-gnu/libze_intel_gpu.so.1
#1  0x00007ffe78558f82 in ?? () from /lib/x86_64-linux-gnu/libze_intel_gpu.so.1
#2  0x00007ffe783af543 in ?? () from /lib/x86_64-linux-gnu/libze_intel_gpu.so.1
#3  0x00007ffe783b081c in ?? () from /lib/x86_64-linux-gnu/libze_intel_gpu.so.1
#4  0x00007ffe783cd6ac in ?? () from /lib/x86_64-linux-gnu/libze_intel_gpu.so.1
#5  0x00007ffe783d8800 in ?? () from /lib/x86_64-linux-gnu/libze_intel_gpu.so.1
#6  0x00007ffe783cecff in ?? () from /lib/x86_64-linux-gnu/libze_intel_gpu.so.1
#7  0x00007ffe8a1b9e02 in _pi_queue::createCommandList(bool, std::__1::__hash_map_iterator<std::__1::__hash_iterator<std::__1::__hash_node<std::__1::__hash_value_type<_ze_command_list_handle_t*, pi_command_list_info_t>, void*>*> >&, _ze_command_queue_handle_t**) ()
   from /opt/intel/oneapi/compiler/2023.0.0/linux/lib/libpi_level_zero.so
#8  0x00007ffe8a1b8e03 in _pi_context::getAvailableCommandList(_pi_queue*, std::__1::__hash_map_iterator<std::__1::__hash_iterator<std::__1::__hash_node<std::__1::__hash_value_type<_ze_command_list_handle_t*, pi_command_list_info_t>, void*>*> >&, bool, bool, _ze_command_queue_handle_t**) ()
   from /opt/intel/oneapi/compiler/2023.0.0/linux/lib/libpi_level_zero.so
#9  0x00007ffe8a1ceabc in piEnqueueKernelLaunch () from /opt/intel/oneapi/compiler/2023.0.0/linux/lib/libpi_level_zero.so
#10 0x00007ffee7a51906 in _pi_result sycl::_V1::detail::plugin::call_nocheck<(sycl::_V1::detail::PiApiKind)75, _pi_queue*, _pi_kernel*, unsigned long, unsigned long*, unsigned long*, unsigned long*, unsigned long, _pi_event**, _pi_event**>(_pi_queue*, _pi_kernel*, unsigned long, unsigned long*, unsigned long*, unsigned long*, unsigned long, _pi_event**, _pi_event**) const () from /opt/intel/oneapi/compiler/2023.0.0/linux/lib/libsycl.so.6
#11 0x00007ffee7a4c354 in sycl::_V1::detail::SetKernelParamsAndLaunch(std::shared_ptr<sycl::_V1::detail::queue_impl> const&, std::vector<sycl::_V1::detail::ArgDesc, std::allocator<sycl::_V1::detail::ArgDesc> >&, std::shared_ptr<sycl::_V1::detail::device_image_impl> const&, _pi_kernel*, sycl::_V1::detail::NDRDescT&, std::vector<_pi_event*, std::allocator<_pi_event*> >&, _pi_event**, std::vector<bool, std::allocator<bool> > const&, std::function<void* (sycl::_V1::detail::AccessorImplHost*)> const&) () from /opt/intel/oneapi/compiler/2023.0.0/linux/lib/libsycl.so.6
#12 0x00007ffee7a4b64a in sycl::_V1::detail::enqueueImpKernel(std::shared_ptr<sycl::_V1::detail::queue_impl> const&, sycl::_V1::detail::NDRDescT&, std::vector<sycl::_V1::detail::ArgDesc, std::allocator<sycl::_V1::detail::ArgDesc> >&, std::shared_ptr<sycl::_V1::detail::kernel_bundle_impl> const&, std::shared_ptr<sycl::_V1::detail::kernel_impl> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, long const&, std::vector<_pi_event*, std::allocator<_pi_event*> >&, _pi_event**, std::function<void* (sycl::_V1::detail::AccessorImplHost*)> const&) ()
   from /opt/intel/oneapi/compiler/2023.0.0/linux/lib/libsycl.so.6
#13 0x00007ffee7a976d1 in sycl::_V1::handler::finalize()::$_0::operator()() const () from /opt/intel/oneapi/compiler/2023.0.0/linux/lib/libsycl.so.6
#14 0x00007ffee7a93ef9 in sycl::_V1::handler::finalize() () from /opt/intel/oneapi/compiler/2023.0.0/linux/lib/libsycl.so.6
#15 0x00007ffee7abf9f9 in void sycl::_V1::detail::queue_impl::finalizeHandler<sycl::_V1::handler>(sycl::_V1::handler&, sycl::_V1::detail::CG::CGTYPE const&, sycl::_V1::event&) () from /opt/intel/oneapi/compiler/2023.0.0/linux/lib/libsycl.so.6
#16 0x00007ffee7abf4f1 in sycl::_V1::detail::queue_impl::submit_impl(std::function<void (sycl::_V1::handler&)> const&, std::shared_ptr<sycl::_V1::detail::queue_impl> const&, std::shared_ptr<sycl::_V1::detail::queue_impl> const&, std::shared_ptr<sycl::_V1::detail::queue_impl> const&, sycl::_V1::detail::code_location const&, std::function<void (bool, bool, sycl::_V1::event&)> const*) () from /opt/intel/oneapi/compiler/2023.0.0/linux/lib/libsycl.so.6
#17 0x00007ffee7abe945 in sycl::_V1::detail::queue_impl::submit(std::function<void (sycl::_V1::handler&)> const&, std::shared_ptr<sycl::_V1::detail::queue_impl> const&, sycl::_V1::detail::code_location const&, std::function<void (bool, bool, sycl::_V1::event&)> const*) ()
   from /opt/intel/oneapi/compiler/2023.0.0/linux/lib/libsycl.so.6
#18 0x00007ffee7abe905 in sycl::_V1::queue::submit_impl(std::function<void (sycl::_V1::handler&)>, sycl::_V1::detail::code_location const&) () from /opt/intel/oneapi/compiler/2023.0.0/linux/lib/libsycl.so.6
..
```
