### ISSUE TITLE
[Need advice] training bottlenecked (by aten::copy calls (?))

### ISSUE THREAD

**Issue by robogast** [intel/intel-extension-for-pytorch#276]
Hi! I'm not entirely sure this is totally related to IPEX, but I'm trying to optimize my code, but I see in the trace I made that (almost) every call is preceded with aten::copy:
![image](https://user-images.githubusercontent.com/5969044/208255053-7b4e8a96-70e0-4ef3-bb1f-475bd922ecc9.png)

Which takes 22.4% of total execution time (!)
![image](https://user-images.githubusercontent.com/5969044/208255112-942ab4b0-b037-4e65-bbfd-8d7322675884.png)

I'm already:
- using `libtcmalloc`
- casting my model + input data to channels last
- using iomp with mpirun (which afaik binds the processes to local mem)

More context:
I'm benchmarking SPR AMX when compared to ICX AVX512VNNI:
- on the ICX node I'm getting ~3 sec/it for 2 instances and ~5.5 sec/it for 4 instances. (fp32)
- on the SPR node I'm getting ~2 sec/it for 2 instances and ~3.5 sec/it for 4 instances. (bf16)
Although this is ofcourse a nice speedup, but from AMX specs I should be getting a lot more: [1024 bfloat16 operations per cycle (vs. 64 without AMX). ](https://edc.intel.com/content/www/us/en/products/performance/benchmarks/architecture-day-2021/)

Any clue as to why I'm not seeing anything close to that number?

Example command with which I'm running (omitted everything irrelevant):
```bash
export I_MPI_SHM=spr
export I_MPI_FABRICS=shm
export LD_PRELOAD=~/2D-VQ-AE-2/libtcmalloc.so:~/2D-VQ-AE-2/.venv/py310-AMX/lib/libiomp5.so:$LD_PRELOAD
export KMP_BLOCKTIME=1 
export KMP_AFFINITY=granularity=fine,compact,1,0 

SLURM_TASKS_PER_NODE=2 OMP_NUM_THREADS=55 mpirun python train.py trainer=ddp_trainer_intel_cpu model/optim@model.optim_conf=adam trainer.precision=bf16 train_datamodule.train_dataloader_conf.num_workers=3 trainer.devices=2
```

**Comment by robogast** [comment]
Ah a clue: a lot of parameters of my model are still fp32!

``` python
>>> [param.dtype for param in model.parameters()]
[torch.bfloat16, torch.bfloat16, torch.float32, torch.float32, torch.float32, torch.float32, torch.float32, torch.float32, torch.float32, torch.float32, torch.bfloat16, torch.bfloat16, torch.bfloat16, tor
ch.float32, torch.float32, torch.float32, torch.float32, torch.float32, torch.float32, torch.float32, torch.float32, torch.float32, torch.float32, torch.bfloat16, torch.bfloat16, torch.bfloat16, torch.bfl
oat16, torch.float32, torch.float32, torch.float32, torch.float32, torch.float32, torch.float32, torch.float32, torch.float32, torch.bfloat16, torch.bfloat16, torch.bfloat16, torch.float32, torch.float32,
 torch.float32, torch.float32, torch.float32, torch.float32, torch.float32, torch.float32, torch.bfloat16, torch.bfloat16, torch.bfloat16, torch.float32, torch.float32, torch.float32, torch.float32, torch
.float32, torch.float32, torch.float32, torch.float32, ...
```
But if I cast my whole model to `bf16` before calling `ipex.optimize`, I get an error with `torch.ops.torch_ipex.split_float_bfloat16`:
```python
Traceback (most recent call last):                                                                                                                                                                          
  File "/global/panfs01/users/Xrjschl/2D-VQ-AE-2/vq_ae/train.py", line 38, in main                                                                                                                          
    trainer.fit(model, train_datamodule.train_dataloader(), train_datamodule.val_dataloader())                                                                                                              
  File "/global/panfs01/users/Xrjschl/2D-VQ-AE-2/.venv/py310-AMX/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 603, in fit                                                       
    call._call_and_handle_interrupt(
  File "/global/panfs01/users/Xrjschl/2D-VQ-AE-2/.venv/py310-AMX/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt                                   
    return trainer_fn(*args, **kwargs)
  File "/global/panfs01/users/Xrjschl/2D-VQ-AE-2/.venv/py310-AMX/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 645, in _fit_impl                                                
    self._run(model, ckpt_path=self.ckpt_path)
  File "/global/panfs01/users/Xrjschl/2D-VQ-AE-2/.venv/py310-AMX/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1037, in _run                                                    
    self._call_setup_hook()  # allow user to setup lightning_module in accelerator environment
  File "/global/panfs01/users/Xrjschl/2D-VQ-AE-2/.venv/py310-AMX/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1285, in _call_setup_hook                                        
    self._call_callback_hooks("setup", stage=fn)
  File "/global/panfs01/users/Xrjschl/2D-VQ-AE-2/.venv/py310-AMX/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1380, in _call_callback_hooks                                    
    fn(self, self.lightning_module, *args, **kwargs)
  File "/global/panfs01/users/Xrjschl/2D-VQ-AE-2/utils/train_helpers.py", line 177, in setup
    self.optimize(model=pl_module, optimizer=optimizers, inplace=True, dtype=dtype)
  File "/global/panfs01/users/Xrjschl/2D-VQ-AE-2/.venv/py310-AMX/lib/python3.10/site-packages/intel_extension_for_pytorch/frontend.py", line 429, in optimize                                              
    optimized_model, optimized_optimizer, params_attr = utils._weight_cast.weight_dtype_convert_with_ipex(                                                                                                 
  File "/global/panfs01/users/Xrjschl/2D-VQ-AE-2/.venv/py310-AMX/lib/python3.10/site-packages/intel_extension_for_pytorch/nn/utils/_weight_cast.py", line 88, in weight_dtype_convert_with_ipex            
    casted_model, casted_optimizer, params_attr = convert_rec(module), optimizer, params_attr
  File "/global/panfs01/users/Xrjschl/2D-VQ-AE-2/.venv/py310-AMX/lib/python3.10/site-packages/intel_extension_for_pytorch/nn/utils/_weight_cast.py", line 85, in convert_rec                               
    setattr(new_m, name, convert_rec(sub_m))
  File "/global/panfs01/users/Xrjschl/2D-VQ-AE-2/.venv/py310-AMX/lib/python3.10/site-packages/intel_extension_for_pytorch/nn/utils/_weight_cast.py", line 85, in convert_rec                               
    setattr(new_m, name, convert_rec(sub_m))
  File "/global/panfs01/users/Xrjschl/2D-VQ-AE-2/.venv/py310-AMX/lib/python3.10/site-packages/intel_extension_for_pytorch/nn/utils/_weight_cast.py", line 83, in convert_rec                               
    new_m = convert(m)
  File "/global/panfs01/users/Xrjschl/2D-VQ-AE-2/.venv/py310-AMX/lib/python3.10/site-packages/intel_extension_for_pytorch/nn/utils/_weight_cast.py", line 76, in convert                                   
    cast_attr(m, name, master_weight_split, params_attr, optimizer)
  File "/global/panfs01/users/Xrjschl/2D-VQ-AE-2/.venv/py310-AMX/lib/python3.10/site-packages/intel_extension_for_pytorch/nn/utils/_weight_cast.py", line 52, in cast_attr                                 
    top_half, bot_half = torch.ops.torch_ipex.split_float_bfloat16(float_param.data)
  File "/global/panfs01/users/Xrjschl/2D-VQ-AE-2/.venv/py310-AMX/lib/python3.10/site-packages/torch/_ops.py", line 442, in __call__                                                                        
    return self._op(*args, **kwargs or {})
RuntimeError: pack_bfloat16_float: expect both tensor to be at::kFloat
```

If I only cast all my singleton Parameters to bfloat16 instead I get an error with fused Adam:

```python
...
  File "/global/panfs01/users/Xrjschl/2D-VQ-AE-2/.venv/py310-AMX/lib/python3.10/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 357, in _optimizer_step                        
    self.trainer._call_lightning_module_hook(
  File "/global/panfs01/users/Xrjschl/2D-VQ-AE-2/.venv/py310-AMX/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1342, in _call_lightning_module_hook                             
    output = fn(*args, **kwargs)
  File "/global/panfs01/users/Xrjschl/2D-VQ-AE-2/.venv/py310-AMX/lib/python3.10/site-packages/pytorch_lightning/core/module.py", line 1661, in optimizer_step                                              
    optimizer.step(closure=optimizer_closure)
  File "/global/panfs01/users/Xrjschl/2D-VQ-AE-2/.venv/py310-AMX/lib/python3.10/site-packages/pytorch_lightning/core/optimizer.py", line 169, in step                                                      
    step_output = self._strategy.optimizer_step(self._optimizer, self._optimizer_idx, closure, **kwargs)                                                                                                   
  File "/global/panfs01/users/Xrjschl/2D-VQ-AE-2/.venv/py310-AMX/lib/python3.10/site-packages/pytorch_lightning/strategies/ddp.py", line 281, in optimizer_step                                            
    optimizer_output = super().optimizer_step(optimizer, opt_idx, closure, model, **kwargs)
  File "/global/panfs01/users/Xrjschl/2D-VQ-AE-2/.venv/py310-AMX/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 234, in optimizer_step                                       
    return self.precision_plugin.optimizer_step(
  File "/global/panfs01/users/Xrjschl/2D-VQ-AE-2/.venv/py310-AMX/lib/python3.10/site-packages/pytorch_lightning/plugins/precision/native_amp.py", line 78, in optimizer_step                               
    return super().optimizer_step(
  File "/global/panfs01/users/Xrjschl/2D-VQ-AE-2/.venv/py310-AMX/lib/python3.10/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 121, in optimizer_step                        
    return optimizer.step(closure=closure, **kwargs)
  File "/global/panfs01/users/Xrjschl/2D-VQ-AE-2/.venv/py310-AMX/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context                                                   
    return func(*args, **kwargs)
  File "/global/panfs01/users/Xrjschl/2D-VQ-AE-2/.venv/py310-AMX/lib/python3.10/site-packages/intel_extension_for_pytorch/optim/_functional.py", line 643, in adam_step                                    
    adam(params_with_grad,
  File "/global/panfs01/users/Xrjschl/2D-VQ-AE-2/.venv/py310-AMX/lib/python3.10/site-packages/intel_extension_for_pytorch/optim/_functional.py", line 699, in adam                                         
    func(params,
  File "/global/panfs01/users/Xrjschl/2D-VQ-AE-2/.venv/py310-AMX/lib/python3.10/site-packages/intel_extension_for_pytorch/optim/_functional.py", line 746, in _single_tensor_adam                          
    torch.ops.torch_ipex.adam_fused_step(
  File "/global/panfs01/users/Xrjschl/2D-VQ-AE-2/.venv/py310-AMX/lib/python3.10/site-packages/torch/_ops.py", line 442, in __call__                                                                        
    return self._op(*args, **kwargs or {})
RuntimeError: adam_fused_step_kernel: expect param2 to be at::BFloat16
```
And if if turn of `fuse_update_step` I get a very unexpected error:
```python
...
  File "/global/panfs01/users/Xrjschl/2D-VQ-AE-2/.venv/py310-AMX/lib/python3.10/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 88, in advance                                    
    outputs = self.optimizer_loop.run(optimizers, kwargs)                                                                                                                                                   
  File "/global/panfs01/users/Xrjschl/2D-VQ-AE-2/.venv/py310-AMX/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 199, in run                                                            
    self.advance(*args, **kwargs)
  File "/global/panfs01/users/Xrjschl/2D-VQ-AE-2/.venv/py310-AMX/lib/python3.10/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 200, in advance                                
    result = self._run_optimization(kwargs, self._optimizers[self.optim_progress.optimizer_position])
  File "/global/panfs01/users/Xrjschl/2D-VQ-AE-2/.venv/py310-AMX/lib/python3.10/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 247, in _run_optimization                      
    self._optimizer_step(optimizer, opt_idx, kwargs.get("batch_idx", 0), closure)
  File "/global/panfs01/users/Xrjschl/2D-VQ-AE-2/.venv/py310-AMX/lib/python3.10/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 357, in _optimizer_step                        
    self.trainer._call_lightning_module_hook(
  File "/global/panfs01/users/Xrjschl/2D-VQ-AE-2/.venv/py310-AMX/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1342, in _call_lightning_module_hook                             
    output = fn(*args, **kwargs)
  File "/global/panfs01/users/Xrjschl/2D-VQ-AE-2/.venv/py310-AMX/lib/python3.10/site-packages/pytorch_lightning/core/module.py", line 1661, in optimizer_step                                              
    optimizer.step(closure=optimizer_closure)
  File "/global/panfs01/users/Xrjschl/2D-VQ-AE-2/.venv/py310-AMX/lib/python3.10/site-packages/pytorch_lightning/core/optimizer.py", line 169, in step                                                      
    step_output = self._strategy.optimizer_step(self._optimizer, self._optimizer_idx, closure, **kwargs)                                                                                                   
  File "/global/panfs01/users/Xrjschl/2D-VQ-AE-2/.venv/py310-AMX/lib/python3.10/site-packages/pytorch_lightning/strategies/ddp.py", line 281, in optimizer_step                                            
    optimizer_output = super().optimizer_step(optimizer, opt_idx, closure, model, **kwargs)
  File "/global/panfs01/users/Xrjschl/2D-VQ-AE-2/.venv/py310-AMX/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 234, in optimizer_step                                       
    return self.precision_plugin.optimizer_step(
  File "/global/panfs01/users/Xrjschl/2D-VQ-AE-2/.venv/py310-AMX/lib/python3.10/site-packages/pytorch_lightning/plugins/precision/native_amp.py", line 78, in optimizer_step                               
    return super().optimizer_step(
  File "/global/panfs01/users/Xrjschl/2D-VQ-AE-2/.venv/py310-AMX/lib/python3.10/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 121, in optimizer_step                        
    return optimizer.step(closure=closure, **kwargs)
  File "/global/panfs01/users/Xrjschl/2D-VQ-AE-2/.venv/py310-AMX/lib/python3.10/site-packages/intel_extension_for_pytorch/optim/_optimizer_utils.py", line 60, in master_param_non_fused_step              
    k.grad = value['bf16_param'].grad.detach().float()
AttributeError: 'NoneType' object has no attribute 'detach'
```

**Comment by jingxu10** [comment]
Hi, did you follow the example at https://intel.github.io/intel-extension-for-pytorch/cpu/latest/tutorials/examples.html#complete-bfloat16?

**Comment by robogast** [comment]
Yes, I verified that that example worked with ipex + ddp + ccl + bf16 before porting my own model, and my own model trains normallly with that setup.

**Comment by ZailiWang** [comment]
Hi, would you share your script (train.py) as well as the model definition which can re-produce the issue?

**Comment by robogast** [comment]
Hi @ZailiWang, my stack is quite complex, so a minimal example is quite hard to make, however for completeness, my codebase resides here: https://github.com/sara-nl/2D-VQ-AE-2
However, today I've figured out that if I add `nn.ParameterDict` to the whitelist here: https://github.com/intel/intel-extension-for-pytorch/blob/12aff46c17c9917373402d885ff5fc8fe90f1b47/intel_extension_for_pytorch/nn/utils/_weight_cast.py#L9-L23
My model runs without the bf16->fp32->bf16->... yoyoing :)

See attached trace:
![image](https://user-images.githubusercontent.com/5969044/208958985-4dc1d25d-a6fa-4229-8a94-3eebb5276112.png)

**Comment by ZailiWang** [comment]
Wow, good for you :-) Thanks a lot for your information, we will check if this is common and should be updated in IPEX code.
