### ISSUE TITLE
Why some operators don't work with torch.float16?

### ISSUE THREAD

**Issue by BA8F0D39** [intel/intel-extension-for-pytorch#291]
I am using v1.13.10+xpu

Addition works with torch.float16
```
import torch
import intel_extension_for_pytorch as ipex
A = torch.randn(3, 4, 5, dtype=torch.float16)
B = torch.randn(3, 4, 5, dtype=torch.float16)
C = A + B
```

But convolution operators don't work with torch.float16
```
m = torch.nn.Conv1d(16, 33, 3, stride=2, dtype=torch.float16)
input = torch.randn(20, 16, 50, dtype=torch.float16)
output = m(input)
print(output)
```

```
[W OperatorEntry.cpp:150] Warning: Overriding a previously registered kernel for the same operator and the same dispatch key
  operator: torchvision::nms
    no debug info
  dispatch key: CPU
  previous kernel: registered at /build/intel-pytorch-extension/csrc/cpu/aten/TorchVisionNms.cpp:47
       new kernel: registered at /opt/workspace/vision/torchvision/csrc/ops/cpu/nms_kernel.cpp:112 (function registerKernel)
/usr/local/lib/python3.10/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 
  warn(f"Failed to load image Python extension: {e}")
Traceback (most recent call last):
  File "/workspace/./b.py", line 16, in <module>
    output = m(input)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/conv.py", line 313, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/conv.py", line 309, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
RuntimeError: "slow_conv2d_cpu" not implemented for 'Half'
```

But all torch.bfloat16 operations work perfectly

**Comment by jingxu10** [comment]
You need to move the data and the model to GPU with _.to('xpu')_, otherwise the computation happens on CPU.
Please also try with AMP:
https://intel.github.io/intel-extension-for-pytorch/xpu/latest/tutorials/examples.html#float16

**Comment by BA8F0D39** [comment]
@jingxu10 
Thanks,
Also is torch.float16 or torch.bfloat16 native on the A770?

Which format is more optimized for inference?

**Comment by jingxu10** [comment]
Please use float16 on inference workloads.
