### ISSUE TITLE
Torchvision functions are broken

### ISSUE THREAD

**Issue by BA8F0D39** [intel/intel-extension-for-pytorch#297]
Using the docker image
https://github.com/intel/intel-extension-for-pytorch/tree/v1.13.10%2Bxpu/docker

Reading an image gives an error
```
import torch
from torchvision.io import read_image
import intel_extension_for_pytorch as ipex

print("reading")
image = read_image("a.png")
print("done")
```

```
root@3ddc5256fb95:/workspace# python3 ./a.py 
/usr/local/lib/python3.10/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 
  warn(f"Failed to load image Python extension: {e}")
reading
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/_ops.py", line 501, in __getattr__
    op, overload_names = torch._C._jit_get_operation(qualified_op_name)
RuntimeError: No such operator image::read_file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspace/./a.py", line 12, in <module>
    image = read_image("a.png")
  File "/usr/local/lib/python3.10/dist-packages/torchvision/io/image.py", line 253, in read_image
    data = read_file(path)
  File "/usr/local/lib/python3.10/dist-packages/torchvision/io/image.py", line 47, in read_file
    data = torch.ops.image.read_file(path)
  File "/usr/local/lib/python3.10/dist-packages/torch/_ops.py", line 505, in __getattr__
    raise AttributeError(
AttributeError: '_OpNamespace' 'image' object has no attribute 'read_file'
```

**Comment by Sikerdebaard** [comment]
Adding to this: this seems to happen because various libs are missing in all of the stable release torchvision [Intel® Extension for PyTorch* v1.13.10+xpu](https://github.com/intel/intel-extension-for-pytorch/releases/tag/v1.13.10%2Bxpu) wheels.

This is not limited to the image.so lib, the whole torchvision.libs directory is missing. Installing these libs from regular cpu torchvision wheels on pypi does not yield a working version of torchvision.

In its current state pytorch + torchvision seems to be broken and cannot be used.

**Comment by jingxu10** [comment]
@WeizhuoZhang-intel

**Comment by BA8F0D39** [comment]
@Sikerdebaard 
Thanks.
Did they just delete the libraries so that they don't give any errors?

**Comment by Yorizuka** [comment]
I installed pytorch using the instruction given in the readme `python -m pip install torch==2.0.1a0 torchvision==0.15.2a0 intel_extension_for_pytorch==2.0.110+xpu --extra-index-url https://pytorch-extension.intel.com/release-whl/stable/xpu/us/`

This warning is produced when torch is loaded.
```
import torch
import intel_extension_for_pytorch as ipex
print(ipex.xpu.get_device_name(0))
```

UserWarning: Failed to load image Python extension: ''If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?

What steps should I take correct this?
