### ISSUE TITLE
Is it possible to officially build a wheel for torchaudio?

### ISSUE THREAD

**Issue by Aloereed** [intel/intel-extension-for-pytorch#301]
Torchaudio I build from source code always has the following errors.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/audio/torchaudio/__init__.py", line 1, in <module>
    from torchaudio import (  # noqa: F401
  File "/home/audio/torchaudio/_extension.py", line 135, in <module>
    _init_extension()
  File "/home/audio/torchaudio/_extension.py", line 105, in _init_extension
    _load_lib("libtorchaudio")
  File "/home/audio/torchaudio/_extension.py", line 52, in _load_lib
    torch.ops.load_library(path)
  File "/home/miniconda3/envs/sovits/lib/python3.8/site-packages/torch/_ops.py", line 573, in load_library
    ctypes.CDLL(path)
  File "/home/miniconda3/envs/sovits/lib/python3.8/ctypes/__init__.py", line 369, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /opt/intel/oneapi/mkl/2023.0.0/lib/intel64/libmkl_intel_thread.so.2: undefined symbol: __kmpc_reduce_nowait

**Comment by hashFactory** [comment]
Would love to see this as well!

**Comment by jingxu10** [comment]
Please compile torchaudio from source.
