### ISSUE TITLE
Potential regression: torch.autograd.backward now requires FP64 on XPU - invalid_kernel("uses-fp64-math")

### ISSUE THREAD

**Issue by substanc3-dev** [intel/intel-extension-for-pytorch#307]
### Describe the bug

It seems as though some change between `v1.10.200+gpu` and `1.13.10+xpu` caused previously working code to fine-tune a Flan-T5 model to no longer work due to an FP64 requirement (which is not supported on Flex). This code previously worked on `v1.10.200+gpu` (inside the `intel/intel-extension-for-pytorch:gpu` docker container containing this version), however this no longer works inside the latest image on tag `intel/intel-extension-for-pytorch:xpu-flex` with the `1.13.10+xpu` version. Assuming a potential culprit could be the added CPU support causing the application to resort to FP64 which is supported on those platforms, however I wasn't able to investigate super deep, so that's just a guess. Any workarounds or fixes would be appreciated.

Reproducible example: https://gist.github.com/substanc3-dev/1f497b2a308b7dc84fa5fc3f32fab759

The container is being run inside Docker Desktop on Windows 11 (22H2 retail non-insider 22621.1265) with the 31.0.101.4146 driver installed.

The full error: 
```
RuntimeError                              Traceback (most recent call last)
Cell In[13], line 1
----> 1 training_function(model)

Cell In[12], line 24, in training_function(model)
     23 loss = outputs['loss']
---> 24 loss.backward()
     25 optimizer.step()
     26 lr_scheduler.step()

File /usr/local/lib/python3.10/dist-packages/torch/_tensor.py:487, in Tensor.backward(self, gradient, retain_graph, create_graph, inputs)
    477 if has_torch_function_unary(self):
    478     return handle_torch_function(
    479         Tensor.backward,
    480         (self,),
   (...)
    485         inputs=inputs,
    486     )
--> 487 torch.autograd.backward(
    488     self, gradient, retain_graph, create_graph, inputs=inputs
    489 )

File /usr/local/lib/python3.10/dist-packages/torch/autograd/__init__.py:197, in backward(tensors, grad_tensors, retain_graph, create_graph, grad_variables, inputs)
    192     retain_graph = create_graph
    194 # The reason we repeat same the comment below is that
    195 # some Python versions print out the first line of a multi-line function
    196 # calls in the traceback and some print out the last line
--> 197 Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
    198     tensors, grad_tensors_, retain_graph, create_graph, inputs,
    199     allow_unreachable=True, accumulate_grad=True)

RuntimeError: Native API failed. Native API returns: -996 (Function exists but address is not available)
invalid_kernel("uses-fp64-math")
 -996 (Function exists but address is not available)```

### Versions

[W OperatorEntry.cpp:150] Warning: Overriding a previously registered kernel for the same operator and the same dispatch key
  operator: torchvision::nms
    no debug info
  dispatch key: CPU
  previous kernel: registered at /build/intel-pytorch-extension/csrc/cpu/aten/TorchVisionNms.cpp:47
       new kernel: registered at /opt/workspace/vision/torchvision/csrc/ops/cpu/nms_kernel.cpp:112 (function registerKernel)
/usr/local/lib/python3.10/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension:
  warn(f"Failed to load image Python extension: {e}")
Collecting environment information...
PyTorch version: 1.13.0a0+gitb1dde16
PyTorch CXX11 ABI: Yes
IPEX version: 1.13.10+xpu
IPEX commit: 7d85b0e92
Build type: Release

OS: Ubuntu 22.04.1 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: N/A
IGC version: N/A
CMake version: N/A
Libc version: glibc-2.35

Python version: 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] (64-bit runtime)
Python platform: Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Is XPU available: True
DPCPP runtime version: N/A
MKL version: N/A
GPU models and configuration:
[0] _DeviceProperties(name='Intel(R) Graphics [0x56a0]', platform_name='Intel(R) Level-Zero', dev_type='gpu, support_fp64=0, total_memory=13004MB, max_compute_units=512)
Intel OpenCL ICD version: 22.43.24595.35+i538~22.04
Level Zero version: 1.3.24595.35+i538~22.04

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   48 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          24
On-line CPU(s) list:             0-23
Vendor ID:                       AuthenticAMD
Model name:                      AMD Ryzen 9 5900X 12-Core Processor
CPU family:                      25
Model:                           33
Thread(s) per core:              2
Core(s) per socket:              12
Socket(s):                       1
Stepping:                        0
BogoMIPS:                        7400.05
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl tsc_reliable nonstop_tsc cpuid extd_apicid pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy svm cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw topoext perfctr_core ssbd ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves clzero xsaveerptr arat npt nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold v_vmsave_vmload umip vaes vpclmulqdq rdpid fsrm
Virtualization:                  AMD-V
Hypervisor vendor:               Microsoft
Virtualization type:             full
L1d cache:                       384 KiB (12 instances)
L1i cache:                       384 KiB (12 instances)
L2 cache:                        6 MiB (12 instances)
L3 cache:                        32 MiB (1 instance)
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] intel-extension-for-pytorch==1.13.10+xpu
[pip3] numpy==1.24.1
[pip3] torch==1.13.0a0+gitb1dde16
[pip3] torchvision==0.14.1a0+0504df5
[conda] N/A

**Comment by RigoLigoRLC** [comment]
Encountered this issue when testing openvpi/DiffSinger training too. Posting my output here for more info

```
(diff) rigoligo@RIGO-DESKTOP:~/gitcode/DiffSinger$ python run.py --config configs/acoustic/nomidi.yaml --exp_name cpop-xpu --reset
[W OperatorEntry.cpp:150] Warning: Overriding a previously registered kernel for the same operator and the same dispatch key
  operator: torchvision::nms
    no debug info
  dispatch key: CPU
  previous kernel: registered at /build/intel-pytorch-extension/csrc/cpu/aten/TorchVisionNms.cpp:47
       new kernel: registered at /opt/workspace/vision/torchvision/csrc/ops/cpu/nms_kernel.cpp:112 (function registerKernel)
/home/rigoligo/miniconda3/envs/diff/lib/python3.8/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension:
  warn(f"Failed to load image Python extension: {e}")
| Hparams chains:  ['configs/basics/base.yaml', 'configs/basics/fs2.yaml', 'configs/acoustic/nomidi.yaml']
| Hparams:
K_step: 1000, accumulate_grad_batches: 1, audio_num_mel_bins: 128, audio_sample_rate: 44100, base_config: ['configs/basics/fs2.yaml'],
binarization_args: {'shuffle': True, 'with_txt': True, 'with_wav': False, 'with_align': True, 'with_spk_embed': False, 'with_f0': True, 'with_f0cwt': True}, binarizer_cls: data_gen.acoustic.AcousticBinarizer, binary_data_dir: data/opencpop/binary, check_val_every_n_epoch: 10, clip_grad_norm: 1,
content_cond_steps: [], cwt_add_f0_loss: False, cwt_hidden_size: 128, cwt_layers: 2, cwt_loss: l1,
cwt_std_scale: 0.8, datasets: ['opencpop'], debug: False, dec_ffn_kernel_size: 9, dec_layers: 4,
decay_steps: 50000, decoder_type: fft, dict_dir: , diff_decoder_type: wavenet, diff_loss_type: l2,
dilation_cycle_length: 4, dropout: 0.1, ds_workers: 4, dur_enc_hidden_stride_kernel: ['0,2,3', '0,2,3', '0,1,3'], dur_loss: mse,
dur_predictor_kernel: 3, dur_predictor_layers: 2, enc_ffn_kernel_size: 9, enc_layers: 4, encoder_K: 8,
encoder_type: fft, endless_ds: True, f0_embed_type: continuous, ffn_act: gelu, ffn_padding: SAME,
fft_size: 2048, fmax: 16000, fmin: 40, g2p_dictionary: checkpoints/cpop-xpu/opencpop-extension.txt, gamma: 0.5,
gaussian_start: True, gen_dir_name: , gen_tgt_spk_id: -1, hidden_size: 256, hop_size: 512,
infer: False, keep_bins: 128, lambda_commit: 0.25, lambda_energy: 0.0, lambda_f0: 0.0,
lambda_ph_dur: 0.0, lambda_sent_dur: 0.0, lambda_uv: 0.0, lambda_word_dur: 0.0, load_ckpt: ,
log_interval: 100, loud_norm: False, lr: 0.0004, max_beta: 0.02, max_epochs: 1000,
max_eval_sentences: 1, max_eval_tokens: 60000, max_frames: 8000, max_input_tokens: 1550, max_sentences: 48,
max_tokens: 80000, max_updates: 320000, mel_loss: ssim:0.5|l1:0.5, mel_vmax: 1.5, mel_vmin: -6.0,
min_level_db: -120, norm_type: gn, num_ckpt_keep: 3, num_heads: 2, num_sanity_val_steps: 1,
num_spk: 1, num_test_samples: 0, num_valid_plots: 10, optimizer_adam_beta1: 0.9, optimizer_adam_beta2: 0.98,
original_g2p_dictionary: dictionaries/opencpop-extension.txt, out_wav_norm: False, permanent_ckpt_interval: 40000, permanent_ckpt_start: 120000, pitch_ar: False,
pitch_enc_hidden_stride_kernel: ['0,2,5', '0,2,5', '0,2,5'], pitch_extractor: parselmouth, pitch_loss: l1, pitch_norm: log, pitch_type: frame,
pndm_speedup: 10, pre_align_args: {'use_tone': True, 'forced_align': 'mfa', 'use_sox': False, 'txt_processor': 'en', 'allow_no_txt': False, 'denoise': False}, pre_align_cls: , predictor_dropout: 0.5, predictor_grad: 0.0,
predictor_hidden: -1, predictor_kernel: 5, predictor_layers: 5, prenet_dropout: 0.5, prenet_hidden_size: 256,
pretrain_fs_ckpt: , processed_data_dir: , profile_infer: False, raw_data_dir: data/opencpop/raw, ref_norm_layer: bn,
rel_pos: True, reset_phone_dict: True, residual_channels: 384, residual_layers: 20, save_best: False,
save_ckpt: True, save_codes: ['configs', 'modules', 'src', 'utils'], save_f0: True, save_gt: False, schedule_type: linear,
seed: 1234, sort_by_len: True, spec_max: [0], spec_min: [-5], spk_cond_steps: [],
stop_token_weight: 5.0, task_cls: src.naive_task.NaiveTask, test_ids: [], test_input_dir: , test_num: 0,
test_prefixes: ['2044', '2086', '2092', '2093', '2100'], test_set_name: test, timesteps: 1000, train_set_name: train, use_denoise: False,
use_energy_embed: False, use_gt_dur: False, use_gt_f0: False, use_key_shift_embed: False, use_midi: False,
use_nsf: True, use_pitch_embed: True, use_pos_embed: True, use_speed_embed: False, use_spk_embed: False,
use_spk_id: False, use_split_spk_id: False, use_uv: False, use_var_enc: False, val_check_interval: 2000,
valid_num: 0, valid_set_name: valid, validate: False, vocoder: NsfHifiGAN, vocoder_ckpt: checkpoints/nsf_hifigan/model,
warmup_updates: 2000, wav2spec_eps: 1e-6, weight_decay: 0, win_size: 2048, work_dir: checkpoints/cpop-xpu,

| load phoneme set: ['AP', 'E', 'En', 'SP', 'a', 'ai', 'an', 'ang', 'ao', 'b', 'c', 'ch', 'd', 'e', 'ei', 'en', 'eng', 'er', 'f', 'g', 'h', 'i', 'i0', 'ia', 'ian', 'iang', 'iao', 'ie', 'in', 'ing', 'iong', 'ir', 'iu', 'j', 'k', 'l', 'm', 'n', 'o', 'ong', 'ou', 'p', 'q', 'r', 's', 'sh', 't', 'u', 'ua', 'uai', 'uan', 'uang', 'ui', 'un', 'uo', 'v', 'van', 've', 'vn', 'w', 'x', 'y', 'z', 'zh']
| Mel losses: {'ssim': 0.5, 'l1': 0.5}
| Load HifiGAN:  checkpoints/nsf_hifigan/model
Removing weight norm...
| Load HifiGAN:  checkpoints/nsf_hifigan/model
Removing weight norm...
| Copied codes to checkpoints/cpop-xpu/codes/20230308152207.
| Copied spk map to checkpoints/cpop-xpu/spk_map.json.
| model Arch:  GaussianDiffusion(
  (denoise_fn): DiffNet(
    (input_projection): Conv1d(128, 384, kernel_size=(1,), stride=(1,))
    (diffusion_embedding): SinusoidalPosEmb()
    (mlp): Sequential(
      (0): Linear(in_features=384, out_features=1536, bias=True)
      (1): Mish()
      (2): Linear(in_features=1536, out_features=384, bias=True)
    )
    (residual_layers): ModuleList(
      (0): ResidualBlock(
        (dilated_conv): Conv1d(384, 768, kernel_size=(3,), stride=(1,), padding=(1,))
        (diffusion_projection): Linear(in_features=384, out_features=384, bias=True)
        (conditioner_projection): Conv1d(256, 768, kernel_size=(1,), stride=(1,))
        (output_projection): Conv1d(384, 768, kernel_size=(1,), stride=(1,))
      )
      (1): ResidualBlock(
        (dilated_conv): Conv1d(384, 768, kernel_size=(3,), stride=(1,), padding=(2,), dilation=(2,))
        (diffusion_projection): Linear(in_features=384, out_features=384, bias=True)
        (conditioner_projection): Conv1d(256, 768, kernel_size=(1,), stride=(1,))
        (output_projection): Conv1d(384, 768, kernel_size=(1,), stride=(1,))
      )
      (2): ResidualBlock(
        (dilated_conv): Conv1d(384, 768, kernel_size=(3,), stride=(1,), padding=(4,), dilation=(4,))
        (diffusion_projection): Linear(in_features=384, out_features=384, bias=True)
        (conditioner_projection): Conv1d(256, 768, kernel_size=(1,), stride=(1,))
        (output_projection): Conv1d(384, 768, kernel_size=(1,), stride=(1,))
      )
      (3): ResidualBlock(
        (dilated_conv): Conv1d(384, 768, kernel_size=(3,), stride=(1,), padding=(8,), dilation=(8,))
        (diffusion_projection): Linear(in_features=384, out_features=384, bias=True)
        (conditioner_projection): Conv1d(256, 768, kernel_size=(1,), stride=(1,))
        (output_projection): Conv1d(384, 768, kernel_size=(1,), stride=(1,))
      )
      (4): ResidualBlock(
        (dilated_conv): Conv1d(384, 768, kernel_size=(3,), stride=(1,), padding=(1,))
        (diffusion_projection): Linear(in_features=384, out_features=384, bias=True)
        (conditioner_projection): Conv1d(256, 768, kernel_size=(1,), stride=(1,))
        (output_projection): Conv1d(384, 768, kernel_size=(1,), stride=(1,))
      )
      (5): ResidualBlock(
        (dilated_conv): Conv1d(384, 768, kernel_size=(3,), stride=(1,), padding=(2,), dilation=(2,))
        (diffusion_projection): Linear(in_features=384, out_features=384, bias=True)
        (conditioner_projection): Conv1d(256, 768, kernel_size=(1,), stride=(1,))
        (output_projection): Conv1d(384, 768, kernel_size=(1,), stride=(1,))
      )
      (6): ResidualBlock(
        (dilated_conv): Conv1d(384, 768, kernel_size=(3,), stride=(1,), padding=(4,), dilation=(4,))
        (diffusion_projection): Linear(in_features=384, out_features=384, bias=True)
        (conditioner_projection): Conv1d(256, 768, kernel_size=(1,), stride=(1,))
        (output_projection): Conv1d(384, 768, kernel_size=(1,), stride=(1,))
      )
      (7): ResidualBlock(
        (dilated_conv): Conv1d(384, 768, kernel_size=(3,), stride=(1,), padding=(8,), dilation=(8,))
        (diffusion_projection): Linear(in_features=384, out_features=384, bias=True)
        (conditioner_projection): Conv1d(256, 768, kernel_size=(1,), stride=(1,))
        (output_projection): Conv1d(384, 768, kernel_size=(1,), stride=(1,))
      )
      (8): ResidualBlock(
        (dilated_conv): Conv1d(384, 768, kernel_size=(3,), stride=(1,), padding=(1,))
        (diffusion_projection): Linear(in_features=384, out_features=384, bias=True)
        (conditioner_projection): Conv1d(256, 768, kernel_size=(1,), stride=(1,))
        (output_projection): Conv1d(384, 768, kernel_size=(1,), stride=(1,))
      )
      (9): ResidualBlock(
        (dilated_conv): Conv1d(384, 768, kernel_size=(3,), stride=(1,), padding=(2,), dilation=(2,))
        (diffusion_projection): Linear(in_features=384, out_features=384, bias=True)
        (conditioner_projection): Conv1d(256, 768, kernel_size=(1,), stride=(1,))
        (output_projection): Conv1d(384, 768, kernel_size=(1,), stride=(1,))
      )
      (10): ResidualBlock(
        (dilated_conv): Conv1d(384, 768, kernel_size=(3,), stride=(1,), padding=(4,), dilation=(4,))
        (diffusion_projection): Linear(in_features=384, out_features=384, bias=True)
        (conditioner_projection): Conv1d(256, 768, kernel_size=(1,), stride=(1,))
        (output_projection): Conv1d(384, 768, kernel_size=(1,), stride=(1,))
      )
      (11): ResidualBlock(
        (dilated_conv): Conv1d(384, 768, kernel_size=(3,), stride=(1,), padding=(8,), dilation=(8,))
        (diffusion_projection): Linear(in_features=384, out_features=384, bias=True)
        (conditioner_projection): Conv1d(256, 768, kernel_size=(1,), stride=(1,))
        (output_projection): Conv1d(384, 768, kernel_size=(1,), stride=(1,))
      )
      (12): ResidualBlock(
        (dilated_conv): Conv1d(384, 768, kernel_size=(3,), stride=(1,), padding=(1,))
        (diffusion_projection): Linear(in_features=384, out_features=384, bias=True)
        (conditioner_projection): Conv1d(256, 768, kernel_size=(1,), stride=(1,))
        (output_projection): Conv1d(384, 768, kernel_size=(1,), stride=(1,))
      )
      (13): ResidualBlock(
        (dilated_conv): Conv1d(384, 768, kernel_size=(3,), stride=(1,), padding=(2,), dilation=(2,))
        (diffusion_projection): Linear(in_features=384, out_features=384, bias=True)
        (conditioner_projection): Conv1d(256, 768, kernel_size=(1,), stride=(1,))
        (output_projection): Conv1d(384, 768, kernel_size=(1,), stride=(1,))
      )
      (14): ResidualBlock(
        (dilated_conv): Conv1d(384, 768, kernel_size=(3,), stride=(1,), padding=(4,), dilation=(4,))
        (diffusion_projection): Linear(in_features=384, out_features=384, bias=True)
        (conditioner_projection): Conv1d(256, 768, kernel_size=(1,), stride=(1,))
        (output_projection): Conv1d(384, 768, kernel_size=(1,), stride=(1,))
      )
      (15): ResidualBlock(
        (dilated_conv): Conv1d(384, 768, kernel_size=(3,), stride=(1,), padding=(8,), dilation=(8,))
        (diffusion_projection): Linear(in_features=384, out_features=384, bias=True)
        (conditioner_projection): Conv1d(256, 768, kernel_size=(1,), stride=(1,))
        (output_projection): Conv1d(384, 768, kernel_size=(1,), stride=(1,))
      )
      (16): ResidualBlock(
        (dilated_conv): Conv1d(384, 768, kernel_size=(3,), stride=(1,), padding=(1,))
        (diffusion_projection): Linear(in_features=384, out_features=384, bias=True)
        (conditioner_projection): Conv1d(256, 768, kernel_size=(1,), stride=(1,))
        (output_projection): Conv1d(384, 768, kernel_size=(1,), stride=(1,))
      )
      (17): ResidualBlock(
        (dilated_conv): Conv1d(384, 768, kernel_size=(3,), stride=(1,), padding=(2,), dilation=(2,))
        (diffusion_projection): Linear(in_features=384, out_features=384, bias=True)
        (conditioner_projection): Conv1d(256, 768, kernel_size=(1,), stride=(1,))
        (output_projection): Conv1d(384, 768, kernel_size=(1,), stride=(1,))
      )
      (18): ResidualBlock(
        (dilated_conv): Conv1d(384, 768, kernel_size=(3,), stride=(1,), padding=(4,), dilation=(4,))
        (diffusion_projection): Linear(in_features=384, out_features=384, bias=True)
        (conditioner_projection): Conv1d(256, 768, kernel_size=(1,), stride=(1,))
        (output_projection): Conv1d(384, 768, kernel_size=(1,), stride=(1,))
      )
      (19): ResidualBlock(
        (dilated_conv): Conv1d(384, 768, kernel_size=(3,), stride=(1,), padding=(8,), dilation=(8,))
        (diffusion_projection): Linear(in_features=384, out_features=384, bias=True)
        (conditioner_projection): Conv1d(256, 768, kernel_size=(1,), stride=(1,))
        (output_projection): Conv1d(384, 768, kernel_size=(1,), stride=(1,))
      )
    )
    (skip_projection): Conv1d(384, 384, kernel_size=(1,), stride=(1,))
    (output_projection): Conv1d(384, 128, kernel_size=(1,), stride=(1,))
  )
  (fs2): ParameterEncoder(
    (txt_embed): Embedding(67, 256, padding_idx=0)
    (dur_embed): Linear(in_features=1, out_features=256, bias=True)
    (encoder): Encoder(
      (layers): ModuleList(
        (0): TransformerEncoderLayer(
          (op): EncSALayer(
            (layer_norm1): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
            (self_attn): MultiheadAttention(
              (out_proj): Linear(in_features=256, out_features=256, bias=False)
            )
            (layer_norm2): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
            (ffn): TransformerFFNLayer(
              (ffn_1): Conv1d(256, 1024, kernel_size=(9,), stride=(1,), padding=(4,))
              (ffn_2): Linear(in_features=1024, out_features=256, bias=True)
            )
          )
        )
        (1): TransformerEncoderLayer(
          (op): EncSALayer(
            (layer_norm1): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
            (self_attn): MultiheadAttention(
              (out_proj): Linear(in_features=256, out_features=256, bias=False)
            )
            (layer_norm2): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
            (ffn): TransformerFFNLayer(
              (ffn_1): Conv1d(256, 1024, kernel_size=(9,), stride=(1,), padding=(4,))
              (ffn_2): Linear(in_features=1024, out_features=256, bias=True)
            )
          )
        )
        (2): TransformerEncoderLayer(
          (op): EncSALayer(
            (layer_norm1): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
            (self_attn): MultiheadAttention(
              (out_proj): Linear(in_features=256, out_features=256, bias=False)
            )
            (layer_norm2): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
            (ffn): TransformerFFNLayer(
              (ffn_1): Conv1d(256, 1024, kernel_size=(9,), stride=(1,), padding=(4,))
              (ffn_2): Linear(in_features=1024, out_features=256, bias=True)
            )
          )
        )
        (3): TransformerEncoderLayer(
          (op): EncSALayer(
            (layer_norm1): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
            (self_attn): MultiheadAttention(
              (out_proj): Linear(in_features=256, out_features=256, bias=False)
            )
            (layer_norm2): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
            (ffn): TransformerFFNLayer(
              (ffn_1): Conv1d(256, 1024, kernel_size=(9,), stride=(1,), padding=(4,))
              (ffn_2): Linear(in_features=1024, out_features=256, bias=True)
            )
          )
        )
      )
      (layer_norm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      (embed_tokens): Embedding(67, 256, padding_idx=0)
      (embed_positions): RelPositionalEncoding(
        (dropout): Dropout(p=0.0, inplace=False)
      )
    )
    (pitch_embed): Linear(in_features=1, out_features=256, bias=True)
  )
)
| model Trainable Parameters: 43.518M
sample time step: 100%|████████████████████████████████████████████████████████| 100/100 [00:04<00:00, 23.87it/s]
Traceback (most recent call last):█████████████████████████████████████████████▍| 99/100 [00:04<00:00, 22.21it/s]
  File "run.py", line 15, in <module>
    run_task()
  File "run.py", line 11, in run_task
    task_cls.start()
  File "/home/rigoligo/gitcode/DiffSinger/basics/base_task.py", line 242, in start
    trainer.fit(task)
  File "/home/rigoligo/gitcode/DiffSinger/utils/pl_utils.py", line 498, in fit
    self.run_pretrain_routine(model)
  File "/home/rigoligo/gitcode/DiffSinger/utils/pl_utils.py", line 574, in run_pretrain_routine
    self.evaluate(model, self.get_val_dataloaders(), self.num_sanity_val_steps, self.testing)
  File "/home/rigoligo/gitcode/DiffSinger/utils/pl_utils.py", line 1194, in evaluate
    output = self.evaluation_forward(model,
  File "/home/rigoligo/gitcode/DiffSinger/utils/pl_utils.py", line 1318, in evaluation_forward
    output = model.validation_step(*args)
  File "/home/rigoligo/gitcode/DiffSinger/src/naive_task.py", line 85, in validation_step
    self.plot_wav(batch_idx, sample['mels'], model_out['mel_out'], gt_f0=gt_f0, pred_f0=pred_f0)
  File "/home/rigoligo/gitcode/DiffSinger/src/diffspeech_task.py", line 121, in plot_wav
    gt_wav = self.vocoder.spec2wav(gt_mel, f0=gt_f0)
  File "/home/rigoligo/gitcode/DiffSinger/src/vocoders/nsf_hifigan.py", line 79, in spec2wav
    y = self.model(c, f0).view(-1)
  File "/home/rigoligo/miniconda3/envs/diff/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/rigoligo/gitcode/DiffSinger/modules/nsf_hifigan/models.py", line 255, in forward
    har_source = self.m_source(f0, self.upp).transpose(1, 2)
  File "/home/rigoligo/miniconda3/envs/diff/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/rigoligo/gitcode/DiffSinger/modules/nsf_hifigan/models.py", line 211, in forward
    sine_wavs, uv, _ = self.l_sin_gen(x, upp)
  File "/home/rigoligo/miniconda3/envs/diff/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/rigoligo/miniconda3/envs/diff/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/rigoligo/gitcode/DiffSinger/modules/nsf_hifigan/models.py", line 146, in forward
    tmp_over_one = torch.cumsum(rad_values.double(), 1)  # % 1  #####%1意味着后面的cumsum无法再优化
RuntimeError: Native API failed. Native API returns: -996 (Function exists but address is not available)
invalid_kernel("uses-fp64-math")
 -996 (Function exists but address is not available)
(diff) rigoligo@RIGO-DESKTOP:~/gitcode/DiffSinger$
```

**Comment by jingxu10** [comment]
issue seems to be from tanhBackward kernel within NewGeluActivation,
We will look into it further.

**Comment by vishnumadhu365** [comment]
The issue will be fixed in the next release of IPEX XPU

**Comment by vishnumadhu365** [comment]
@substanc3-dev meanwhile if it helps, you could try the latest version by building from source. Below references should help:
1. manual - https://intel.github.io/intel-extension-for-pytorch/xpu/1.13.10+xpu/tutorials/installation.html#install-via-compiling-from-source
OR
2. build script - https://github.com/intel/intel-extension-for-pytorch/blob/xpu-master/scripts/compile_bundle.sh

**Comment by deepglugs** [comment]
> The issue will be fixed in the next release of IPEX XPU

When is the next release for XPU?  Last release was almost 4 months ago.

**Comment by jingxu10** [comment]
It will be taking some time before next release.
Currently, you can compile from source with https://github.com/intel/intel-extension-for-pytorch/blob/xpu-master/scripts/compile_bundle.sh
please try with oneapi basekit 2023.1 and the latest driver.
