### ISSUE TITLE
Import error occurs when running ipexrun, so I want to know how to take action

### ISSUE THREAD

**Issue by park12sj** [intel/intel-extension-for-pytorch#313]
### Describe the issue

The following error occurs when running ipexrun
```
Traceback (most recent call last):
  File "/opt/conda/envs/py38/bin/ipexrun", line 5, in <module>
    from intel_extension_for_pytorch.cpu.launch import main
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/intel_extension_for_pytorch/__init__.py", line 9, in <module>
    from .cpu import _cpu_isa
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/intel_extension_for_pytorch/cpu/__init__.py", line 2, in <module>
    from . import runtime
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/intel_extension_for_pytorch/cpu/runtime/__init__.py", line 3, in <module>
    from .multi_stream import MultiStreamModule, get_default_num_streams, \
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/intel_extension_for_pytorch/cpu/runtime/multi_stream.py", line 4, in <module>
    import intel_extension_for_pytorch._C as core
ImportError: /opt/conda/envs/py38/lib/python3.8/site-packages/intel_extension_for_pytorch/lib/libintel-ext-pt-cpu.so: undefined symbol: _ZN3c1010TensorTypeC1ENS_8optionalINS_10ScalarTypeEEENS1_INS_6DeviceEEERKNS_13SymbolicShapeERKNS_12VaryingShapeINS_6StrideEEENS1_IbEESE_
```

Torch and ipex version are as follows. The same issue exists when the torch version is 1.13.0, 1.13.0+cpu
```
intel-extension-for-pytorch 2.0.0
torch                       2.1.0.dev20230326+cpu
```

**Comment by jingxu10** [comment]
Please use PyTorch and IPEX with the same major version. i.e. both 2.0.0 or both 2.1.0...

**Comment by park12sj** [comment]
@jingxu10 

https://github.com/intel/intel-extension-for-pytorch#installation
Is there a problem since the version like the text was installed using the install command in the guide link above?

Separately, I set it to 1.13.0 and it was solved. Thank you.

**Comment by jingxu10** [comment]
torch                       2.1.0.dev20230326+cpu
the torch you installed is 2.1.0, the nightly build. switching it to stable release 2.0.0 would work.
