### ISSUE TITLE
importing failed due to undefined symbol: _ZNK5torch8autograd4Node4nameEv

### ISSUE THREAD

**Issue by qianguih** [intel/intel-extension-for-pytorch#317]
### Describe the issue

Installed via the following command:
`python -m pip install intel_extension_for_pytorch`
And here is my pytorch info:
```
>>> torch.__version__
'2.0.0+cpu'
>>> torch.__config__.show()
'PyTorch built with:\n  - GCC 8.4\n  - C++ Version: 201703\n  - Intel(R) Math Kernel Library Version 2020.0.4 Product Build 20200917 for Intel(R) 64 architecture applications\n  - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)\n  - OpenMP 201511 (a.k.a. OpenMP 4.5)\n  - LAPACK is enabled (usually provided by MKL)\n  - CPU capability usage: AVX2\n  - CUDA Runtime 11.8\n  - NVCC architecture flags: -gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_89,code=sm_89;-gencode;arch=compute_90,code=sm_90\n  - CuDNN 8.6\n  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.8, CUDNN_VERSION=8.6.0, CXX_COMPILER=/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=1 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_PYTORCH_QNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.0.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF, \n'
```
And error appeared when trying to import `intel_extension_for_pytorch`:
```
>>> import intel_extension_for_pytorch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/pyenv/versions/3.10.0/lib/python3.10/site-packages/intel_extension_for_pytorch/__init__.py", line 9, in <module>
    from .cpu import _cpu_isa
  File "/pyenv/versions/3.10.0/lib/python3.10/site-packages/intel_extension_for_pytorch/cpu/__init__.py", line 2, in <module>
    from . import runtime
  File "/pyenv/versions/3.10.0/lib/python3.10/site-packages/intel_extension_for_pytorch/cpu/runtime/__init__.py", line 3, in <module>
    from .multi_stream import MultiStreamModule, get_default_num_streams, \
  File "/pyenv/versions/3.10.0/lib/python3.10/site-packages/intel_extension_for_pytorch/cpu/runtime/multi_stream.py", line 4, in <module>
    import intel_extension_for_pytorch._C as core
ImportError: /pyenv/versions/3.10.0/lib/python3.10/site-packages/intel_extension_for_pytorch/lib/libintel-ext-pt-cpu.so: undefined symbol: _ZNK5torch8autograd4Node4nameEv
```

Any idea what might be wrong here and how I can fix this?

**Comment by gc-fu** [comment]
I encounter the exact same error.

I built the PyTorch `v1.13.1` from source, the PyTorch related info is listed below:

```python

>>> import torch
>>> torch.__config__.show()
'PyTorch built with:\n  - GCC 9.4\n  - C++ Version: 201402\n  - Intel(R) oneAPI Math Kernel Library Version 2023.0-Product Build 20221128 for Intel(R) 64 architecture applications\n  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)\n  - OpenMP 201511 (a.k.a. OpenMP 4.5)\n  - LAPACK is enabled (usually provided by MKL)\n  - NNPACK is enabled\n  - CPU capability usage: AVX2\n  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CXX_COMPILER=/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.1, USE_CUDA=0, USE_CUDNN=OFF, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=1, USE_MPI=0, USE_NCCL=OFF, USE_NNPACK=ON, USE_OPENMP=1, USE_ROCM=0, \n'
```

Error when imported ipex:
```python
root@icx-6:/ppml# python3 test.py
/usr/local/lib/python3.8/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: libc10_cuda.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")
Traceback (most recent call last):
  File "test.py", line 19, in <module>
    import intel_extension_for_pytorch as ipex
  File "/usr/local/lib/python3.8/dist-packages/intel_extension_for_pytorch/__init__.py", line 24, in <module>
    from . import cpu
  File "/usr/local/lib/python3.8/dist-packages/intel_extension_for_pytorch/cpu/__init__.py", line 2, in <module>
    from . import runtime
  File "/usr/local/lib/python3.8/dist-packages/intel_extension_for_pytorch/cpu/runtime/__init__.py", line 3, in <module>
    from .multi_stream import MultiStreamModule, get_default_num_streams, \
  File "/usr/local/lib/python3.8/dist-packages/intel_extension_for_pytorch/cpu/runtime/multi_stream.py", line 4, in <module>
    import intel_extension_for_pytorch._C as core
ImportError: /usr/local/lib/python3.8/dist-packages/intel_extension_for_pytorch/lib/libintel-ext-pt-cpu.so: undefined symbol: _ZNK5torch8autograd4Node4nameEv
```


```bash
root@icx-6:/ppml# pip3 list | grep torch
WARNING: The directory '/root/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
intel-extension-for-pytorch 1.13.100
pytorch-lightning           1.6.4
torch                       1.13.1               /pytorch1
torchmetrics                0.11.0
torchvision                 0.14.1


```

**Comment by gc-fu** [comment]
It seems that my error was caused by wired compile issues.  I cannot find `_ZNK5torch8autograd4Node4nameEv` in `libtorch_cpu.so`.  However, I can find `_ZNK5torch8autograd4Node4nameB5cxx11Ev` in `libtorch_cpu.so`.  The `B5cxx11Ev` indicates that it uses the C++11 ABI.  I believe this is the correct behavior.

I try to use other compilers in my system.  However, I cannot build one with symbol `_ZNK5torch8autograd4Node4nameEv`.

A workaround could be using `libtorch_cpu.so` from official pypi releases to replace the one in your self-built torch directory.

**Comment by jgong5** [comment]
@qianguih To clarify things a bit, I noticed you were using PyTorch 2.0. What IPEX version did you use?

**Comment by gc-fu** [comment]
Although I did not find symbol `_ZNK5torch8autograd4Node4nameEv`, I did find symbol `_ZNK5torch8autograd4Node4nameB5cxx11Ev`.

The `B5cxx11Ev` at the end indicates that it uses the C++11 ABI, so I think it might be an issue about compile things?

**Comment by qianguih** [comment]
> @qianguih To clarify things a bit, I noticed you were using PyTorch 2.0. What IPEX version did you use? (note that you have to use the same version of PyTorch and IPEX, e.g., PyTorch 1.13 w/ IPEX 1.13, PyTorch 2.0 vs. IPEX 2.0, etc.)

It's IPEX 2.0.0, the latest on main.

**Comment by jingxu10** [comment]
@qianguih please run https://github.com/intel/intel-extension-for-pytorch/blob/master/scripts/collect_env.py and share the output.

**Comment by gc-fu** [comment]
> Although I did not find symbol `_ZNK5torch8autograd4Node4nameEv`, I did find symbol `_ZNK5torch8autograd4Node4nameB5cxx11Ev`.
> 
> The `B5cxx11Ev` at the end indicates that it uses the C++11 ABI, so I think it might be an issue about compile things?

Build IPEX from source seems to solve this problem

**Comment by qianguih** [comment]
> @qianguih please run https://github.com/intel/intel-extension-for-pytorch/blob/master/scripts/collect_env.py and share the output.

Here is the output. Please note that I have updated my local env to cuda version of pytorch. Hopefully it doesn't make a difference for u.
```
Collecting environment information...
PyTorch version: 2.0.0a0+gitc263bd4
PyTorch CXX11 ABI: Yes
IPEX version: N/A
IPEX commit: N/A
Build type: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 8.4.0-3ubuntu2) 8.4.0
Clang version: 10.0.0-4ubuntu1 
IGC version: N/A
CMake version: version 3.22.3
Libc version: glibc-2.31

Python version: 3.10.0 (default, Mar 29 2023, 21:31:08) [GCC 8.4.0] (64-bit runtime)
Python platform: Linux-5.14.0-1054-oem-x86_64-with-glibc2.31
Is XPU available: N/A
DPCPP runtime version: N/A
MKL version: N/A
GPU models and configuration: 
N/A
Intel OpenCL ICD version: N/A
Level Zero version: N/A

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   39 bits physical, 48 bits virtual
CPU(s):                          16
On-line CPU(s) list:             0-15
Thread(s) per core:              2
Core(s) per socket:              8
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           167
Model name:                      11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz
Stepping:                        1
CPU MHz:                         3500.000
CPU max MHz:                     5300.0000
CPU min MHz:                     800.0000
BogoMIPS:                        7008.00
Virtualization:                  VT-x
L1d cache:                       384 KiB
L1i cache:                       256 KiB
L2 cache:                        4 MiB
L3 cache:                        16 MiB
NUMA node0 CPU(s):               0-15
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Vulnerable: Clear CPU buffers attempted, no microcode; SMT vulnerable
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx avx512f avx512dq rdseed adx smap avx512ifma clflushopt intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp hwp_pkg_req avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq rdpid fsrm md_clear flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] intel-extension-for-pytorch==2.0.0
[pip3] mypy==1.1.1
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.2
[pip3] open-clip-torch==2.11.1
[pip3] torch==2.0.0a0+gitc263bd4
[pip3] torchvision==0.15.1a0+42759b1
[conda] N/A
```

**Comment by jingxu10** [comment]
The pytorch you are using is a self-built one. The intel_extension_for_pytorch we released is supposed to be working with publicly released pytorch 2.0.0+cpu.
In your case, please compile intel_extension_for_pytorch from source with your existing pytorch binary.
```
PyTorch version: 2.0.0a0+gitc263bd4
PyTorch CXX11 ABI: Yes
```

**Comment by qianguih** [comment]
cool, building from source fixed the issue. thanks!

**Comment by WolfKingAlex** [comment]
> cool, building from source fixed the issue. thanks!

how to build  IPEX from source

**Comment by olivier-s-j** [comment]
Fyi, I had the same issue. It was solved by:

`python -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu`
`python -m pip install --trusted-host pytorch-extension.intel.com  intel_extension_for_pytorch --extra-index-url https://pytorch-extension.intel.com/release-whl/stable/cpu/us/`


the main thing that helped was providing the --index-url
