### ISSUE TITLE
Inference fails after ipex.optimize

### ISSUE THREAD

**Issue by park12sj** [intel/intel-extension-for-pytorch#322]
### Describe the issue

There is an issue that cannot be infernced if I add `ipex.optimize` in the infernce code below.
Is there anything I missed that needs further action before ipex.optimize?

- test code
```
import torch
import torch.nn as nn
import clip
from joblib import load
import intel_extension_for_pytorch as ipex

class ScoringNet(nn.Module):
    def __init__(self, clip_path, svr_path):
        super(ScoringNet, self).__init__()
        model, _ = clip.load(clip_path)

        self.clip = model.visual
        print('clip loaded')
        self.svr = load(svr_path)
        print('svr loaded')

    def forward(self, input):
        out = self.clip(input).detach().cpu()
        out = self.svr.predict(out)
        return out # numpy array type


warmup_tensor = torch.rand((1, 3, 384, 384), dtype=torch.float32).to('cpu')
base_path = '/model'
model = ScoringNet(clip_path=f'{base_path}/scoring_clip.pt', svr_path=f'{base_path}/LinearSVR_clip2.joblib').to('cpu')
model.eval()
# model = ipex.optimize(model)

with torch.no_grad():
    output = model(warmup_tensor)
print(output)

```

- When there's no "ipex.optimize"
`[0.59768564]`
- When there's "ipex.optimize"
```
<intel_extension_for_pytorch.frontend._Properties object at 0x7fcee8b2ec40>
    /opt/conda/envs/py38/lib/python3.8/site-packages/intel_extension_for_pytorch/frontend.py:397: UserWarning: Conv BatchNorm folding failed during the optimize process.
      warnings.warn("Conv BatchNorm folding failed during the optimize process.")
    /opt/conda/envs/py38/lib/python3.8/site-packages/intel_extension_for_pytorch/frontend.py:402: UserWarning: Linear BatchNorm folding failed during the optimize process.
      warnings.warn("Linear BatchNorm folding failed during the optimize process.")
    Traceback (most recent call last):
      File "/workspace/storage/cephrbd/git/pai/ml/ml/serving/model/application/vision/image_scoring/temp.py", line 14, in <module>
        output = model(warmup_tensor)
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1191, in _call_impl
        return forward_call(*input, **kwargs)
      File "{local code path}/test.py", line 17, in forward
        out = self.clip(input).detach().cpu()
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1191, in _call_impl
        return forward_call(*input, **kwargs)
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/clip/model.py", line 152, in forward
        x = self.attnpool(x)
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1191, in _call_impl
        return forward_call(*input, **kwargs)
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/clip/model.py", line 72, in forward
        x, _ = F.multi_head_attention_forward(
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/torch/nn/functional.py", line 5055, in multi_head_attention_forward
        q, k, v = _in_projection(query, key, value, q_proj_weight, k_proj_weight, v_proj_weight, b_q, b_k, b_v)
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/torch/nn/functional.py", line 4799, in _in_projection
        assert w_q.shape == (Eq, Eq), f"expecting query weights shape of {(Eq, Eq)}, but got {w_q.shape}"
    AssertionError: expecting query weights shape of (3072, 3072), but got torch.Size([11813089])
```

- Below is the version information
```
torch                       1.13.0
intel-extension-for-pytorch 1.13.0
```

**Comment by park12sj** [comment]
It's working well without svr...
It was my fault.
