### ISSUE TITLE
compile_bundle.sh fails to build torch "missing cuda"

### ISSUE THREAD

**Issue by tripzero** [intel/intel-extension-for-pytorch#329]
### Describe the bug

Running ```
./compile_bundle.sh /opt/intel/oneapi/compiler/latest /opt/intel/oneapi/mkl/latest
```
with xpu-master(5fdf9e64581769fb8d5b0c1ffabb5f70fc3793bd) and get the following error:


```
running build_ext
running build_clib
-- The C compiler identification is IntelLLVM 2023.0.0
-- The CXX compiler identification is IntelLLVM 2023.0.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /opt/intel/oneapi/compiler/2023.0.0/linux/bin/icx - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/intel/oneapi/compiler/2023.0.0/linux/bin/icpx - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CUDA_TOOLKIT_ROOT_DIR not found or specified
-- Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) 
CMake Warning at /home/kev/anaconda3/envs/ipex/lib/python3.10/site-packages/torch/share/cmake/Caffe2/public/cuda.cmake:31 (message):
  Caffe2: CUDA cannot be found.  Depending on whether you are building Caffe2
  or a Caffe2 dependent library, the next warning / error will give you more
  info.
Call Stack (most recent call first):
  /home/kev/anaconda3/envs/ipex/lib/python3.10/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:88 (include)
  /home/kev/anaconda3/envs/ipex/lib/python3.10/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:68 (find_package)
  CMakeLists.txt:21 (find_package)

CMake Error at /home/kev/anaconda3/envs/ipex/lib/python3.10/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:90 (message):
  Your installed Caffe2 version uses CUDA but I cannot find the CUDA
  libraries.  Please set the proper CUDA prefixes and / or install CUDA.
Call Stack (most recent call first):
  /home/kev/anaconda3/envs/ipex/lib/python3.10/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:68 (find_package)
  CMakeLists.txt:21 (find_package)

-- Configuring incomplete, errors occurred!
Traceback (most recent call last):
  File "/home/kev/src/intel-extension-for-pytorch/scripts/intel-extension-for-pytorch/setup.py", line 868, in <module>
    setup(
  File "/home/kev/anaconda3/envs/ipex/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/home/kev/anaconda3/envs/ipex/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/kev/anaconda3/envs/ipex/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/kev/anaconda3/envs/ipex/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
    self.run_command(cmd)
  File "/home/kev/anaconda3/envs/ipex/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/home/kev/anaconda3/envs/ipex/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/home/kev/anaconda3/envs/ipex/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 299, in run
    self.run_command('build')
  File "/home/kev/anaconda3/envs/ipex/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
    self.distribution.run_command(command)
  File "/home/kev/anaconda3/envs/ipex/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/home/kev/anaconda3/envs/ipex/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/home/kev/anaconda3/envs/ipex/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 132, in run
    self.run_command(cmd_name)
  File "/home/kev/anaconda3/envs/ipex/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
    self.distribution.run_command(command)
  File "/home/kev/anaconda3/envs/ipex/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/home/kev/anaconda3/envs/ipex/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/home/kev/src/intel-extension-for-pytorch/scripts/intel-extension-for-pytorch/setup.py", line 838, in run
    self.run_command('build_clib')
  File "/home/kev/anaconda3/envs/ipex/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
    self.distribution.run_command(command)
  File "/home/kev/anaconda3/envs/ipex/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/home/kev/anaconda3/envs/ipex/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/home/kev/src/intel-extension-for-pytorch/scripts/intel-extension-for-pytorch/setup.py", line 607, in run
    _gen_build_cfg_from_cmake(cmake_exec, project_root_dir, cmake_args_gpu, ipex_xpu_build_dir, my_env)
  File "/home/kev/src/intel-extension-for-pytorch/scripts/intel-extension-for-pytorch/setup.py", line 474, in _gen_build_cfg_from_cmake
    check_call([cmake_exec, project_root_dir] + cmake_args, cwd=build_dir, env=build_env)
  File "/home/kev/anaconda3/envs/ipex/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/home/kev/src/intel-extension-for-pytorch/scripts/intel-extension-for-pytorch', '-DBUILD_MODULE_TYPE=GPU', '-DBUILD_WITH_XPU=ON', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_CXX_COMPILER=icpx', '-DCMAKE_C_COMPILER=icx', '-DCMAKE_INSTALL_INCLUDEDIR=include', '-DCMAKE_INSTALL_LIBDIR=lib', '-DCMAKE_INSTALL_PREFIX=/home/kev/src/intel-extension-for-pytorch/scripts/intel-extension-for-pytorch/build/Release/packages/intel_extension_for_pytorch', '-DCMAKE_PREFIX_PATH=/home/kev/anaconda3/envs/ipex/lib/python3.10/site-packages/torch/share/cmake;/opt/intel/oneapi/compiler/2023.0.0/linux/IntelDPCPP', '-DCMAKE_PROJECT_VERSION=1.13.120', '-DIPEX_INSTALL_LIBDIR=/home/kev/src/intel-extension-for-pytorch/scripts/intel-extension-for-pytorch/build/Release/packages/intel_extension_for_pytorch/lib', '-DIPEX_PROJ_NAME=intel_extension_for_pytorch', '-DLIBIPEX_GITREV=bb076cf7', '-DLIBIPEX_VERSION=1.13.120+gitbb076cf', '-DPYTHON_EXECUTABLE=/home/kev/anaconda3/envs/ipex/bin/python', '-DPYTHON_INCLUDE_DIR=/home/kev/anaconda3/envs/ipex/include/python3.10', '-DPYTHON_PLATFORM_INFO=Linux-6.2.0-060200rc7-generic-x86_64-with-glibc2.36', '-DUSE_LLVM=/home/kev/src/intel-extension-for-pytorch/scripts/llvm-project/build/../release']' returned non-zero exit status 1.
```

### Versions

Collecting environment information...
PyTorch version: 2.0.0+cu117
PyTorch CXX11 ABI: No
IPEX version: N/A
IPEX commit: N/A
Build type: N/A

OS: Ubuntu 22.10 (x86_64)
GCC version: (Ubuntu 12.2.0-3ubuntu1) 12.2.0
Clang version: 15.0.7
IGC version: N/A
CMake version: version 3.26.0
Libc version: glibc-2.36

Python version: 3.10.8 (main, Nov  4 2022, 13:48:29) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-6.2.0-060200rc7-generic-x86_64-with-glibc2.36
Is XPU available: N/A
DPCPP runtime version: N/A
MKL version: N/A
GPU models and configuration: 
N/A
Intel OpenCL ICD version: 22.49.25018.23+i554~22.04
Level Zero version: 1.3.25018.23+i554~22.04

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          24
On-line CPU(s) list:             0-23
Vendor ID:                       GenuineIntel
Model name:                      12th Gen Intel(R) Core(TM) i9-12900K
CPU family:                      6
Model:                           151
Thread(s) per core:              2
Core(s) per socket:              16
Socket(s):                       1
Stepping:                        2
CPU(s) scaling MHz:              81%
CPU max MHz:                     5200.0000
CPU min MHz:                     800.0000
BogoMIPS:                        6374.40
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault cat_l2 invpcid_single cdp_l2 ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdt_a rdseed adx smap clflushopt clwb intel_pt sha_ni xsaveopt xsavec xgetbv1 xsaves split_lock_detect avx_vnni dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp hwp_pkg_req hfi umip pku ospke waitpkg gfni vaes vpclmulqdq tme rdpid movdiri movdir64b fsrm md_clear serialize pconfig arch_lbr ibt flush_l1d arch_capabilities
Virtualization:                  VT-x
L1d cache:                       640 KiB (16 instances)
L1i cache:                       768 KiB (16 instances)
L2 cache:                        14 MiB (10 instances)
L3 cache:                        30 MiB (1 instance)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-23
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] pytorch-warmup==0.1.0
[pip3] torch==2.0.0
[pip3] torchaudio==0.13.1+b90d798
[conda] numpy                     1.23.5                   pypi_0    pypi
[conda] torch                     2.0.0                    pypi_0    pypi
[conda] torchaudio                0.13.1+b90d798           pypi_0    pypi

**Comment by jingxu10** [comment]
Please uninstall torch and torchaudio first and then run the script again.

**Comment by tripzero** [comment]
Something in the script is calling for torch to be installed in a requirements.txt, so it installs it even if I uninstall.  Looks like the first failure is building fbgemm.  It's treating all warnings as errors:

```
/usr/lib/gcc/x86_64-linux-gnu/12/include/emmintrin.h: In function ‘void fbgemm::requantizeOutputProcessingGConvAvx512(uint8_t*, const int32_t*, const block_type_t&, int, int, const requantizationParams_t<BIAS_TYPE>&) [with bool A_SYMMETRIC = false; bool B_SYMMETRIC = false; QuantizationGranularity Q_GRAN = fbgemm::QuantizationGranularity::OUT_CHANNEL; bool HAS_BIAS = false; bool FUSE_RELU = false; int C_PER_G = 16; BIAS_TYPE = int]’:
/usr/lib/gcc/x86_64-linux-gnu/12/include/emmintrin.h:788:11: note: ‘__Y’ was declared here
  788 |   __m128i __Y = __Y;
      |           ^~~
cc1plus: all warnings being treated as errors
```

If we turn on `set -e` in the script it will stop shortly after this so we can see what's going on.  What version of GCC are you using there?  Are we missing a flag to turn off werror?

**Comment by jingxu10** [comment]
the script applies patches to pytorch and compile it first. It should not install pytorch from pip. Please use the one in `xpu-master` branch.
for the git config one, if you do manually, please remove the invocations from the script.

**Comment by tripzero** [comment]
The problem was it was failing on compiling torch because it needs gcc-11 and I was using gcc-12 (which is more strict and causes warnings which turn to errors because of werror).  I added a check to ensure gcc-11 is being used.  I'll submit the PR as soon as I verify it competes all the way through.

**Comment by fredlarochelle** [comment]
A simple solution to execute the script without issues is to establish a Conda environnment using the following command: `conda create -n ipex_env gcc_linux-64=11 gxx_linux-64=11 python=3.10`.

**Comment by leuc** [comment]
what is the specific requirement to llvm-13 to build it from source and not use a distribution package?

**Comment by jingxu10** [comment]
> what is the specific requirement to llvm-13 to build it from source and not use a distribution package?

@xuhancn

**Comment by xuhancn** [comment]
@tripzero  Please upgrade basekit to 2023.1 and try again.

**Comment by tripzero** [comment]
After updating to basekit 2023.1, I now get an error during torchvision compilation:

error: AV_CODEC_CAP_INTRA_ONLY was not declared in this scope; did you mean AV_CODEC_PROP_INTRA_ONLY.

my ffmpeg is pretty new because I need a newer version to do AV1 encode on dg2.  Looks like there were some compatibility issues with torchvison and ffmpeg-5 that were solved last year.  Is this a consequence of our torchvision being too old?

**Comment by jingxu10** [comment]
Would you try upgrade torchvision version?
From our release perspective, we need to align the torchvision version with pytorch version following the table shown in [torchvision github repo](https://github.com/pytorch/vision#installation).
