### ISSUE TITLE
Which dependency versions were used in the 1.13.120+xpu build?

### ISSUE THREAD

**Issue by fhaust** [intel/intel-extension-for-pytorch#342]
### Describe the issue

I don't seem to find a valid combination of dependencies that would allow me to run the latest ipex build. You mention some issues in:

https://github.com/intel/intel-extension-for-pytorch/blob/v1.13.120%2Bxpu/docs/tutorials/performance_tuning/known_issues.md

Right now my dependencies are:

```bash
# pip list
Package                     Version
--------------------------- -------------------
certifi                     2022.12.7
charset-normalizer          3.1.0
**dpcpp-cpp-rt                2023.0.0**
filelock                    3.12.0
fsspec                      2023.4.0
huggingface-hub             0.14.1
idna                        3.4
intel-cmplr-lib-rt          2023.0.0
intel-cmplr-lic-rt          2023.0.0
intel-extension-for-pytorch 1.13.120+xpu
intel-opencl-rt             2023.0.0
intel-openmp                2023.0.0
**mkl                         2023.1.0**
**mkl-dpcpp                   2023.1.0**
numpy                       1.24.3
packaging                   23.1
Pillow                      9.5.0
pip                         23.1.2
psutil                      5.9.5
PyYAML                      6.0
regex                       2023.3.23
requests                    2.29.0
setuptools                  67.6.1
tbb                         2021.9.0
tokenizers                  0.13.3
torch                       1.13.0a0+git6c9b55e
torchvision                 0.14.1a0+5e8e2f1
tqdm                        4.65.0
transformers                4.28.1
typing_extensions           4.5.0
urllib3                     1.26.15
wheel                       0.40.0
```

(highlights signify dependencies that I installed in response to missing .so libraries)

I now seem to have all required .so dependencies, but I think they are not compatible with each other:

```bash
# LD_LIBRARY_PATH=venv/lib:$LD_LIBRARY_PATH ionice -c3 nice -n19 python -i ./stablelm_base_test.py 
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:11<00:00,  5.63s/it]
/home/florian/Dokumente/Projects/Python/stablelm/venv/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 
  warn(f"Failed to load image Python extension: {e}")
Traceback (most recent call last):
  File "/home/florian/Dokumente/Projects/Python/stablelm/./stablelm_base_test.py", line 6, in <module>
    import intel_extension_for_pytorch as ipex
  File "/home/florian/Dokumente/Projects/Python/stablelm/venv/lib/python3.10/site-packages/intel_extension_for_pytorch/__init__.py", line 8, in <module>
    from .utils._trap_module import *
  File "/home/florian/Dokumente/Projects/Python/stablelm/venv/lib/python3.10/site-packages/intel_extension_for_pytorch/utils/_trap_module.py", line 2, in <module>
    import intel_extension_for_pytorch._C
ImportError: venv/lib/libmkl_sycl.so.3: undefined symbol: _ZNK4sycl3_V16detail12buffer_plain13handleReleaseEv
>>> 
```

(I got tired of using LD_PRELOAD for everything ... so a blanket LD_LIBRARY_PATH it is)

**Comment by gujinghui** [comment]
env issue? @jingxu10

**Comment by jingxu10** [comment]
**dpcpp-cpp-rt                2023.0.0**
DPCPP runtime version doesn't seem to be 2023.1. Also, a compiler hotfix is required.
Would you double check compiler version?

**Comment by stacksmash76** [comment]
This is an issue currently actual on Arch Linux (which is not officially supported by Intel), since the official community repositories use 2023.0.0.25537-3. New version 2023.1.0.46401-1 is currently in community-testing. I can confirm that after updating everything works as expected and this issue is gone.

@fhaust 
If you are on Arch Linux, then you can install the package yourself: https://archlinux.org/packages/community-testing/x86_64/intel-oneapi-basekit/
(or build it yourself by cloning PKGBUILD and intel-oneapi-basekit.install to a single folder and doing `makepkg -si` or you could even use the official installer)
