### ISSUE TITLE
There has some failed test case for test_torch.py

### ISSUE THREAD

**Issue by XiaobingSuper** [intel/intel-extension-for-pytorch#35]
'''
ERROR: test_copy_all_dtypes_and_devices_dpcpp (__main__.TestTorchDeviceTypeDPCPP)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/xiaobinz/Downloads/intel-extension-for-pytorch/tests/cpu/common_device_type.py", line 227, in instantiated_test
    return test(self, device_arg)
  File "test_torch.py", line 10281, in test_copy_all_dtypes_and_devices
    y = copy(x)
  File "/home/xiaobinz/anaconda3/envs/pytorch-test/lib/python3.6/copy.py", line 96, in copy
    rv = reductor(4)
  File "/home/xiaobinz/Downloads/pytorch-xiaobing/torch/tensor.py", line 132, in __reduce_ex__
    args = (self.storage(),
RuntimeError: unsupported Storage type

======================================================================
FAIL: test_broadcast_batched_matmul_dpcpp (__main__.TestTorchDeviceTypeDPCPP)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/xiaobinz/Downloads/intel-extension-for-pytorch/tests/cpu/common_device_type.py", line 227, in instantiated_test
    return test(self, device_arg)
  File "test_torch.py", line 7589, in test_broadcast_batched_matmul
    verify_batched_matmul(*indices)
  File "test_torch.py", line 7581, in verify_batched_matmul
    self.assertEqual(truth, maybe_squeeze_result(l, r, out))
  File "/home/xiaobinz/Downloads/intel-extension-for-pytorch/tests/cpu/common_utils.py", line 782, in assertEqual
    assertTensorsEqual(x, y)
  File "/home/xiaobinz/Downloads/intel-extension-for-pytorch/tests/cpu/common_utils.py", line 752, in assertTensorsEqual
    self.assertLessEqual(max_err, prec, message)
AssertionError: tensor(2.8768, device='dpcpp') not less than or equal to 1e-05 :

======================================================================
FAIL: test_memory_format_clone_dpcpp (__main__.TestTorchDeviceTypeDPCPP)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/xiaobinz/Downloads/intel-extension-for-pytorch/tests/cpu/common_device_type.py", line 227, in instantiated_test
    return test(self, device_arg)
  File "test_torch.py", line 12852, in test_memory_format_clone
    device, get_generator(mf, shape), transformation_fn, mf, True, default_is_preserve=True)
  File "test_torch.py", line 12788, in _test_memory_format_transformations
    self.assertFalse(clone.is_contiguous())
AssertionError: True is not false
''''

**Comment by EikanWang** [comment]
The 3 failed test cases are known issues. Thanks to record here. I will mark it as bu.

**Comment by EikanWang** [comment]
We switched the underhood device to CPU. The issue has gone.
