### ISSUE TITLE
WARNING - Core binding with numactl is not available

### ISSUE THREAD

**Issue by NathanJHLee** [intel/intel-extension-for-pytorch#354]
### Describe the issue

Hi my name is Nathan

I am using ipex '1.13.100+cpu' and launch 'ipexrun'

When i try to run my binary file, Log shows WARNING as below.
How to fix this warn and use numactl.

My env is Centos 7.9 and
(base) [asr@aa026e4b97df libtorch]$ rpm -qa | grep numactl
numactl-2.0.12-5.el7.x86_64
numactl-libs-2.0.12-5.el7.x86_64
numactl-devel-2.0.12-5.el7.x86_64

Please check my error. Thank you.

(base) [asr@aa026e4b97df main]$ **ipexrun --no_python ./e2e-main-3200frame-online** --config=conf/e2e-dynamic-kor-8k.conf --chunk_size=32 ark:test-file-AI_Memo_8k_x1000.scp
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
set_mempolicy: Operation not permitted
setting membind: Operation not permitted
**2023-05-23 15:28:37,471 - intel_extension_for_pytorch.cpu.launch - WARNING - Core binding with numactl is not available. Disabling numactl and using taskset instead. This may affect performance in multi-socket system; please use numactl if memory binding is needed.**
2023-05-23 15:28:37,472 - intel_extension_for_pytorch.cpu.launch - INFO - Use TCMalloc memory allocator
2023-05-23 15:28:37,472 - intel_extension_for_pytorch.cpu.launch - INFO - OMP_NUM_THREADS=40
2023-05-23 15:28:37,472 - intel_extension_for_pytorch.cpu.launch - INFO - Using Intel OpenMP
2023-05-23 15:28:37,472 - intel_extension_for_pytorch.cpu.launch - INFO - KMP_AFFINITY=granularity=fine,compact,1,0
2023-05-23 15:28:37,473 - intel_extension_for_pytorch.cpu.launch - INFO - KMP_BLOCKTIME=1
2023-05-23 15:28:37,473 - intel_extension_for_pytorch.cpu.launch - INFO - LD_PRELOAD=/home/asr/miniconda3/lib/libiomp5.so:/usr/lib64/libtcmalloc.so
2023-05-23 15:28:37,473 - intel_extension_for_pytorch.cpu.launch - INFO - taskset -c 0-39 ./e2e-main-3200frame-online --config=conf/e2e-dynamic-kor-8k.conf --chunk_size=32 ark:test-file-AI_Memo_8k_x1000.scp
./e2e-main-3200frame-online --config=conf/e2e-dynamic-kor-8k.conf --chunk_size=32 ark:test-file-AI_Memo_8k_x1000.scp

**Traceback (most recent call last):
  File "/home/asr/miniconda3/bin/ipexrun", line 8, in <module>
    sys.exit(main())
  File "/home/asr/miniconda3/lib/python3.9/site-packages/intel_extension_for_pytorch/cpu/launch.py", line 881, in main
    launcher.launch(args)
  File "/home/asr/miniconda3/lib/python3.9/site-packages/intel_extension_for_pytorch/cpu/launch.py", line 543, in launch
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd_s)
subprocess.CalledProcessError: Command 'taskset -c 0-39 ./e2e-main-3200frame-online --config=conf/e2e-dynamic-kor-8k.conf --chunk_size=32 ark:test-file-AI_Memo_8k_x1000.scp' died with <Signals.SIGSEGV: 11>.**

**Comment by jingxu10** [comment]
pls try launch the docker container with `--privileged` flag.

**Comment by NathanJHLee** [comment]
Oh thank u soooooo~ much :D
