### ISSUE TITLE
xpu-master build for IGPU error

### ISSUE THREAD

**Issue by kyflores** [intel/intel-extension-for-pytorch#390]
### Describe the bug

When building for IGPU, On `xpu-master` (320f4da8224857c87eee76259b2626a3324e7ab), the script errors out late in the build.

I started from a fresh checkout and am in a conda environment with python 3.10. My commandline is:
```
bash compile_bundle.sh /opt/intel/oneapi/compiler/2023.2.0/ /opt/intel/oneapi/mkl/2023.2.0/ Gen12LP
```
And the error is:
```
Compilation from IR - skipping loading of FCL
Build succeeded for : 12.0.0.
llvm-foreach:
icpx: error: gen compiler command failed with exit code 245 (use -v to see invocation)
Intel(R) oneAPI DPC++/C++ Compiler 2023.2.0 (2023.2.0.20230622)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/intel/oneapi/compiler/2023.2.0/linux/bin-llvm
Configuration file: /opt/intel/oneapi/compiler/2023.2.0/linux/bin-llvm/../bin/icpx.cfg
icpx: note: diagnostic msg: Error generating preprocessed source(s).
make[2]: *** [csrc/gpu/CMakeFiles/intel-ext-pt-gpu.dir/build.make:4037: csrc/gpu/libintel-ext-pt-gpu.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:594: csrc/gpu/CMakeFiles/intel-ext-pt-gpu.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
Traceback (most recent call last):
  File "/home/user/Documents/intel-extension-for-pytorch/scripts/intel-extension-for-pytorch/setup.py", line 1103, in <module>
    setup(
  File "/home/user/miniconda3/envs/ipex/lib/python3.10/site-packages/setuptools/__init__.py", line 107, in setup
    return distutils.core.setup(**attrs)
  File "/home/user/miniconda3/envs/ipex/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/user/miniconda3/envs/ipex/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/user/miniconda3/envs/ipex/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/user/miniconda3/envs/ipex/lib/python3.10/site-packages/setuptools/dist.py", line 1244, in run_command
    super().run_command(command)
  File "/home/user/miniconda3/envs/ipex/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/user/miniconda3/envs/ipex/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 325, in run
    self.run_command("build")
  File "/home/user/miniconda3/envs/ipex/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/user/miniconda3/envs/ipex/lib/python3.10/site-packages/setuptools/dist.py", line 1244, in run_command
    super().run_command(command)
  File "/home/user/miniconda3/envs/ipex/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/user/miniconda3/envs/ipex/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 131, in run
    self.run_command(cmd_name)
  File "/home/user/miniconda3/envs/ipex/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/user/miniconda3/envs/ipex/lib/python3.10/site-packages/setuptools/dist.py", line 1244, in run_command
    super().run_command(command)
  File "/home/user/miniconda3/envs/ipex/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/user/Documents/intel-extension-for-pytorch/scripts/intel-extension-for-pytorch/setup.py", line 1072, in run
    self.run_command("build_clib")
  File "/home/user/miniconda3/envs/ipex/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/user/miniconda3/envs/ipex/lib/python3.10/site-packages/setuptools/dist.py", line 1244, in run_command
    super().run_command(command)
  File "/home/user/miniconda3/envs/ipex/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/user/Documents/intel-extension-for-pytorch/scripts/intel-extension-for-pytorch/setup.py", line 783, in run
    _build_project(build_args, ipex_xpu_build_dir, my_env, use_ninja)
  File "/home/user/Documents/intel-extension-for-pytorch/scripts/intel-extension-for-pytorch/setup.py", line 563, in _build_project
    check_call(["make"] + build_args, cwd=build_dir, env=build_env)
  File "/home/user/miniconda3/envs/ipex/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-j', '8', 'install']' returned non-zero exit status 2.
```

### Versions

```
Collecting environment information...
PyTorch version: 2.0.0a0+gite9ebda2
PyTorch CXX11 ABI: Yes
IPEX version: 2.0.110+git320f4da
IPEX commit: 320f4da8
Build type: Release

OS: Ubuntu 22.04.2 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
Clang version: N/A
IGC version: 2023.2.0 (2023.2.0.20230622)
CMake version: version 3.26.4
Libc version: glibc-2.35

Python version: 3.10.12 (main, Jul  5 2023, 18:54:27) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.19.0-46-generic-x86_64-with-glibc2.35
Is XPU available: False
DPCPP runtime version: 2023.2.0
MKL version: 2023.2.0
GPU models and configuration:

Intel OpenCL ICD version: 22.14.22890-1
Level Zero version: N/A

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   39 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          8
On-line CPU(s) list:             0-7
Vendor ID:                       GenuineIntel
Model name:                      11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
CPU family:                      6
Model:                           140
Thread(s) per core:              2
Core(s) per socket:              4
Socket(s):                       1
Stepping:                        1
CPU max MHz:                     4200.0000
CPU min MHz:                     400.0000
BogoMIPS:                        4838.40
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l2 invpcid_single cdp_l2 ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves split_lock_detect dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp hwp_pkg_req avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq rdpid movdiri movdir64b fsrm avx512_vp2intersect md_clear ibt flush_l1d arch_capabilities
Virtualization:                  VT-x
L1d cache:                       192 KiB (4 instances)
L1i cache:                       128 KiB (4 instances)
L2 cache:                        5 MiB (4 instances)
L3 cache:                        8 MiB (1 instance)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-7
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] intel-extension-for-pytorch==2.0.110+git320f4da
[pip3] numpy==1.25.1
[pip3] torch==2.0.0a0+gite9ebda2
[pip3] torchaudio==2.0.2+31de77d
[pip3] torchvision==0.15.2a0+fa99a53
[conda] intel-extension-for-pytorch 2.0.110+git320f4da          pypi_0    pypi
[conda] numpy                     1.25.1                   pypi_0    pypi
[conda] torch                     2.0.0a0+gite9ebda2          pypi_0    pypi
[conda] torchaudio                2.0.2+31de77d            pypi_0    pypi
[conda] torchvision               0.15.2a0+fa99a53          pypi_0    pypi
```

**Comment by jingxu10** [comment]
Does it work without AOT text?
i.e. `bash compile_bundle.sh /opt/intel/oneapi/compiler/2023.2.0/ /opt/intel/oneapi/mkl/2023.2.0/`
Also, driver packages don't seem to be correct. Which version of driver are you using? level zero is required, but seems to be not installed.
```
Intel OpenCL ICD version: 22.14.22890-1
Level Zero version: N/A
```

**Comment by kyflores** [comment]
Ah, I neglected to source the various `vars.sh` before running collect env. I updated my comment, but my Level Zero version is still empty. My installation came from the [`intel-basekit` package](https://www.intel.com/content/www/us/en/developer/tools/oneapi/base-toolkit-download.html?operatingsystem=linux&distributions=aptpackagemanager), which

Are the instructions on [this](https://dgpu-docs.intel.com/driver/client/overview.html) page correct for getting a driver distribution that will build IPEX?

I'll reinstall and try a fresh build again, thanks for pointing that out.

**Comment by kyflores** [comment]
Ok, after installing the client driver from the second link the build completes, both with and without AOT.

```
PyTorch version: 2.0.0a0+gite9ebda2
PyTorch CXX11 ABI: Yes
IPEX version: 2.0.110+git320f4da
IPEX commit: 320f4da8
Build type: Release

OS: Ubuntu 22.04.2 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
Clang version: 14.0.0-1ubuntu1
IGC version: 2023.2.0 (2023.2.0.20230622)
CMake version: version 3.27.0
Libc version: glibc-2.35

Python version: 3.10.12 (main, Jul  5 2023, 18:54:27) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.19.0-46-generic-x86_64-with-glibc2.35
Is XPU available: False
DPCPP runtime version: 2023.2.0
MKL version: 2023.2.0
GPU models and configuration:

Intel OpenCL ICD version: 23.17.26241.33-647~22.04
Level Zero version: 1.3.26241.33-647~22.04
```

I can import IPEX without errors but xpu is not identified. Tried this with both the AOT and no-AOT builds.
```
>>> import torch
>>> import intel_extension_for_pytorch as ipex
>>> torch.xpu.device_count()
0
>>> a = torch.randn(1)
>>> a.to('xpu')
Segmentation fault (core dumped)
```

Are there some debug switches or envars I could enable to show more useful info on this? Thanks for answering questions wrt IGPU even though it's not really a supported setup.

**Comment by jingxu10** [comment]
Thanks for updating the info.
You might need to try adding your user into render and reactivate the env by logging out and in or rebooting the system.
https://dgpu-docs.intel.com/driver/installation.html#configuring-render-group-membership

**Comment by kyflores** [comment]
Yup, thanks, adding to `render` was it. I had added myself to `video` instead for some reason.

Closing this as the problems were just a result of misconfiguration, but here's a summary for future readers of what I did.

1. [Install client IGPU packages](https://dgpu-docs.intel.com/driver/client/overview.html)
2. Add user to the `render` group. In my case this group already existed so `sudo usermod -aG render $USER`
3. [Install oneapi base toolkit](https://www.intel.com/content/www/us/en/developer/tools/oneapi/base-toolkit-download.html?operatingsystem=linux&distributions=aptpackagemanager)
4. Create a fresh python environment and activate it.
5. `source /opt/intel/oneapi/setvars.sh`
6. Clone `intel-extension-for-pytorch`, checkout `xpu-master`, and build with ` bash scripts/compile_bundle.sh /opt/intel/oneapi/compiler/2023.2.0/ /opt/intel/oneapi/mkl/2023.2.0/ Gen12LP`, replacing `Gen12LP` for the [desired IGPU configuration](https://www.intel.com/content/www/us/en/docs/dpcpp-cpp-compiler/developer-guide-reference/2023-0/ahead-of-time-compilation.html)

**Comment by dino21official** [comment]
Excuse me, I have a question. I am using intel iris xe graphics and I don't know what to install in step 1 and 3 of this procedure, please let me know!

1.[Install client IGPU packages](https://dgpu-docs.intel.com/driver/client/overview.html)
2.Add user to the render group. In my case this group already existed so sudo usermod -aG render $USER & reboot.
3.[Install oneapi base toolkit](https://www.intel.com/content/www/us/en/developer/tools/oneapi/base-toolkit-download.html?operatingsystem=linux&distributions=aptpackagemanager)
Create a fresh python environment and activate it.
Optionally source /opt/intel/oneapi/setvars.sh and run the collect_env.py script check installation
Clone intel-extension-for-pytorch, checkout xpu-master, and build with  bash scripts/compile_bundle.sh /opt/intel/oneapi/compiler/2023.2.0/ /opt/intel/oneapi/mkl/2023.2.0/ Gen12LP, replacing Gen12LP for the [desired IGPU configuration](https://www.intel.com/content/www/us/en/docs/dpcpp-cpp-compiler/developer-guide-reference/2023-0/ahead-of-time-compilation.html)
