### ISSUE TITLE
IPEX xpu wheel files for windows using the wrong version of Pytorch?  Also no torchvision

### ISSUE THREAD

**Issue by Mindset-Official** [intel/intel-extension-for-pytorch#398]
### Describe the issue

python -m pip install torch==2.0.0a0 intel_extension_for_pytorch==2.0.110+gitba7f6c1 -f https://developer.intel.com/ipex-whl-stable-xpu

wheel files seem to include torch 2.0.0a0 but notes say that xpu is only available for torch 2.0.1a0

Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> import intel_extension_for_pytorch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\mymin\AppData\Local\Programs\Python\Python310\lib\site-packages\intel_extension_for_pytorch\__init__.py", line 89, in <module>
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\mymin\AppData\Local\Programs\Python\Python310\lib\site-packages\intel_extension_for_pytorch\bin\intel-ext-pt-gpu.dll" or one of its dependencies.
>>> torch.xpu.is_available()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'torch' has no attribute 'xpu'

Also there seems to be no version of torchvision for windows?  Not sure if this is a mistake or just part of the expiremental nature?  as is xpu is not detected and doesn't work on windows so it defaults to cpu still.

**Comment by jingxu10** [comment]
Because of the experimental nature, the pytorch wheel shipped is 2.0.1 code base, but didn't get version updated in its `version.txt` file. `torchvision` wheels are not available at this moment as well.

@min-jean-cho could you check the error above?
```
OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\mymin\AppData\Local\Programs\Python\Python310\lib\site-packages\intel_extension_for_pytorch\bin\intel-ext-pt-gpu.dll" or one of its dependencies.
```

**Comment by min-jean-cho** [comment]
Thanks @Mindset-Official for trying out. Could you please double check if you have activated oneAPI environment, `call "{YOUR_PATH_TO_ONEAPI}\setvars.bat"`  (e.g., `call "C:\Program Files (x86)\Intel\oneAPI\setvars.bat"`)?

**Comment by Mindset-Official** [comment]
> 

Okay, thanks. I was able to get it to run by deleting python and installing miniconda as default, I then ran everything in oneapi environment and 

Python 3.10.12 | packaged by Anaconda, Inc. | (main, Jul  5 2023, 19:01:18) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> import intel_extension_for_pytorch
>>> torch.xpu.is_available()
True
>>>

appreciate the help and response.  I will give it a shot and see how everything works in windows.

**Comment by min-jean-cho** [comment]
Glad to hear that! Let us know if any other questions.

**Comment by Nuullll** [comment]
Since Intel hasn't released a corresponding `torchvision` wheel for windows, the [SD Web UI](https://github.com/vladmandic/automatic) tries to install the latest `torchvision == 0.15.2`, which requires `torch == 2.0.1`. So `pip install torchvision` will uninstall the intel torch because of incompatible version and install `torch == 2.0.1` instead. Then `intel_extension_for_pytorch` bails out because of wrong dll version from `torch 2.0.1`.

I have to hack `torchvision-0.15.2.dist-info/METADATA` in the python site-packages to force it compatible with `torch == 2.0.0a0`.

```diff
Metadata-Version: 2.1
Name: torchvision
Version: 0.15.1
Summary: image and video datasets and models for torch deep learning
Home-page: https://github.com/pytorch/vision
Author: PyTorch Core Team
Author-email: soumith@pytorch.org
License: BSD
Requires-Python: >=3.8
License-File: LICENSE
Requires-Dist: numpy
Requires-Dist: requests
+ Requires-Dist: torch (==2.0.0a0)
- Requires-Dist: torch (==2.0.0)
Requires-Dist: pillow (!=8.3.*,>=5.3.0)
Provides-Extra: scipy
Requires-Dist: scipy ; extra == 'scipy'
```

**Comment by Nuullll** [comment]
So we really need an intel `torchvision` wheel for windows. Is that planned in the recent future?

**Comment by Nuullll** [comment]
Thanks @Mindset-Official. [torchvision-0.15.2a0+cxx11.abi-cp310-cp310-linux_x86_64.whl](https://intel-extension-for-pytorch.s3.amazonaws.com/ipex_stable/xpu/torchvision-0.15.2a0%2Bcxx11.abi-cp310-cp310-linux_x86_64.whl) seems to be a linux wheel, I doubt it would work as expected on native windows. Anyway I'd give it a try.

**Comment by charygu** [comment]
> > 
> 
> Okay, thanks. I was able to get it to run by deleting python and installing miniconda as default, I then ran everything in oneapi environment and
> 
> Python 3.10.12 | packaged by Anaconda, Inc. | (main, Jul 5 2023, 19:01:18) [MSC v.1916 64 bit (AMD64)] on win32 Type "help", "copyright", "credits" or "license" for more information.
> 
> > > > import torch
> > > > import intel_extension_for_pytorch
> > > > torch.xpu.is_available()
> > > > True
> 
> appreciate the help and response. I will give it a shot and see how everything works in windows.

Hi, Mindset-Official, Could you tell me how you fix that issue?

**Comment by Mindset-Official** [comment]
> > > 
> > 
> > 
> > Okay, thanks. I was able to get it to run by deleting python and installing miniconda as default, I then ran everything in oneapi environment and
> > Python 3.10.12 | packaged by Anaconda, Inc. | (main, Jul 5 2023, 19:01:18) [MSC v.1916 64 bit (AMD64)] on win32 Type "help", "copyright", "credits" or "license" for more information.
> > > > > import torch
> > > > > import intel_extension_for_pytorch
> > > > > torch.xpu.is_available()
> > > > > True
> > 
> > 
> > appreciate the help and response. I will give it a shot and see how everything works in windows.
> 
> Hi, Mindset-Official, Could you tell me how you fix that issue? Did you get this fixed on native Windows?

Yeah, what I did in that post fixed it.  You can probably run it without miniconda but I left it as is.  Definitely make sure to run the environment and call those variables every time you run.

**Comment by charygu** [comment]
> > > > 
> > > 
> > > 
> > > Okay, thanks. I was able to get it to run by deleting python and installing miniconda as default, I then ran everything in oneapi environment and
> > > Python 3.10.12 | packaged by Anaconda, Inc. | (main, Jul 5 2023, 19:01:18) [MSC v.1916 64 bit (AMD64)] on win32 Type "help", "copyright", "credits" or "license" for more information.
> > > > > > import torch
> > > > > > import intel_extension_for_pytorch
> > > > > > torch.xpu.is_available()
> > > > > > True
> > > 
> > > 
> > > appreciate the help and response. I will give it a shot and see how everything works in windows.
> > 
> > 
> > Hi, Mindset-Official, Could you tell me how you fix that issue? Did you get this fixed on native Windows?
> 
> Yeah, what I did in that post fixed it. You can probably run it without miniconda but I left it as is. Definitely make sure to run the environment and call those variables every time you run.

I found the solution finally. Thank you very much.

**Comment by charygu** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > Okay, thanks. I was able to get it to run by deleting python and installing miniconda as default, I then ran everything in oneapi environment and
> > > > > Python 3.10.12 | packaged by Anaconda, Inc. | (main, Jul 5 2023, 19:01:18) [MSC v.1916 64 bit (AMD64)] on win32 Type "help", "copyright", "credits" or "license" for more information.
> > > > > > > > import torch
> > > > > > > > import intel_extension_for_pytorch
> > > > > > > > torch.xpu.is_available()
> > > > > > > > True
> > > > > 
> > > > > 
> > > > > appreciate the help and response. I will give it a shot and see how everything works in windows.
> > > > 
> > > > 
> > > > Hi, Mindset-Official, Could you tell me how you fix that issue? Did you get this fixed on native Windows?
> > > 
> > > 
> > > Yeah, what I did in that post fixed it. You can probably run it without miniconda but I left it as is. Definitely make sure to run the environment and call those variables every time you run.
> > 
> > 
> > I found the solution finally. Thank you very much.
> 
> Hi @charygu, could you share your solution? It is killing me. Thanks!

I didn't stick to oneAPI of windows installer. Instead, I installed it by using pip in your conda env. Then you may get the 2023.2.0 version which includes the dependencies "intel-ext-pt-gpu.dll" needs.

**Comment by makejiang** [comment]
> > > > > > > 
> > > > > > 
> > > > > > 
> > > > > > Okay, thanks. I was able to get it to run by deleting python and installing miniconda as default, I then ran everything in oneapi environment and
> > > > > > Python 3.10.12 | packaged by Anaconda, Inc. | (main, Jul 5 2023, 19:01:18) [MSC v.1916 64 bit (AMD64)] on win32 Type "help", "copyright", "credits" or "license" for more information.
> > > > > > > > > import torch
> > > > > > > > > import intel_extension_for_pytorch
> > > > > > > > > torch.xpu.is_available()
> > > > > > > > > True
> > > > > > 
> > > > > > 
> > > > > > appreciate the help and response. I will give it a shot and see how everything works in windows.
> > > > > 
> > > > > 
> > > > > Hi, Mindset-Official, Could you tell me how you fix that issue? Did you get this fixed on native Windows?
> > > > 
> > > > 
> > > > Yeah, what I did in that post fixed it. You can probably run it without miniconda but I left it as is. Definitely make sure to run the environment and call those variables every time you run.
> > > 
> > > 
> > > I found the solution finally. Thank you very much.
> > 
> > 
> > Hi @charygu, could you share your solution? It is killing me. Thanks!
> 
> I didn't stick to oneAPI of windows installer. Instead, I installed it by using conda in my conda env. Then you may get the 2023.2.0 version which includes the dependencies "intel-ext-pt-gpu.dll" needs.

Thanks charygu, 2023.2 works!

**Comment by Cyberavater** [comment]
Can anyone give or link me to a proper guide to use this on Windows?

**Comment by YimingLiu000** [comment]
Hi@charygu, could you tell me how to activate oneAPI in conda environment? I can use conda install the 2023.2.0 version, but don't know how to load it.

**Comment by karthika-ml** [comment]
Hi, here is an amazing blog that I found to configure the intel-ipex to your pytorch on a windows: https://christianjmills.com/posts/intel-pytorch-extension-tutorial/native-windows/
