### ISSUE TITLE
RuntimeError: The size of tensor a (32) must match the size of tensor b (33) at non-singleton dimension 3

### ISSUE THREAD

**Issue by jerin-scalers-ai** [intel/intel-extension-for-pytorch#403]
### Describe the issue

Getting runtime error while executing [run_generation.py](https://github.com/intel/intel-extension-for-pytorch/blob/v2.1.0.dev%2Bcpu.llm/examples/cpu/inference/python/llm/run_generation.py) with Llama-2-7b-chat model.

Python: 3.9  
intel-extension-for-pytorch:  2.1.0.dev0+cpu.llm   
transformers: 4.31.0
torch: 2.1.0.dev20230711+cpu

### Step to reproduce the issue

- Converted the llama-2-7b-chat model to using transformer conversion tool
- Cmd: python run_generation.py --benchmark -m converted-model/ --dtype bfloat16 --ipex --jit

### Issue

Namespace(model_id='converted-model/', device='cpu', dtype='bfloat16', input_tokens='32', max_new_tokens=32, prompt=None, greedy=False, ipex=True, jit=True, benchmark=True, lambada=False, dataset='lambada', accuracy_only=False, num_iter=100, num_warmup=10, batch_size=1, token_latency=False)
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:06<00:00,  3.45s/it]
/home/user/.pyenv/versions/3.9.17/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py:579: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if input_shape[-1] > 1:
/home/user/.pyenv/versions/3.9.17/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py:55: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if past_key_values_length > 0:
Traceback (most recent call last):
  File "/home/user/jerin/amd-epyc/benchmarks/hfnlp/hfnlp/ipex/run_generation.py", line 198, in <module>
    trace_model = torch.jit.trace(
  File "/home/user/.pyenv/versions/3.9.17/lib/python3.9/site-packages/intel_extension_for_pytorch/jit/_trace.py", line 69, in wrapper
    traced = f(*args, **kwargs)
  File "/home/user/.pyenv/versions/3.9.17/lib/python3.9/site-packages/torch/jit/_trace.py", line 795, in trace
    return trace_module(
  File "/home/user/.pyenv/versions/3.9.17/lib/python3.9/site-packages/torch/jit/_trace.py", line 1045, in trace_module
    module._c._create_method_from_trace_with_dict(
  File "/home/user/.pyenv/versions/3.9.17/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1522, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/user/.pyenv/versions/3.9.17/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1531, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/.pyenv/versions/3.9.17/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1512, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/user/.pyenv/versions/3.9.17/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 806, in forward
    outputs = self.model(
  File "/home/user/.pyenv/versions/3.9.17/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1522, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/user/.pyenv/versions/3.9.17/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1531, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/.pyenv/versions/3.9.17/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1512, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/user/.pyenv/versions/3.9.17/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 652, in forward
    attention_mask = self._prepare_decoder_attention_mask(
  File "/home/user/.pyenv/versions/3.9.17/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 593, in _prepare_decoder_attention_mask
    expanded_attn_mask if combined_attention_mask is None else expanded_attn_mask + combined_attention_mask
RuntimeError: The size of tensor a (32) must match the size of tensor b (33) at non-singleton dimension 3

**Comment by ZhaoqiongZ** [comment]
Hi @jerin-scalers-ai , thanks for trying out, I will look into it.

**Comment by ZhaoqiongZ** [comment]
Hi @jerin-scalers-ai , ipex llm release is now only support with transformers==4.28.1, would you downgrade your transformers version to run it?

**Comment by jerin-scalers-ai** [comment]
@ZhaoqiongZ Thank you for the solution. 
Downgrading transformers package to 4.28.1 resolved the issue.

The summary at the end of the benchmarking prints Average 2, P90 2 and P99 2. Is it token latency ?
 ---------- Summary: ----------
Inference latency: 6.697 sec.
First token average latency: 3.580 sec.
Average 2... latency: 0.098 sec.
P90 2... latency: 0.099 sec.
P99 2... latency: 0.101 sec.

**Comment by jingxu10** [comment]
average 2... latency: latency for generating tokens from the 2nd one.
P90 2... latency: average 90% of latencies for generating tokens from the 2nd one.
P99 2... latency: average 99% of latencies for generating tokens from the 2nd one.

**Comment by jerin-scalers-ai** [comment]
Thanks for the clarification.
