### ISSUE TITLE
Safetensor loading having a function overwritten by IPEX doesn't work

### ISSUE THREAD

**Issue by simonlui** [intel/intel-extension-for-pytorch#407]
### Describe the bug

I tried running [ComfyUI](https://github.com/comfyanonymous/ComfyUI), a third-party Stable Diffusion web interface with ipexrun through a Docker environment I made with `ipexrun xpu main.py` and I got this issue while it was trying to load the model through [safetensors](https://github.com/huggingface/safetensors)

```
!!! Exception during processing !!!
Traceback (most recent call last):
  File "/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/ComfyUI/nodes.py", line 446, in load_checkpoint
    out = comfy.sd.load_checkpoint_guess_config(ckpt_path, output_vae=True, output_clip=True, embedding_directory=folder_paths.get_folder_paths("embeddings"))
  File "/ComfyUI/comfy/sd.py", line 1180, in load_checkpoint_guess_config
    sd = utils.load_torch_file(ckpt_path)
  File "/ComfyUI/comfy/utils.py", line 11, in load_torch_file
    sd = safetensors.torch.load_file(ckpt, device=device.type)
  File "/deps/venv/lib/python3.10/site-packages/safetensors/torch.py", line 311, in load_file
    result[k] = f.get_tensor(k)
  File "/deps/venv/lib/python3.10/site-packages/intel_extension_for_pytorch/xpu/overrides.py", line 232, in new_api
    assert len(args) > 0 and isinstance(
AssertionError: Current api <built-in method asarray of type object at 0x7fa730e2c500> got non-Tensor for the 1st arguement
```
Unfortunately, I can't reproduce it as just running the safetensors.torch.load_file() line cleanly in an example like below won't reproduce it so I'm not sure if you need to load the file differently through the project like I stated above.

```python
import torch
import intel_extension_for_pytorch as ipex
import safetensors.torch

def load_torch_file(ckpt, safe_load=False, device=None):
    if device is None:
        device = torch.device("cpu")
    if ckpt.lower().endswith(".safetensors"):
        sd = safetensors.torch.load_file(ckpt, device=device.type)
    else:
        if safe_load:
            if not 'weights_only' in torch.load.__code__.co_varnames:
                print("Warning torch.load doesn't support weights_only on this pytorch version, loading unsafely.")
                safe_load = False
        if safe_load:
            pl_sd = torch.load(ckpt, map_location=device, weights_only=True)
        else:
            pl_sd = torch.load(ckpt, map_location=device, pickle_module=comfy.checkpoint_pickle)
        if "global_step" in pl_sd:
            print(f"Global Step: {pl_sd['global_step']}")
        if "state_dict" in pl_sd:
            sd = pl_sd["state_dict"]
        else:
            sd = pl_sd
    return sd

# Try loading SD 1.5, for example
file = load_torch_file("v1-5-pruned-emaonly.safetensors")
```
It looks like it's a function override IPEX is doing that has gone wrong or is detecting wrong here but I dunno what is triggering it. Also, please fix the typo in the error message as "arguement" is spelled wrong here.

### Versions

```
Collecting environment information...
PyTorch version: 2.0.1a0+cxx11.abi
PyTorch CXX11 ABI: Yes
IPEX version: 2.0.110+xpu
IPEX commit: ba7f6c127
Build type: Release

OS: Ubuntu 22.04.2 LTS (x86_64)
GCC version: N/A
Clang version: N/A
IGC version: N/A
CMake version: version 3.27.2
Libc version: glibc-2.35

Python version: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-6.5.0-rc2+-x86_64-with-glibc2.35
Is XPU available: True
DPCPP runtime version: N/A
MKL version: N/A
GPU models and configuration: 
[0] _DeviceProperties(name='Intel(R) Arc(TM) A770 Graphics', platform_name='Intel(R) Level-Zero', dev_type='gpu, support_fp64=0, total_memory=16288MB, max_compute_units=512, gpu_eu_count=512)
Intel OpenCL ICD version: 23.17.26241.33-647~22.04
Level Zero version: 1.3.26241.33-647~22.04

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   48 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          32
On-line CPU(s) list:             0-31
Vendor ID:                       AuthenticAMD
Model name:                      AMD Ryzen 9 5950X 16-Core Processor
CPU family:                      25
Model:                           33
Thread(s) per core:              2
Core(s) per socket:              16
Socket(s):                       1
Stepping:                        0
Frequency boost:                 enabled
CPU max MHz:                     5083.3979
CPU min MHz:                     2200.0000
BogoMIPS:                        6799.48
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca fsrm
Virtualization:                  AMD-V
L1d cache:                       512 KiB (16 instances)
L1i cache:                       512 KiB (16 instances)
L2 cache:                        8 MiB (16 instances)
L3 cache:                        64 MiB (2 instances)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-31
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP always-on, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] intel-extension-for-pytorch==2.0.110+xpu
[pip3] numpy==1.24.4
[pip3] open-clip-torch==2.20.0
[pip3] pytorch-lightning==1.9.4
[pip3] torch==2.0.1a0+cxx11.abi
[pip3] torchdiffeq==0.2.3
[pip3] torchmetrics==1.0.3
[pip3] torchsde==0.2.5
[pip3] torchvision==0.15.2a0+cxx11.abi
[conda] N/A
```

**Comment by vishnumadhu365** [comment]
@simonlui Thanks for reporting. We will look into reproducing the error. Meanwhile, would you have a dockerfile which could potentially run into this error when built and ran ?

**Comment by vishnumadhu365** [comment]
Thanks @simonlui , this helps a ton!

**Comment by vishnumadhu365** [comment]
Hi @simonlui , finally I could get the issue reproduced for the ipexrun scenario. 
Meanwhile, in my tests I observed that even without setting the argument UseIPEX=true, the SD model(both ckpt and safetensor) runs well on the XPU. Is there some specific reason for using the ipexrun launcher ?

**Comment by simonlui** [comment]
Hi @vishnumadhu365, the purpose was to test it even though there isn't much that the XPU `ipexrun` does at this time. I imagine there will be future functionality added like where the CPU `ipexrun` is at the moment so I wanted to have it working in my Docker image. I was surprised what little modification the current launcher does isn't working. Is the XPU `ipexrun` still in beta or not really supported at the moment?

**Comment by vishnumadhu365** [comment]
Ok, got it. This is a valid issue and the error is coming from the explicit fp64 to fp32 override, will report back once we have a fix for this. That's right, ipexrun for xpu doesn't do much today.  For now, if you still want to keep ipexrun in your docker, you could do so without the flag '--convert-fp64-to-fp32'.
Also, thanks for reporting the "arguement" typo, will get that addressed as well.

**Comment by vishnumadhu365** [comment]
@simonlui this issue with ipexrun had been fix and would be made available in the upcoming release of IPEX XPU. Closing this issue for now.
