### ISSUE TITLE
Failed running GPT-J int8 benchmark

### ISSUE THREAD

**Issue by RenyanDiao** [intel/intel-extension-for-pytorch#437]
### Describe the bug

MODEL_ID="/models/models--EleutherAI--gpt-j-6b"
python run_gpt-j_int8.py -m ${MODEL_ID} --quantized-model-path "./saved_results_gptj/best_model.pt" --benchmark --jit \
--token-latency --greedy --num-iter 10 --batch-size 1 --max-new-tokens 32 --num-warmup 3

# with --int8-bf16-mixed
Traceback (most recent call last):
  File "/dry/intel-extension-for-pytorch/examples/cpu/inference/python/llm/run_gpt-j_int8.py", line 442, in <module>
    output = user_model.generate(input_ids, **generate_kwargs)
  File "/opt/conda/envs/llm/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/envs/llm/lib/python3.9/site-packages/transformers/generation/utils.py", line 1538, in generate
    return self.greedy_search(
  File "/opt/conda/envs/llm/lib/python3.9/site-packages/intel_extension_for_pytorch/cpu/transformers/generation.py", line 796, in _greedy_search
    outputs = self.trace_graph(**model_inputs)
  File "/opt/conda/envs/llm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1519, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/envs/llm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1528, in _call_impl
    return forward_call(*args, **kwargs)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/intel_extension_for_pytorch/quantization/_quantize_utils/___torch_mangle_2671.py", line 223, in forward
    _173 = [int(torch.alias(ret35)), int(torch.alias(ret36)), 4096]
    ret37 = torch.view(_172, _173)
    ret38 = torch.quantize_per_tensor(torch.alias(ret37), 0.032824374735355377, 152, 13)
            ~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    ret39 = torch.dequantize(torch.alias(ret38))
    ret40 = torch.linear(torch.alias(ret39), torch.dequantize(CONSTANTS.c8))

Traceback of TorchScript, original code (most recent call last):
/opt/conda/envs/llm/lib/python3.9/site-packages/torch/_tensor.py(1386): __torch_function__
/opt/conda/envs/llm/lib/python3.9/site-packages/intel_extension_for_pytorch/quantization/_quantize_utils.py(590): __torch_function__
/opt/conda/envs/llm/lib/python3.9/site-packages/intel_extension_for_pytorch/quantization/_quantization_state_utils.py(453): iterate_and_apply_convert
/opt/conda/envs/llm/lib/python3.9/site-packages/intel_extension_for_pytorch/quantization/_quantization_state_utils.py(364): iterate_and_apply_convert
/opt/conda/envs/llm/lib/python3.9/site-packages/intel_extension_for_pytorch/quantization/_quantization_state.py(398): op_convert_before_hook
/opt/conda/envs/llm/lib/python3.9/site-packages/intel_extension_for_pytorch/quantization/_quantize_utils.py(694): _patched_module_call
/opt/conda/envs/llm/lib/python3.9/site-packages/intel_extension_for_pytorch/cpu/transformers/attentions.py(464): forward
/opt/conda/envs/llm/lib/python3.9/site-packages/torch/nn/modules/module.py(1509): _slow_forward
/opt/conda/envs/llm/lib/python3.9/site-packages/torch/nn/modules/module.py(1528): _call_impl
/opt/conda/envs/llm/lib/python3.9/site-packages/torch/nn/modules/module.py(1519): _wrapped_call_impl
/opt/conda/envs/llm/lib/python3.9/site-packages/intel_extension_for_pytorch/quantization/_quantize_utils.py(721): _patched_module_call
/opt/conda/envs/llm/lib/python3.9/site-packages/transformers/models/gptj/modeling_gptj.py(309): forward
/opt/conda/envs/llm/lib/python3.9/site-packages/torch/nn/modules/module.py(1509): _slow_forward
/opt/conda/envs/llm/lib/python3.9/site-packages/torch/nn/modules/module.py(1528): _call_impl
/opt/conda/envs/llm/lib/python3.9/site-packages/torch/nn/modules/module.py(1519): _wrapped_call_impl
/opt/conda/envs/llm/lib/python3.9/site-packages/intel_extension_for_pytorch/quantization/_quantize_utils.py(721): _patched_module_call
/opt/conda/envs/llm/lib/python3.9/site-packages/intel_extension_for_pytorch/cpu/transformers/models.py(165): GPTJModel_forward
/opt/conda/envs/llm/lib/python3.9/site-packages/torch/nn/modules/module.py(1509): _slow_forward
/opt/conda/envs/llm/lib/python3.9/site-packages/torch/nn/modules/module.py(1528): _call_impl
/opt/conda/envs/llm/lib/python3.9/site-packages/torch/nn/modules/module.py(1519): _wrapped_call_impl
/opt/conda/envs/llm/lib/python3.9/site-packages/intel_extension_for_pytorch/quantization/_quantize_utils.py(721): _patched_module_call
/opt/conda/envs/llm/lib/python3.9/site-packages/intel_extension_for_pytorch/cpu/transformers/models.py(1204): GPTJForCausalLM_forward
/opt/conda/envs/llm/lib/python3.9/site-packages/torch/nn/modules/module.py(1509): _slow_forward
/opt/conda/envs/llm/lib/python3.9/site-packages/torch/nn/modules/module.py(1528): _call_impl
/opt/conda/envs/llm/lib/python3.9/site-packages/torch/nn/modules/module.py(1519): _wrapped_call_impl
/opt/conda/envs/llm/lib/python3.9/site-packages/intel_extension_for_pytorch/quantization/_quantize_utils.py(721): _patched_module_call
/opt/conda/envs/llm/lib/python3.9/site-packages/intel_extension_for_pytorch/quantization/_quantize_utils.py(746): __call__
/opt/conda/envs/llm/lib/python3.9/site-packages/torch/jit/_trace.py(1070): trace_module
/opt/conda/envs/llm/lib/python3.9/site-packages/torch/jit/_trace.py(803): trace
/opt/conda/envs/llm/lib/python3.9/site-packages/intel_extension_for_pytorch/jit/_trace.py(69): wrapper
/opt/conda/envs/llm/lib/python3.9/site-packages/neural_compressor/adaptor/pytorch.py(2644): quantize
/opt/conda/envs/llm/lib/python3.9/site-packages/neural_compressor/utils/utility.py(305): fi
/opt/conda/envs/llm/lib/python3.9/site-packages/neural_compressor/strategy/strategy.py(425): traverse
/opt/conda/envs/llm/lib/python3.9/site-packages/neural_compressor/strategy/auto.py(108): traverse
/opt/conda/envs/llm/lib/python3.9/site-packages/neural_compressor/quantization.py(215): fit
/dry/intel-extension-for-pytorch/examples/cpu/inference/python/llm/run_gpt-j_int8.py(322): <module>
RuntimeError: Quantize only works on Float Tensor, got BFloat16

# without --int8-bf16-mixed
Traceback (most recent call last):
  File "/dry/intel-extension-for-pytorch/examples/cpu/inference/python/llm/run_gpt-j_int8.py", line 442, in <module>
    output = user_model.generate(input_ids, **generate_kwargs)
  File "/opt/conda/envs/llm/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/envs/llm/lib/python3.9/site-packages/transformers/generation/utils.py", line 1538, in generate
    return self.greedy_search(
  File "/opt/conda/envs/llm/lib/python3.9/site-packages/intel_extension_for_pytorch/cpu/transformers/generation.py", line 802, in _greedy_search
    outputs = self(
  File "/opt/conda/envs/llm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1519, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/envs/llm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1528, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/envs/llm/lib/python3.9/site-packages/intel_extension_for_pytorch/cpu/transformers/models.py", line 1204, in GPTJForCausalLM_forward
    transformer_outputs = self.transformer(
  File "/opt/conda/envs/llm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1519, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/envs/llm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1528, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/envs/llm/lib/python3.9/site-packages/intel_extension_for_pytorch/cpu/transformers/models.py", line 165, in GPTJModel_forward
    outputs = block(
  File "/opt/conda/envs/llm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1519, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/envs/llm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1528, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/envs/llm/lib/python3.9/site-packages/transformers/models/gptj/modeling_gptj.py", line 309, in forward
    attn_outputs = self.attn(
  File "/opt/conda/envs/llm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1519, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/envs/llm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1528, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/envs/llm/lib/python3.9/site-packages/intel_extension_for_pytorch/cpu/transformers/attentions.py", line 399, in forward
    torch.ops.torch_ipex.rotary_position_embedding(
  File "/opt/conda/envs/llm/lib/python3.9/site-packages/torch/_ops.py", line 742, in __call__
    return self._op(*args, **kwargs or {})
NotImplementedError: Could not run 'torch_ipex::rotary_position_embedding' with arguments from the 'Meta' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'torch_ipex::rotary_position_embedding' is only available for these backends: [CPU, BackendSelect, Python, FuncTorchDynamicLayerBackMode, Functionalize, Named, Conjugate, Negative, ZeroTensor, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradMPS, AutogradXPU, AutogradHPU, AutogradLazy, AutogradMeta, Tracer, AutocastCPU, AutocastCUDA, FuncTorchBatched, BatchedNestedTensor, FuncTorchVmapMode, Batched, VmapMode, FuncTorchGradWrapper, PythonTLSSnapshot, FuncTorchDynamicLayerFrontMode, PreDispatch, PythonDispatcher].

CPU: registered at /dry/intel-extension-for-pytorch/csrc/cpu/aten/RotaryPositionEmbedding.cpp:33 [kernel]
BackendSelect: fallthrough registered at ../aten/src/ATen/core/BackendSelectFallbackKernel.cpp:3 [backend fallback]
Python: registered at ../aten/src/ATen/core/PythonFallbackKernel.cpp:153 [backend fallback]
FuncTorchDynamicLayerBackMode: registered at ../aten/src/ATen/functorch/DynamicLayer.cpp:498 [backend fallback]
Functionalize: registered at ../aten/src/ATen/FunctionalizeFallbackKernel.cpp:302 [backend fallback]
Named: registered at ../aten/src/ATen/core/NamedRegistrations.cpp:7 [backend fallback]
Conjugate: registered at ../aten/src/ATen/ConjugateFallback.cpp:17 [backend fallback]
Negative: registered at ../aten/src/ATen/native/NegateFallback.cpp:19 [backend fallback]
ZeroTensor: registered at ../aten/src/ATen/ZeroTensorFallback.cpp:86 [backend fallback]
ADInplaceOrView: fallthrough registered at ../aten/src/ATen/core/VariableFallbackKernel.cpp:86 [backend fallback]
AutogradOther: registered at ../aten/src/ATen/core/VariableFallbackKernel.cpp:53 [backend fallback]
AutogradCPU: registered at ../aten/src/ATen/core/VariableFallbackKernel.cpp:57 [backend fallback]
AutogradCUDA: registered at ../aten/src/ATen/core/VariableFallbackKernel.cpp:65 [backend fallback]
AutogradXLA: registered at ../aten/src/ATen/core/VariableFallbackKernel.cpp:69 [backend fallback]
AutogradMPS: registered at ../aten/src/ATen/core/VariableFallbackKernel.cpp:77 [backend fallback]
AutogradXPU: registered at ../aten/src/ATen/core/VariableFallbackKernel.cpp:61 [backend fallback]
AutogradHPU: registered at ../aten/src/ATen/core/VariableFallbackKernel.cpp:90 [backend fallback]
AutogradLazy: registered at ../aten/src/ATen/core/VariableFallbackKernel.cpp:73 [backend fallback]
AutogradMeta: registered at ../aten/src/ATen/core/VariableFallbackKernel.cpp:81 [backend fallback]
Tracer: registered at ../torch/csrc/autograd/TraceTypeManual.cpp:297 [backend fallback]
AutocastCPU: fallthrough registered at ../aten/src/ATen/autocast_mode.cpp:380 [backend fallback]
AutocastCUDA: fallthrough registered at ../aten/src/ATen/autocast_mode.cpp:246 [backend fallback]
FuncTorchBatched: registered at ../aten/src/ATen/functorch/LegacyBatchingRegistrations.cpp:744 [backend fallback]
BatchedNestedTensor: registered at ../aten/src/ATen/functorch/LegacyBatchingRegistrations.cpp:772 [backend fallback]
FuncTorchVmapMode: fallthrough registered at ../aten/src/ATen/functorch/VmapModeRegistrations.cpp:28 [backend fallback]
Batched: registered at ../aten/src/ATen/LegacyBatchingRegistrations.cpp:1075 [backend fallback]
VmapMode: fallthrough registered at ../aten/src/ATen/VmapModeRegistrations.cpp:33 [backend fallback]
FuncTorchGradWrapper: registered at ../aten/src/ATen/functorch/TensorWrapper.cpp:203 [backend fallback]
PythonTLSSnapshot: registered at ../aten/src/ATen/core/PythonFallbackKernel.cpp:161 [backend fallback]
FuncTorchDynamicLayerFrontMode: registered at ../aten/src/ATen/functorch/DynamicLayer.cpp:494 [backend fallback]
PreDispatch: registered at ../aten/src/ATen/core/PythonFallbackKernel.cpp:165 [backend fallback]
PythonDispatcher: registered at ../aten/src/ATen/core/PythonFallbackKernel.cpp:157 [backend fallback]

### Versions

llm_feature_branch latest self compile
git clone --branch llm_feature_branch https://github.com/intel/intel-extension-for-pytorch.git
cd intel-extension-for-pytorch
git submodule sync && git submodule update --init --recursive
export DNNL_GRAPH_BUILD_COMPILER_BACKEND=1
export CXXFLAGS="${CXXFLAGS} -D__STDC_FORMAT_MACROS"
python setup.py install
cd ../

**Comment by jgong5** [comment]
@jianan-gu any thoughts?

**Comment by jianan-gu** [comment]
@RenyanDiao May I know the CMD that how you generate the quantization model?
To run with --int8-bf16-mixed, we need to generate the quantization model with --int8-bf16-mixed as well.
And using --int8 is the same, quantization and run with the same flag.
Thanks

**Comment by RenyanDiao** [comment]
> @RenyanDiao May I know the CMD that how you generate the quantization model? To run with --int8-bf16-mixed, we need to generate the quantization model with --int8-bf16-mixed as well. And using --int8 is the same, quantization and run with the same flag. Thanks

## GPT-J quantization
#MODEL_ID="EleutherAI/gpt-j-6b"
MODEL_ID="/models/models--EleutherAI--gpt-j-6b"
mkdir saved_results_gptj
python run_gpt-j_int8.py --ipex-smooth-quant --lambada --output-dir "saved_results_gptj" --jit --int8-bf16-mixed -m ${MODEL_ID}

## GPT-J int8 benchmark
MODEL_ID="/models/models--EleutherAI--gpt-j-6b"
python run_gpt-j_int8.py -m ${MODEL_ID} --quantized-model-path "./saved_results_gptj/best_model.pt" --benchmark --jit \
--token-latency --greedy --num-iter 10 --batch-size 1 --max-new-tokens 32 --num-warmup 3

**Comment by jianan-gu** [comment]
# About --ipex-smooth-quant usage:

## Case 1: use int8 mixed fp32 (--int8 is needed)
### Step a) quantization
python run_gpt-j_int8.py --ipex-smooth-quant --lambada --output-dir "saved_results_gptj_int8-fp32" --jit  -m ${MODEL_ID} **--int8**  

### Step b) benchmark

python run_gpt-j_int8.py -m ${MODEL_ID} --quantized-model-path "./saved_results_gptj_int8-fp32/best_model.pt" --benchmark --jit --token-latency  --num-iter 10 --batch-size 1 --max-new-tokens 32 --num-warmup 3 **--int8**  (default is beam search, use --greedy if beam size=1 )


##  Case 2: use int8 mixed bf16 (--int8-bf16-mixed is needed)
### Step a) quantization

python run_gpt-j_int8.py --ipex-smooth-quant --lambada --output-dir "./saved_results_gptj_int8-bf16" --jit  -m ${MODEL_ID}  **--int8-bf16-mixed**  (default is beam search, use --greedy if beam size=1 )


### Step b) benchmark
python run_gpt-j_int8.py -m ${MODEL_ID} --quantized-model-path "./saved_results_gptj_int8-bf16/best_model.pt" --benchmark --jit --token-latency  --num-iter 10 --batch-size 1 --max-new-tokens 32 --num-warmup 3 **--int8-bf16-mixed**  (default is beam search, use --greedy if beam size=1 )


##  Note： 

1. If run with greedy search, --greedy is needed both for step a) and b) above. Default is beam search with size 4 without --greedy.

**Comment by jianan-gu** [comment]
Based on above usage, back to the issues you met @RenyanDiao:

**with --int8-bf16-mixed:**
You need to use _--int8-bf16-mixed_ both in quantization and benchmark.
If you need to run with greedy search, use _--greedy_ both in quantization and benchmark.

**without --int8-bf16-mixed:**
It will use int8 mixed fp32, and _--int8_ is needed both in quantization and benchmark.
And again, if you need to run with greedy search, use _--greedy_ both in quantization and benchmark.
