### ISSUE TITLE
xpu Embedding layer will cause the xpu device to be lost on Windows

### ISSUE THREAD

**Issue by MeouSker77** [intel/intel-extension-for-pytorch#448]
### Describe the bug

Following code
```python
import torch
import intel_extension_for_pytorch as ipex

with torch.inference_mode():
    layer = torch.nn.Embedding(10, 10)
    i = torch.tensor([1])

    layer = layer.to('xpu')
    i = i.to('xpu')

    o = layer(i)
    torch.xpu.synchronize()
```
will throw an error `PI_ERROR_DEVICE_NOT_FOUND`

```
Traceback (most recent call last):
  File "C:\Users\arda\yishuo\transformer_int4\run3.py", line 13, in <module>
    torch.xpu.synchronize()
  File "C:\Users\arda\anaconda3\envs\yishuo-llm-test\lib\site-packages\intel_extension_for_pytorch\xpu\__init__.py", line 260, in synchronize
    return intel_extension_for_pytorch._C._synchronize(idx)
RuntimeError: Native API failed. Native API returns: -1 (PI_ERROR_DEVICE_NOT_FOUND) -1 (PI_ERROR_DEVICE_NOT_FOUND)
```

I conducted some experiments and came to the conclusion that the error is caused by the xpu Embedding layer.

### Versions

The output of `collect_env.py`:

```
Collecting environment information...
PyTorch version: 2.0.0a0+gitc6a572f
PyTorch CXX11 ABI: No
IPEX version: 2.0.110+gitba7f6c1
IPEX commit: ba7f6c127
Build type: Release

OS: Microsoft Windows 11 家庭中文版
GCC version: N/A
Clang version: N/A
IGC version: 2023.2.0 (2023.2.0.20230627)
CMake version: version 3.26.4-msvc4
Libc version: N/A

Python version: 3.9.18 | packaged by conda-forge | (main, Aug 30 2023, 03:40:31) [MSC v.1929 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22621-SP0
Is XPU available: True
DPCPP runtime version: N/A
MKL version: N/A
GPU models and configuration:
[0] _DeviceProperties(name='Intel(R) Arc(TM) A770 Graphics', platform_name='Intel(R) Level-Zero', dev_type='gpu, support_fp64=0, total_memory=15930MB, max_compute_units=512, gpu_eu_count=512)
Intel OpenCL ICD version: N/A
Level Zero version: N/A

CPU:
Architecture=9
CurrentClockSpeed=3200
DeviceID=CPU0
Family=207
L2CacheSize=14336
L2CacheSpeed=
Manufacturer=GenuineIntel
MaxClockSpeed=3200
Name=12th Gen Intel(R) Core(TM) i9-12900K
ProcessorType=3
Revision=

Versions of relevant libraries:
[pip3] intel-extension-for-pytorch==2.0.110+gitba7f6c1
[pip3] numpy==1.26.1
[pip3] torch==2.0.0a0+gitc6a572f
[conda] intel-extension-for-pytorch 2.0.110+gitba7f6c1          pypi_0    pypi
[conda] numpy                     1.26.1                   pypi_0    pypi
[conda] torch                     2.0.0a0+gitc6a572f          pypi_0    pypi
```

BTW, I used the following command to install torch and ipex
```
pip install torch==2.0.0a0 intel_extension_for_pytorch==2.0.110+gitba7f6c1 --extra-index-url https://developer.intel.com/ipex-whl-stable-xpu
```

and my gpu driver version is `31.0.101.4577`.

BTW, I have tried the same code with the same environment on another ARC A770 desktop, but this error didn't happen. The gpu driver version of that desktop is `31.0.101.4032`, maybe this error is related to gpu driver? (just a guess)

**Comment by kta-intel** [comment]
@jingxu10 I don't have access to a windows system to test. do we know the compatibility of `31.0.101.4577` driver?

**Comment by MeouSker77** [comment]
some update:

I have upgraded the gpu driver of both desktops to the latest `31.0.101.4887` version, this error appears on both desktops.
So I think this bug is indeed related to the gpu driver version. (`31.0.101.4577` and `31.0.101.4887` have this error, while `31.0.101.4032` does not.)

**Comment by MeouSker77** [comment]
close it since it has been solved with latest driver
