### ISSUE TITLE
When I build the intel-extension-for-pytorch , I got the error that it cannot find xpu compiler path from OS PATH

### ISSUE THREAD

**Issue by sxunix** [intel/intel-extension-for-pytorch#466]
### Describe the issue

**When I build the intel-extension-for-pytorch , I got the following error. How can I setup the OS Path for the xpu compliers?**
  File "C:\Users\tao\Downloads\ipex_bundle\intel-extension-for-pytorch\setup.py", line 431, in get_xpu_compliers
    raise RuntimeError("Failed to find compiler path from OS PATH")

**The details are as follows:**
Traceback (most recent call last):
  File "C:\Users\tao\Downloads\ipex_bundle\intel-extension-for-pytorch\setup.py", line 1104, in <module>
    setup(
  File "C:\Users\tao\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\tao\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
    return run_commands(dist)
  File "C:\Users\tao\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
    dist.run_commands()
  File "C:\Users\tao\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\dist.py", line 968, in run_commands
    self.run_command(cmd)
  File "C:\Users\tao\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\dist.py", line 1217, in run_command
    super().run_command(command)
  File "C:\Users\tao\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
    cmd_obj.run()
  File "C:\Users\tao\AppData\Local\Programs\Python\Python310\lib\site-packages\wheel\bdist_wheel.py", line 369, in run
    self.run_command("build")
  File "C:\Users\tao\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
    self.distribution.run_command(command)
  File "C:\Users\tao\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\dist.py", line 1217, in run_command
    super().run_command(command)
  File "C:\Users\tao\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
    cmd_obj.run()
  File "C:\Users\tao\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\command\build.py", line 132, in run
    self.run_command(cmd_name)
  File "C:\Users\tao\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
    self.distribution.run_command(command)
  File "C:\Users\tao\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\dist.py", line 1217, in run_command
    super().run_command(command)
  File "C:\Users\tao\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
    cmd_obj.run()
  File "C:\Users\tao\Downloads\ipex_bundle\intel-extension-for-pytorch\setup.py", line 1073, in run
    self.run_command("build_clib")
  File "C:\Users\tao\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
    self.distribution.run_command(command)
  File "C:\Users\tao\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\dist.py", line 1217, in run_command
    super().run_command(command)
  File "C:\Users\tao\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
    cmd_obj.run()
  File "C:\Users\tao\Downloads\ipex_bundle\intel-extension-for-pytorch\setup.py", line 687, in run
    gpu_cc, gpu_cxx = get_xpu_compliers()
  File "C:\Users\tao\Downloads\ipex_bundle\intel-extension-for-pytorch\setup.py", line 431, in get_xpu_compliers
    raise RuntimeError("Failed to find compiler path from OS PATH")
RuntimeError: Failed to find compiler path from OS PATH

**Comment by jingxu10** [comment]
@min-jean-cho

**Comment by kta-intel** [comment]
Hi, it looks like the path to the DPC++ Compiler is not being properly set (or `icx`/`icpx` are missing)

Please double check that the `icx` and `icpx` compilers are installed. they should be located under `<path to  DPC++ Compiler>\latest\bin\` and make sure that your script is calling `vars.bat` for the DPC++ Compiler

If you aren't already, I recommend using the [compile_bundle script](https://github.com/intel/intel-extension-for-pytorch/blob/xpu-main/scripts/compile_bundle.bat)
