### ISSUE TITLE
Crash in cpu_info.py when using german locales

### ISSUE THREAD

**Issue by daFritz84** [intel/intel-extension-for-pytorch#486]
Getting the current processor speed using cpu_info.py breaks when using german locales. For some reason, lscpu uses ',' and not a '.' as a separator which breaks string to float conversion in python.

https://github.com/intel/intel-extension-for-pytorch/blob/cb84a6e90d6366fa5d8825891533c30eda5accef/intel_extension_for_pytorch/cpu/launch/cpu_info.py#L91

**lscpu version:**
`
lscpu von util-linux 2.39.3
`

**locale output:**
> locale
LANG=de_AT.UTF-8
LC_CTYPE="de_AT.UTF-8"
LC_NUMERIC=de_AT.UTF-8
LC_TIME=de_AT.UTF-8
LC_COLLATE="de_AT.UTF-8"
LC_MONETARY=de_AT.UTF-8
LC_MESSAGES="de_AT.UTF-8"
LC_PAPER=de_AT.UTF-8
LC_NAME=de_AT.UTF-8
LC_ADDRESS=de_AT.UTF-8
LC_TELEPHONE=de_AT.UTF-8
LC_MEASUREMENT=de_AT.UTF-8
LC_IDENTIFICATION=de_AT.UTF-8
LC_ALL=

**Traceback:**
>Traceback (most recent call last):
  File "/home/sseifried/stable-diffusion-intel/venv/bin/ipexrun", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/sseifried/stable-diffusion-intel/venv/lib/python3.11/site-packages/intel_extension_for_pytorch/launcher.py", line 85, in main
    parser, cpu_parser, xpu_parser = init_parser()
                                     ^^^^^^^^^^^^^
  File "/home/sseifried/stable-diffusion-intel/venv/lib/python3.11/site-packages/intel_extension_for_pytorch/launcher.py", line 67, in init_parser
    cpu_init_parser(cpu_parser)
  File "/home/sseifried/stable-diffusion-intel/venv/lib/python3.11/site-packages/intel_extension_for_pytorch/cpu/launch/launch.py", line 383, in init_parser
    launcher_distributed = DistributedTrainingLauncher()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sseifried/stable-diffusion-intel/venv/lib/python3.11/site-packages/intel_extension_for_pytorch/cpu/launch/launcher_base.py", line 14, in __init__
    self.cpuinfo = CPUPoolList(self.logger, lscpu_txt)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sseifried/stable-diffusion-intel/venv/lib/python3.11/site-packages/intel_extension_for_pytorch/cpu/launch/cpu_info.py", line 183, in __init__
    self.pool_all.append(CoreInfo(t, headers))
                         ^^^^^^^^^^^^^^^^^^^^
  File "/home/sseifried/stable-diffusion-intel/venv/lib/python3.11/site-packages/intel_extension_for_pytorch/cpu/launch/cpu_info.py", line 79, in __init__
    self.parse_raw(lscpu_txt, headers)
  File "/home/sseifried/stable-diffusion-intel/venv/lib/python3.11/site-packages/intel_extension_for_pytorch/cpu/launch/cpu_info.py", line 91, in parse_raw
    self.maxmhz = float(cols[headers["maxmhz"]])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: '4000,0000'

**Workaround:**
Temporarily override localisation for your current shell
`
export LC_ALL=C
`

**Comment by jingxu10** [comment]
will update the script. Thanks for sharing the workaround.

**Comment by jingxu10** [comment]
May I know the command you used for reproducing this issue?

**Comment by daFritz84** [comment]
@jingxu10 I used [vladmandic/automatic](https://github.com/vladmandic/automatic) fork of AUTOMATIC1111/stable-diffusion-webui

Didn't bother to create a minimal example of the issue yet. Do you need one for verifying the fix later on?

**Comment by jingxu10** [comment]
fixed, please check the latest main branch.

**Comment by jingxu10** [comment]
https://github.com/intel/intel-extension-for-pytorch/blob/main/intel_extension_for_pytorch/cpu/launch/cpu_info.py#L150

**Comment by daFritz84** [comment]
LGTM, Thanks for the effort
