### ISSUE TITLE
Allocation of greater than 4GB not possible

### ISSUE THREAD

**Issue by ElliottDyson** [intel/intel-extension-for-pytorch#492]
### Describe the bug

Installed as per the linux installation guide (do not have the technical knowledge required for custom compiling):
python -m pip install torch==2.1.0a0 torchvision==0.16.0a0 torchaudio==2.1.0a0 intel-extension-for-pytorch==2.1.10+xpu --extra-index-url https://pytorch-extension.intel.com/release-whl/stable/xpu/us/

I have the following error when attempting to train models with a larger architecture and batch size than 4GB:
RuntimeError: Current platform can NOT allocate memory block with size larger than 4GB! Tried to allocate 7.62 GiB (GPU  0; 15.11 GiB total capacity; 334.79 MiB already allocated; 474.00 MiB reserved in total by PyTorch)

### Versions

The program instructed to use for versions failed:
Collecting environment information...
Traceback (most recent call last):
  File "/home/elliott/Downloads/Multimodal_Transformer_Edition2 - Knock Test/collect_env.py", line 515, in <module>
    main()
  File "/home/elliott/Downloads/Multimodal_Transformer_Edition2 - Knock Test/collect_env.py", line 510, in main
    output = get_pretty_env_info()
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/elliott/Downloads/Multimodal_Transformer_Edition2 - Knock Test/collect_env.py", line 505, in get_pretty_env_info
    return pretty_str(get_env_info())
                      ^^^^^^^^^^^^^^
  File "/home/elliott/Downloads/Multimodal_Transformer_Edition2 - Knock Test/collect_env.py", line 343, in get_env_info
    pip_version, pip_list_output = get_pip_packages(run_lambda)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/elliott/Downloads/Multimodal_Transformer_Edition2 - Knock Test/collect_env.py", line 336, in get_pip_packages
    out = run_with_pip(sys.executable + " -mpip")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/elliott/Downloads/Multimodal_Transformer_Edition2 - Knock Test/collect_env.py", line 324, in run_with_pip
    for line in out.splitlines()
                ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'splitlines'

However the versions are those same ones supplied when using the pip install method above, running Python 3.11

**Comment by ElliottDyson** [comment]
> Duplicate of 
> https://github.com/intel/intel-extension-for-pytorch/issues/325

Thank you. Sorry I missed that
