### ISSUE TITLE
[IPEX Sanity Test] ModuleNotFoundError: No module named 'sympy.utilities'

### ISSUE THREAD

**Issue by rskasturi** [intel/intel-extension-for-pytorch#524]
### Describe the issue

```
(test) user@idc-beta-batch-pvc-node-17:~$ python -c "import torch; import intel_extension_for_pytorch as ipex; print(torch.__version__); print(ipex.__version__); [print(f'[{i}]: {torch.xpu.get_device_properties(i)}') for i in range(torch.xpu.device_count())];"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/.conda/envs/test/lib/python3.9/site-packages/torch/__init__.py", line 1504, in <module>
    from . import masked
  File "/home/user/.conda/envs/test/lib/python3.9/site-packages/torch/masked/__init__.py", line 3, in <module>
    from ._ops import (
  File "/home/user/.conda/envs/test/lib/python3.9/site-packages/torch/masked/_ops.py", line 11, in <module>
    from torch._prims_common import corresponding_real_dtype
  File "/home/user/.conda/envs/test/lib/python3.9/site-packages/torch/_prims_common/__init__.py", line 23, in <module>
    import sympy
  File "/home/user/.local/lib/python3.9/site-packages/sympy/__init__.py", line 30, in <module>
    from sympy.core.cache import lazy_function
  File "/home/user/.local/lib/python3.9/site-packages/sympy/core/__init__.py", line 4, in <module>
    from .sympify import sympify, SympifyError
  File "/home/user/.local/lib/python3.9/site-packages/sympy/core/sympify.py", line 8, in <module>
    from sympy.core.random import choice
  File "/home/user/.local/lib/python3.9/site-packages/sympy/core/random.py", line 25, in <module>
    from sympy.utilities.iterables import is_sequence
ModuleNotFoundError: No module named 'sympy.utilities'
```

Unable to resolve this issue while doing the [sanity test](https://intel.github.io/intel-extension-for-pytorch/index.html#installation?platform=gpu&version=v2.1.10%2Bxpu:~:text=Intel%20conda%20channel.-,4.%20Sanity%20Test,-You%20can%20run), after following the installation instructions from [here](https://intel.github.io/intel-extension-for-pytorch/index.html#installation?platform=gpu&version=v2.1.10%2Bxpu).

**Here are the steps to reproduce**

```
$> conda create -n test python=3.9 -y
$> conda activate test

$> python -m pip install --no-cache-dir torch==2.1.0a0 torchvision==0.16.0a0 torchaudio==2.1.0a0 intel-extension-for-pytorch==2.1.10+xpu --extra-index-url https://pytorch-extension.intel.com/release-whl/stable/xpu/us/
```

**Additional info:**

```
(test) user@idc-beta-batch-pvc-node-17:~$ icpx --version
Intel(R) oneAPI DPC++/C++ Compiler 2024.0.0 (2024.0.0.20231017)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/user/intel/oneapi/compiler/2024.0/bin/compiler
Configuration file: /home/user/intel/oneapi/compiler/2024.0/bin/compiler/../icpx.cfg
```

```
(test) user@idc-beta-batch-pvc-node-17:~$ pip list
Package                     Version
--------------------------- ------------------
annotated-types             0.6.0
certifi                     2023.11.17
charset-normalizer          3.3.2
filelock                    3.13.1
fsspec                      2023.12.2
idna                        3.6
intel-extension-for-pytorch 2.1.10+xpu
Jinja2                      3.1.3
MarkupSafe                  2.1.4
mpmath                      1.3.0
networkx                    3.2.1
numpy                       1.26.3
packaging                   23.2
pillow                      10.2.0
pip                         23.1.2
psutil                      5.9.8
pydantic                    2.6.0
pydantic_core               2.16.1
requests                    2.31.0
setuptools                  67.7.2
sympy                       1.12
torch                       2.1.0a0+cxx11.abi
torchaudio                  2.1.0a0+cxx11.abi
torchvision                 0.16.0a0+cxx11.abi
typing_extensions           4.9.0
urllib3                     2.2.0
wheel                       0.40.0
```

**Comment by hueyline** [comment]
Hi @rskasturi, I am not able to reproduce the issue. Could you clean your local environment and reinstall IPEX? You can check the Python packages installed within your local environment. For example, in my local environment, the path is "~/miniconda3/envs/test/lib/python3.9/site-packages".

**Comment by rskasturi** [comment]
It worked! Setup a new environment and installed it from the wheels this time.
Not sure if the ordered of installation matters. IPEX first and torch next.

Thanks @hueyline,
