### ISSUE TITLE
I can't import ipex(v2.1.10+xpu) on Windows 11

### ISSUE THREAD

**Issue by ShihKuanChen** [intel/intel-extension-for-pytorch#531]
### Describe the bug

I run these commands in powershell:
```
C:\Program Files (x86)\Intel\oneAPI\dpcpp-ct\latest\env\vars.bat
C:\Program Files (x86)\Intel\oneAPI\mkl\latest\env\vars.bat
```

Then I tried to run this code:
```python
import torch
import intel_extension_for_pytorch as ipex # the bug is here
```

I got the error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\python_projects\intel_pytorch_test_v3\intel_pytorch_test_v3_env\Lib\site-packages\intel_extension_for_pytorch\__init__.py", line 90, in <module>
    raise err
OSError: [WinError 126] 找不到指定的模組。 Error loading "D:\python_projects\intel_pytorch_test_v3\intel_pytorch_test_v3_env\Lib\site-packages\intel_extension_for_pytorch\bin\intel-ext-pt-gpu.dll" or one of its dependencies.
```

### Versions

PyTorch version: 2.1.0a0+cxx11.abi
PyTorch CXX11 ABI: No
IPEX version: N/A
IPEX commit: N/A
Build type: N/A

OS: Microsoft Windows 11 家用版
GCC version: N/A
Clang version: N/A
IGC version: N/A
CMake version: N/A
Libc version: N/A

Python version: 3.11.7 | packaged by Anaconda, Inc. | (main, Dec 15 2023, 18:05:47) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22631-SP0
Is XPU available: N/A
DPCPP runtime version: N/A
MKL version: N/A
GPU models and configuration:
N/A
Intel OpenCL ICD version: N/A
Level Zero version: N/A

CPU:
Architecture=9
CurrentClockSpeed=3500
DeviceID=CPU0
Family=205
L2CacheSize=20480
L2CacheSpeed=
Manufacturer=GenuineIntel
MaxClockSpeed=3500
Name=13th Gen Intel(R) Core(TM) i5-13600K
ProcessorType=3
Revision=

Versions of relevant libraries:
[pip3] intel-extension-for-pytorch==2.1.10+xpu
[pip3] numpy==1.26.4
[pip3] torch==2.1.0a0+cxx11.abi
[pip3] torchaudio==2.1.0a0+cxx11.abi
[pip3] torchvision==0.16.0a0+cxx11.abi
[conda] intel-extension-for-pytorch 2.1.10+xpu               pypi_0    pypi
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] torch                     2.1.0a0+cxx11.abi          pypi_0    pypi
[conda] torchaudio                2.1.0a0+cxx11.abi          pypi_0    pypi
[conda] torchvision               0.16.0a0+cxx11.abi          pypi_0    pypi

**Comment by ShihKuanChen** [comment]
When I changed from powershell to cmd it worked!
