### ISSUE TITLE
Build version v2.1.10+xpu from source code, met python ipex import error with mkl symbol libmkl_sycl_lapack.so.4

### ISSUE THREAD

**Issue by bopeng1234** [intel/intel-extension-for-pytorch#561]
### Describe the issue

Hi,

I am trying to build the ipex xpu from source code, referring to [link](https://intel.github.io/intel-extension-for-pytorch/index.html#installation?platform=gpu&version=v2.1.10%2Bxpu) .

Hardware: i9-12900KF + Arc770
OS: Anolis OS (CentOS like OS), kernel 6.6

After compilation done, try to import ipex, met following issue.
```
(base) [root@e2b895ae002c mkl]# python -c "import torch; import intel_extension_for_pytorch as ipex;"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/anaconda3/lib/python3.11/site-packages/intel_extension_for_pytorch/__init__.py", line 94, in <module>
    from .utils._proxy_module import *
  File "/root/anaconda3/lib/python3.11/site-packages/intel_extension_for_pytorch/utils/_proxy_module.py", line 2, in <module>
    import intel_extension_for_pytorch._C
ImportError: /opt/intel/oneapi/mkl/2024.0/lib/libmkl_sycl_lapack.so.4: undefined symbol: mkl_lapack_dsytrd_sb2st_block_rfg
```

the installed MKL version is:
```
(base) [root@e2b895ae002c mkl]# dnf list --installed | grep intel
intel-oneapi-mkl-2024.0.x86_64                        2024.0.0-49656               @oneAPI
intel-oneapi-mkl-common-2024.0.noarch                 2024.0.0-49656               @oneAPI
intel-oneapi-mkl-common-devel-2024.0.noarch           2024.0.0-49656               @oneAPI
intel-oneapi-mkl-devel.x86_64                         2024.0.0-49656               @oneAPI
intel-oneapi-mkl-devel-2024.0.x86_64                  2024.0.0-49656               @oneAPI
```
The MKL version is matching the installation link
`sudo dnf install -y intel-oneapi-dpcpp-cpp-2024.0 intel-oneapi-mkl-devel-2024.0.0-49656`

not sure why I met this import issue, looks like a version mismatch, looking forward to hear from you.

Thanks,
Bo

**Comment by ZailiWang** [comment]
Hi, would you share the branch and commit ID of the ipex source code you used for building? Thanks.

**Comment by bopeng1234** [comment]
Sure!
```
commit 45400a8cae41989c1e62ea60ee372564c4192ef6 (HEAD, tag: v2.1.10+xpu)
Author: Jing Xu <jing.xu@intel.com>
Date:   Fri Dec 15 18:31:42 2023 +0900

    bug fix in dockerfile.compile (#3617)
```

**Comment by ZailiWang** [comment]
Thanks for sharing this. Would you try with installing IPEX with downloaded prebuilt wheel file? 
```
python -m pip install intel-extension-for-pytorch==2.1.10+xpu --extra-index-url https://pytorch-extension.intel.com/release-whl/stable/xpu/cn/
```
and check if this solves your problem?
This step can help diagnose if something is wrong with your env, or something wrong with the src build script `combile_bundle.sh`.
Please let me know your test result. Thanks!

**Comment by bopeng1234** [comment]
OK, I am in conda env as the `compile_bundle.sh` required.
So, I created a new env and install the torch and ipex as below, tried but still has issue.
```
conda create -n official-ipex-xpu-test python=3.10
conda activate official-ipex-xpu-test
python -m pip install install torch==2.1.0a0 intel-extension-for-pytorch==2.1.10+xpu --extra-index-url https://pytorch-extension.intel.com/release-whl/stable/xpu/cn/

[root@e2b895ae002c intel-extension-for-pytorch]# python -c "import torch; import intel_extension_for_pytorch as ipex;"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Document/ipex-xpu-source-code-compile/intel-extension-for-pytorch/intel_extension_for_pytorch/__init__.py", line 94, in <module>
    from .utils._proxy_module import *
  File "/Document/ipex-xpu-source-code-compile/intel-extension-for-pytorch/intel_extension_for_pytorch/utils/_proxy_module.py", line 2, in <module>
    import intel_extension_for_pytorch._C
ModuleNotFoundError: No module named 'intel_extension_for_pytorch._C'
(official-ipex-xpu-test) [root@e2b895ae002c intel-extension-for-pytorch]# which python
/root/anaconda3/envs/official-ipex-xpu-test/bin/python
(official-ipex-xpu-test) [root@e2b895ae002c intel-extension-for-pytorch]# which pip
/root/anaconda3/envs/official-ipex-xpu-test/bin/pip
(official-ipex-xpu-test) [root@e2b895ae002c intel-extension-for-pytorch]# python -m pip list | grep intel
intel-extension-for-pytorch 2.1.10+xpu
(official-ipex-xpu-test) [root@e2b895ae002c intel-extension-for-pytorch]# python -m pip list | grep torch
intel-extension-for-pytorch 2.1.10+xpu
torch                       2.1.0a0+cxx11.abi
```

**Comment by ZailiWang** [comment]
Did you invoke oneAPI env in advance?
```
source /opt/intel/oneapi/setvars.sh
```

**Comment by bopeng1234** [comment]
Yes, did it

**Comment by ZailiWang** [comment]
Hmm... anyway, would you try with the original conda env in which the "undefined symbol" of the libmkl library error was invoked? Try replace the ipex python lib from source code build version to wheel file "pip install" version. Add a `--force-reinstall` flag with the `pip install intel_extension_for_pytorch......` command for this.

**Comment by bopeng1234** [comment]
ok,

1. in original conda env, replaced the ipex from source code build to wheel file
`(base) [root@e2b895ae002c /]# pip install --force-reinstall intel-extension-for-pytorch==2.1.10+xpu --extra-index-url https://pytorch-extension.intel.com/release-whl/stable/xpu/cn/`

Then, the same issue before, undefined symbol.
```
(base) [root@e2b895ae002c /]# python -c "import torch; import intel_extension_for_pytorch as ipex;"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/anaconda3/lib/python3.11/site-packages/intel_extension_for_pytorch/__init__.py", line 94, in <module>
    from .utils._proxy_module import *
  File "/root/anaconda3/lib/python3.11/site-packages/intel_extension_for_pytorch/utils/_proxy_module.py", line 2, in <module>
    import intel_extension_for_pytorch._C
ImportError: /opt/intel/oneapi/mkl/2024.0/lib/libmkl_gnu_thread.so.2: undefined symbol: mkl_blas_xgemm_f16f16f32_pack
```

2. I found what I did is wrong, before.

As you suggested and I tried firstly, create a new conda env 'official-ipex-xpu-test', the installed wheel works well.
```
(official-ipex-xpu-test) [root@e2b895ae002c /]# python -c "import torch; import intel_extension_for_pytorch as ipex; print(torch.__version__); print(ipex.__version__); [print(f'[{i}]: {torch.xpu.get_device_properties(i)}') for i in range(torch.xpu.device_count())];"
2.1.0a0+cxx11.abi
2.1.10+xpu
[0]: _DeviceProperties(name='Intel(R) Arc(TM) A770 Graphics', platform_name='Intel(R) Level-Zero', dev_type='gpu, support_fp64=0, total_memory=15473MB, max_compute_units=512, gpu_eu_count=512)
```
what I did wrong is the terminal path has a folder named intel_extension_for_pytorch, it is the source code path, so no _C module.

**Comment by bopeng1234** [comment]
is the python version matters?
conda env official-ipex-xpu-test use Python 3.10.13, good.
conda env base use Python 3.11.7, failed

**Comment by bopeng1234** [comment]
Looks like the python version is not the root cause, confirmed it.

The root cause might be the conda base env has mkl and intel-openmp installed.

```
pip remove torch intel-extension-for-pytorch
pip install torch==2.1.0a0 intel-extension-for-pytorch==2.1.10+xpu --extra-index-url https://pytorch-extension.intel.com/release-whl/stable/xpu/cn/
(base) [root@e2b895ae002c /]# python -c "import torch; import intel_extension_for_pytorch as ipex; print(torch.__version__); print(ipex.__version__); [print(f'[{i}]: {torch.xpu.get_device_properties(i)}') for i in range(torch.xpu.device_count())];"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/anaconda3/lib/python3.11/site-packages/intel_extension_for_pytorch/__init__.py", line 94, in <module>
    from .utils._proxy_module import *
  File "/root/anaconda3/lib/python3.11/site-packages/intel_extension_for_pytorch/utils/_proxy_module.py", line 2, in <module>
    import intel_extension_for_pytorch._C
ImportError: /root/anaconda3/bin/../lib/libmkl_intel_ilp64.so.2: undefined symbol: mkl_graph_descriptor_destroy_internal
(base) [root@e2b895ae002c /]# mv /root/anaconda3/bin/../lib/libmkl_* /bak/
(base) [root@e2b895ae002c /]# python -c "import torch; import intel_extension_for_pytorch as ipex; print(torch.__version__); print(ipex.__version__); [print(f'[{i}]: {torch.xpu.get_device_properties(i)}') for i in range(torch.xpu.device_count())];"
2.1.0a0+cxx11.abi
2.1.10+xpu
...
(base) [root@e2b895ae002c intel-extension-for-pytorch]# pip uninstall intel_extension_for_pytorch
(base) [root@e2b895ae002c /]# pip install Document/ipex-xpu-source-code-compile/intel-extension-for-pytorch/dist/intel_extension_for_pytorch-2.1.10+git45400a8-cp311-cp311-linux_x86_64.whl
(base) [root@e2b895ae002c /]# python -c "import torch; import intel_extension_for_pytorch as ipex; print(torch.__version__); print(ipex.__version__); [print(f'[{i}]: {torch.xpu.get_device_properties(i)}') for i in range(torch.xpu.device_count())];"
2.1.0a0+cxx11.abi
2.1.10+git45400a8
[0]: _DeviceProperties(name='Intel(R) Arc(TM) A770 Graphics', platform_name='Intel(R) Level-Zero', dev_type='gpu, support_fp64=0, total_memory=15473MB, max_compute_units=512, gpu_eu_count=512)
```

As the log say, after I did `mv /root/anaconda3/bin/../lib/libmkl_* /bak/`, both the wheel and source build can work now.
not sure why we use conda in the script, met a lot issue about conda env.
I will try to rebuild to see if still issue exit, and back to you soon!, thanks for the support @ZailiWang

**Comment by bopeng1234** [comment]
really confused me.

I re-compiled ipex, import the ipex met undefined symbol in /opt/.../libmkl...so file.
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/anaconda3/envs/ipex/lib/python3.10/site-packages/intel_extension_for_pytorch/__init__.py", line 94, in <module>
    from .utils._proxy_module import *
  File "/root/anaconda3/envs/ipex/lib/python3.10/site-packages/intel_extension_for_pytorch/utils/_proxy_module.py", line 2, in <module>
    import intel_extension_for_pytorch._C
ImportError: /opt/intel/oneapi/mkl/2024.0/lib/libmkl_sycl_dft.so.4: undefined symbol: fftw3_mkl
```

then remove the ipex and reinstall from official web whl file, then import success.

then remove it and reinstall the whl file locally built from source, the import met issue again.

@ZailiWang , any idea to check it?

**Comment by ZailiWang** [comment]
Hi @bopeng1234 thanks a lot for your effort and findings about this issue.
I asked an IPEX developer for this, yet the answer is "This is indeed an issue but only reproducible in a few cases. It is not easy to root cause since the complexity of the compilation process. We are considering to add it into `known issues` part in the doc."
If you have to compile your own ipex in your server, you can try setting up a docker env and do the src building in the container, this may works. Sorry for the inconvenience.

**Comment by bopeng1234** [comment]
Hi @ZailiWang 
Apply following diff can resolve the issue.
```
cmake/Modules/FindoneMKL.cmake
 # IPEX XPU lib always use the dynamic linker for oneMKL lib if USE_ONEMKL is ON and oneMKL is available.
 # IPEX CPU lib always download and install mkl-static lib and use static linker for mkl-static lib.
-if(BUILD_MODULE_TYPE STREQUAL "GPU")
-  set(BUILD_STATIC_ONEMKL OFF)
-  if(DEFINED ENV{MKLROOT})
-    set(mkl_root_hint $ENV{MKLROOT})
-  elseif(DEFINED ENV{MKL_ROOT})
-    set(mkl_root_hint $ENV{MKL_ROOT})
-  elseif(MKL_ROOT)
-    set(mkl_root_hint ${MKL_ROOT})
-  else()
-    message(WARNING "Please set oneMKL root path by MKLROOT, or MKL_ROOT for IPEX XPU build.")
-    return()
-  endif()
+set(BUILD_STATIC_ONEMKL OFF)
+if(DEFINED ENV{MKLROOT})
+  set(mkl_root_hint $ENV{MKLROOT})
+elseif(DEFINED ENV{MKL_ROOT})
+  set(mkl_root_hint $ENV{MKL_ROOT})
+elseif(MKL_ROOT)
+  set(mkl_root_hint ${MKL_ROOT})
 else()
-  set(BUILD_STATIC_ONEMKL ON)
-  message(STATUS "Download and install mkl-include and mkl-static for IPEX CPU build automatically.")
-  install_mkl_packages()
+  message(WARNING "Please set oneMKL root path by MKLROOT, or MKL_ROOT for IPEX XPU build.")
+  return()
 endif()
```

I met another issue, and want to get your insight.
After I opened AOT, the compilation for kernels is facing a issue.
```
In file included from /Document/ipex-xpu-source-code-compile-2/intel-extension-for-pytorch/csrc/gpu/aten/operators/xetla/kernels/GEMM/hgemm.cpp:3:
/Document/ipex-xpu-source-code-compile-2/intel-extension-for-pytorch/csrc/gpu/aten/operators/xetla/kernels/GEMM/hgemm_impl.h:289:40: error: non-constant-expression cannot be narrowed from type 'int' to 'uint32_t' (aka 'unsigned int') in initializer list [-Wc++11-narrowing]
  289 |       {{{const_cast<scalar_t*>(res0), {n, m, n}, res0_factor},
```
even thought I added `-Wc++11-narrowing` in `cmake/gpu/BuildFlags.cmake` and `csrc/CMakeLists.txt`, the issue still exists.
`set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wc++11-narrowing")`

Dose anyone met this before and how to resolve it?

**Comment by ZailiWang** [comment]
@jingxu10 @xuhancn would you help review the changes the reporter made to fix the error, and look into the current issue he shared above? thanks.

**Comment by bopeng1234** [comment]
Oh, the current issue is my bad, I wrong removed `set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-narrowing")`, revert it, and works well. will double confirm and back to you.

**Comment by bopeng1234** [comment]
no issue now, the workaround is https://github.com/intel/intel-extension-for-pytorch/issues/561#issuecomment-2014171460
, close the issue.
