### ISSUE TITLE
[python][cpu][llm] run with THUDM/chatglm3-6b raise "RuntimeError: Unsupported input type"

### ISSUE THREAD

**Issue by mozillazg** [intel/intel-extension-for-pytorch#583]
### Describe the bug

1. build test env follow: https://github.com/intel/intel-extension-for-pytorch/tree/main/examples/cpu/inference/python/llm#31-recommended-docker-based-environment-setup-with-compilation-from-source
2. run `python run.py -m THUDM/chatglm3-6b --prompt 'who are you?' --ipex --num-iter 2 --benchmark` in the container:

```
~/llm$ python run.py -m THUDM/chatglm3-6b --prompt 'who are you?' --ipex --num-iter 2 --benchmark
LLM RUNTIME INFO: running model geneartion...
Namespace(model_id='THUDM/chatglm3-6b', dtype='bfloat16', input_tokens='32', max_new_tokens=32, prompt='who are you?', streaming=False, image_url='http://images.cocodataset.org/val2017/000000039769.jpg', config_file=None, greedy=False, ipex=True, deployment_mode=True, torch_compile=False, backend='ipex', profile=False, benchmark=True, num_iter=2, num_warmup=10, batch_size=1, token_latency=False)
/home/ubuntu/miniconda3/envs/py310/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py:266: UserWarning: Device capability of ccl unspecified, assuming `cpu` and `cuda`. Please specify it via the `devices` argument of `register_backend`.
  warnings.warn(
Warning: Cannot load xpu CCL. CCL doesn't work for XPU device
[2024-04-07 02:21:49,745] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cpu (auto detect)
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  2.39it/s]
2024-04-07 02:21:57,339 - _logger.py - transformers_modules.THUDM.chatglm3_6b._03caa40027ebfd8450289ca2f278eac4ff26405.tokenization_chatglm - WARNING - Setting eos_token is not supported, use the default one.
2024-04-07 02:21:57,339 - _logger.py - transformers_modules.THUDM.chatglm3_6b._03caa40027ebfd8450289ca2f278eac4ff26405.tokenization_chatglm - WARNING - Setting pad_token is not supported, use the default one.
2024-04-07 02:21:57,339 - _logger.py - transformers_modules.THUDM.chatglm3_6b._03caa40027ebfd8450289ca2f278eac4ff26405.tokenization_chatglm - WARNING - Setting unk_token is not supported, use the default one.
[INFO] SINGLE_INSTANCE MODE.
/home/ubuntu/miniconda3/envs/py310/lib/python3.10/site-packages/transformers/modeling_utils.py:4193: FutureWarning: `_is_quantized_training_enabled` is going to be deprecated in transformers 4.39.0. Please use `model.hf_quantizer.is_trainable` instead
  warnings.warn(
/home/ubuntu/miniconda3/envs/py310/lib/python3.10/site-packages/intel_extension_for_pytorch/transformers/models/reference/models.py:745: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if (attention_mask is not None and not attention_mask.all()) or (
/home/ubuntu/miniconda3/envs/py310/lib/python3.10/site-packages/intel_extension_for_pytorch/transformers/models/reference/models.py:746: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  past_key_values and seq_length != 1
/home/ubuntu/miniconda3/envs/py310/lib/python3.10/site-packages/intel_extension_for_pytorch/transformers/models/reference/modules/attentions.py:2590: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if past_length:
2024-04-07 02:22:00,436 - _logger.py - IPEX - WARNING - [NotSupported]fail to apply ipex.llm.optimize due to: Unsupported input type, fallback to the origin model
---- Prompt size: 6
/home/ubuntu/miniconda3/envs/py310/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:410: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
Traceback (most recent call last):
  File "/home/ubuntu/llm/single_instance/run_generation.py", line 307, in <module>
    output = model.generate(input_ids, **generate_kwargs)
  File "/home/ubuntu/miniconda3/envs/py310/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/py310/lib/python3.10/site-packages/transformers/generation/utils.py", line 1626, in generate
    return self.beam_search(
  File "/home/ubuntu/miniconda3/envs/py310/lib/python3.10/site-packages/intel_extension_for_pytorch/transformers/generation/beam_search.py", line 338, in _beam_search
    outputs = self(
  File "/home/ubuntu/miniconda3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1536, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/py310/lib/python3.10/site-packages/intel_extension_for_pytorch/transformers/models/reference/models.py", line 851, in ChatGLMForConditionalGeneration_forward
    transformer_outputs = self.transformer(
  File "/home/ubuntu/miniconda3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1536, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/py310/lib/python3.10/site-packages/intel_extension_for_pytorch/transformers/models/reference/models.py", line 761, in ChatGLMModel_forward
    hidden_states, presents, all_hidden_states, all_self_attentions = self.encoder(
  File "/home/ubuntu/miniconda3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1536, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/py310/lib/python3.10/site-packages/intel_extension_for_pytorch/transformers/models/reference/models.py", line 814, in GLMTransformer_forward
    layer_ret = layer(
  File "/home/ubuntu/miniconda3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1536, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/py310/lib/python3.10/site-packages/intel_extension_for_pytorch/transformers/models/reference/modules/decoder.py", line 1403, in forward
    return GLMBlock_forward(
  File "/home/ubuntu/miniconda3/envs/py310/lib/python3.10/site-packages/intel_extension_for_pytorch/transformers/models/reference/modules/decoder.py", line 372, in GLMBlock_forward
    layernorm_output = self.input_layernorm(hidden_states)
  File "/home/ubuntu/miniconda3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1536, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/py310/lib/python3.10/site-packages/intel_extension_for_pytorch/transformers/models/cpu/fusions/mha_fusion.py", line 310, in forward
    return torch.ops.torch_ipex.rmsnorm(
  File "/home/ubuntu/miniconda3/envs/py310/lib/python3.10/site-packages/torch/_ops.py", line 860, in __call__
    return self_._op(*args, **(kwargs or {}))
RuntimeError: Unsupported input type
LLM RUNTIME ERROR: Running generation task failed. Quit.
```

### Versions

```
$ python collect_env.py
/home/ubuntu/miniconda3/envs/py310/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py:266: UserWarning: Device capability of ccl unspecified, assuming `cpu` and `cuda`. Please specify it via the `devices` argument of `register_backend`.
  warnings.warn(
Warning: Cannot load xpu CCL. CCL doesn't work for XPU device
[2024-04-07 02:22:43,331] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cpu (auto detect)
Collecting environment information...
PyTorch version: 2.4.0.dev20240325+cpu
PyTorch CXX11 ABI: No
IPEX version: 2.4.0+gite4a6456
IPEX commit: e4a645649
Build type: Release

OS: Ubuntu 22.04.4 LTS (x86_64)
GCC version: (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0
Clang version: N/A
IGC version: N/A
CMake version: N/A
Libc version: glibc-2.35

Python version: 3.10.14 (main, Mar 21 2024, 16:24:04) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.10.134-16.1.al8.x86_64-x86_64-with-glibc2.35
Is XPU available: False
DPCPP runtime version: N/A
MKL version: N/A
GPU models and configuration: 

Intel OpenCL ICD version: N/A
Level Zero version: N/A

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   52 bits physical, 57 bits virtual
Byte Order:                      Little Endian
CPU(s):                          24
On-line CPU(s) list:             0-23
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) Platinum 8475B
CPU family:                      6
Model:                           143
Thread(s) per core:              2
Core(s) per socket:              12
Socket(s):                       1
Stepping:                        8
CPU max MHz:                     3800.0000
CPU min MHz:                     800.0000
BogoMIPS:                        5400.00
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq monitor ssse3 fma cx16 pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single ibrs_enhanced fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves avx_vnni avx512_bf16 wbnoinvd ida arat hwp hwp_notify hwp_act_window hwp_epp hwp_pkg_req avx512vbmi umip pku ospke waitpkg avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq rdpid bus_lock_detect cldemote movdiri movdir64b enqcmd fsrm uintr md_clear serialize tsxldtrk amx_bf16 avx512_fp16 amx_tile amx_int8 arch_capabilities
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       576 KiB (12 instances)
L1i cache:                       384 KiB (12 instances)
L2 cache:                        24 MiB (12 instances)
L3 cache:                        97.5 MiB (1 instance)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-23
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] intel-extension-for-pytorch==2.4.0+gite4a6456
[pip3] numpy==1.26.4
[pip3] torch==2.4.0.dev20240325+cpu
[conda] intel-extension-for-pytorch 2.4.0+gite4a6456          pypi_0    pypi
[conda] mkl                       2023.1.0         h213fc3f_46344  
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] torch                     2.4.0.dev20240325+cpu          pypi_0    pypi
```

**Comment by jgong5** [comment]
The error was thrown from here:
https://github.com/intel/intel-extension-for-pytorch/blob/e4a645649744bf03fa2c3d90b771d48a8dc204fc/csrc/cpu/aten/kernels/RMSNormKrnl.cpp#L66C25-L66C47

Even though I have no idea why, inputs are neither float nor bfloat16? cc @jianan-gu

**Comment by jianan-gu** [comment]
@mozillazg  Hi, please check the first line of this notes~
https://github.com/intel/intel-extension-for-pytorch/tree/main/examples/cpu/inference/python/llm#423-additional-configuration-for-specific-models

ChatGLM models have some [hard coded init](https://huggingface.co/THUDM/chatglm3-6b/blob/main/modeling_chatglm.py#L755) with` torch.float16` dtype, we have to change it to `torch.float32` in [config.json](https://huggingface.co/THUDM/chatglm3-6b/blob/main/config.json#L37)

**Comment by mozillazg** [comment]
@jianan-gu oh! sorry, my bad! Thanks for your reminder.

BTW, 

* how about place these notes before 4.1 section?
* asking the user to change the config.json of the model may not be a good idea ?

**Comment by jgong5** [comment]
> ChatGLM models have some [hard coded init](https://huggingface.co/THUDM/chatglm3-6b/blob/main/modeling_chatglm.py#L755) with` torch.float16` dtype, we have to change it to `torch.float32` in [config.json](https://huggingface.co/THUDM/chatglm3-6b/blob/main/config.json#L37)

Is it possible to reinit the `RotaryEmbedding` inside IPEX for such a case? Then, we don't require users to change the script.
