### ISSUE TITLE
ImportError: libze_loader.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by bconsolvo** [intel/intel-extension-for-pytorch#666]
### Describe the issue

I am running on WSL and Ubuntu 22.04

Even after installing the oneAPI base toolkit, and doing the 

```bash

source /opt/intel/oneapi/compiler/latest/env/vars.sh
source /opt/intel/oneapi/mkl/latest/env/vars.sh
export LD_LIBRARY_PATH=/opt/intel/oneapi/mkl/latest/lib:$LD_LIBRARY_PATH
source /opt/intel/oneapi/setvars.sh
export SYCL_CACHE_PERSISTENT=1
export BIGDL_LLM_XMX_DISABLED=1
```
I am still getting this import error. Would appreciate your help.

```bash 
import intel_extension_for_pytorch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/miniconda3/envs/gpu_ipexllm/lib/python3.10/site-packages/ipex_llm/__init__.py", line 38, in <module>
    ipex_importer.import_ipex()
  File "/root/miniconda3/envs/gpu_ipexllm/lib/python3.10/site-packages/ipex_llm/utils/ipex_importer.py", line 130, in import_ipex
    self.directly_import_ipex()
  File "/root/miniconda3/envs/gpu_ipexllm/lib/python3.10/site-packages/ipex_llm/utils/ipex_importer.py", line 144, in directly_import_ipex
    import intel_extension_for_pytorch as ipex
  File "/root/miniconda3/envs/gpu_ipexllm/lib/python3.10/site-packages/intel_extension_for_pytorch/__init__.py", line 95, in <module>
    from .utils._proxy_module import *
  File "/root/miniconda3/envs/gpu_ipexllm/lib/python3.10/site-packages/intel_extension_for_pytorch/utils/_proxy_module.py", line 2, in <module>
    import intel_extension_for_pytorch._C
ImportError: libze_loader.so.1: cannot open shared object file: No such file or directory
```

**Comment by ZailiWang** [comment]
Hi @bconsolvo , Ubuntu 20.04 has been out of IPEX support scope for a while. Would you try with 22.04? thanks.

**Comment by bconsolvo** [comment]
Nevermind, I was using Ubuntu 22.04 anyway. Disregard my initial comment of 20.04. Still same error. Thanks.

**Comment by jketreno** [comment]
Have you already installed the level-zero GPU driver in WSL2? If not:

```bash
wget -qO - https://repositories.intel.com/gpu/intel-graphics.key | \
  sudo gpg --yes --dearmor --output /usr/share/keyrings/intel-graphics.gpg
echo "deb [arch=amd64 signed-by=/usr/share/keyrings/intel-graphics.gpg] https://repositories.intel.com/gpu/ubuntu jammy/lts/2350 unified" | \
    sudo tee /etc/apt/sources.list.d/intel-gpu-jammy.list
sudo apt update
sudo apt install level-zero intel-level-zero-gpu
```

That will install the libze_loader.so (from level-zero) and the runtime for the Intel GPU.
