### ISSUE TITLE
CCL_ROOT Configuration in IPEX Image

### ISSUE THREAD

**Issue by youyou782** [intel/intel-extension-for-pytorch#727]
### Describe the issue

Hi all,

I'm wondering what value `${CCL_ROOT}` should be set when I'm using docker image intel/intel-extension-for-pytorch:2.3.110-xpu for DDP training. 

User manual tells to use `${CONDA_PREFIX}`, but the docker image is not using conda to manage packages.

**Comment by huiyan2021** [comment]
Hi @youyou782 , Thanks for reporting this issue. Please try ` export CCL_ROOT=/usr/local` . We will update the documentation later.

**Comment by youyou782** [comment]
Hi, thank you @huiyan2021 

however, after setting CCL_ROOT, there seems missing some other env variables.

```
2024:10:23-03:50:31:( 2305) |CCL_ERROR| atl_mpi_ctx.cpp:663 check_impi_env: CCL/MPI uses Intel(R) MPI Library but neither I_MPI_ROOT nor ONEAPI_ROOT is set. Please source release version of Intel(R) MPI Library (2019 or higher version).
2024:10:23-03:50:31:( 2305) |CCL_ERROR| atl_mpi_comm.cpp:87 init_transport: condition transport->init(nullptr, nullptr, &attr, nullptr, pmi) == ATL_STATUS_SUCCESS failed
```
```
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/huazhi/codes/applications.ai.spui.nlu-kernel/internal/train_test.py", line 24, in <module>
[rank0]:     kernel.train(configs)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/nlukernel/kernel.py", line 218, in train
[rank0]:     self.model.train(train_samples, dev_samples, unlabelled_samples, self.tokenizer,
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/nlukernel/models/base.py", line 459, in train
[rank0]:     model = self._convert_for_parallel()
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/nlukernel/models/base.py", line 1074, in _convert_for_parallel
[rank0]:     return nn.parallel.DistributedDataParallel(
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/distributed.py", line 798, in __init__
[rank0]:     _verify_param_shape_across_processes(self.process_group, parameters)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/distributed/utils.py", line 269, in _verify_param_shape_across_processes
[rank0]:     return dist._verify_params_across_processes(process_group, tensors, logger)
[rank0]: RuntimeError: oneCCL: atl_mpi_comm.cpp:87 init_transport: EXCEPTION: failed to initialize ATL
```

**Comment by huiyan2021** [comment]
Try below:

```
export I_MPI_ROOT=/usr/local
export LD_LIBRARY_PATH=/usr/local/lib/ccl:/usr/local/lib/libfabric:/usr/local/lib/mpi
```

**Comment by youyou782** [comment]
Hi, thanks @huiyan2021 

Should there be a script like setvar.sh for user to source for convenience? According to env variable references in the Intel® MPI Library Developer Guide, I think there are more env variables need to be set other than those mentioned above.

**Comment by jingxu10** [comment]
Please try
```
export CCL_ROOT="/usr/local"
export I_MPI_ROOT="/usr/local"
export CLASSPATH="${I_MPI_ROOT}/lib/mpi.jar"
export PATH="${I_MPI_ROOT}/bin/libfabric:${PATH}"
export LD_LIBRARY_PATH="${I_MPI_ROOT}/lib/libfabric:${LD_LIBRARY_PATH}"
export FI_PROVIDER_PATH="${I_MPI_ROOT}/lib/libfabric/prov:/usr/lib/x86_64-linux-gnu/libfabric"

# wget https://github.com/intel/torch-ccl/raw/refs/heads/master/demo/demo.py
# mpirun -n 2 -l python demo.py --device xpu
[0] /usr/local/lib/python3.10/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 'libpng16.so.16: cannot open shared object file: No such file or directory'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
[0]   warn(
[1] /usr/local/lib/python3.10/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 'libpng16.so.16: cannot open shared object file: No such file or directory'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
[1]   warn(
[1] /usr/local/lib/python3.10/dist-packages/intel_extension_for_pytorch/llm/__init__.py:9: UserWarning: failed to use huggingface generation fuctions due to: No module named 'transformers'.                                                                                                                           [1]   warnings.warn(f"failed to use huggingface generation fuctions due to: {e}.")                                                                          [0] /usr/local/lib/python3.10/dist-packages/intel_extension_for_pytorch/llm/__init__.py:9: UserWarning: failed to use huggingface generation fuctions due to: No module named 'transformers'.                                                                                                                           [0]   warnings.warn(f"failed to use huggingface generation fuctions due to: {e}.")                                                                          [1] [rank1]:[W reducer.cpp:69] Warning: measureDifference between two events is not supported on XPU backend! (function operator())
[0] [rank0]:[W reducer.cpp:69] Warning: measureDifference between two events is not supported on XPU backend! (function operator())
[1] Runing Iteration: 0 on device xpu:1
[1] Runing forward: 0 on device xpu:1
[1] Runing loss: 0 on device xpu:1
[1] Runing backward: 0 on device xpu:1
[1] Runing optim: 0 on device xpu:1
[1] Runing Iteration: 1 on device xpu:1
[1] Runing forward: 1 on device xpu:1
[1] Runing loss: 1 on device xpu:1
[1] Runing backward: 1 on device xpu:1
[1] Runing optim: 1 on device xpu:1
[1] Runing Iteration: 2 on device xpu:1
[1] Runing forward: 2 on device xpu:1
[1] Runing loss: 2 on device xpu:1
[1] Runing backward: 2 on device xpu:1
[1] Runing optim: 2 on device xpu:1
[1] Finish
[0] Runing Iteration: 0 on device xpu:0
[0] Runing forward: 0 on device xpu:0
[0] Runing loss: 0 on device xpu:0
[0] Runing backward: 0 on device xpu:0
[0] Runing optim: 0 on device xpu:0
[0] Runing Iteration: 1 on device xpu:0
[0] Runing forward: 1 on device xpu:0
[0] Runing loss: 1 on device xpu:0
[0] Runing backward: 1 on device xpu:0
[0] Runing optim: 1 on device xpu:0
[0] Runing Iteration: 2 on device xpu:0
[0] Runing forward: 2 on device xpu:0
[0] Runing loss: 2 on device xpu:0
[0] Runing backward: 2 on device xpu:0
[0] Runing optim: 2 on device xpu:0
[0] Finish
```

**Comment by youyou782** [comment]
Hi @jingxu10 ,
 
Now it works, thanks.

**Comment by huiyan2021** [comment]
Thanks for the update, close the issue.
