### ISSUE TITLE
Fail to run 4bit phi3 model on LNL XPU

### ISSUE THREAD

**Issue by shira-g** [intel/intel-extension-for-pytorch#742]
Hi,

I'm trying to run optimized phi3 4-bit model and failing to do so.
I tested two ways:

**First try:**

```
from transformers import AutoTokenizer, AutoModelForCausalLM
import intel_extension_for_pytorch as ipex
import torch

device = "xpu"
model_name = "microsoft/Phi-3-mini-4k-instruct"
qmodel = AutoModelForCausalLM.from_pretrained(model_name, load_in_4bit=True, device_map=device, trust_remote_code=True)
qmodel = ipex.optimize_transformers(qmodel, inplace=True, device=device)
```

**Error:**

Traceback (most recent call last):
  File "C:\Users\sdp\shira\ipex_example\run.py", line 10, in <module>
    qmodel = ipex.optimize_transformers(qmodel, inplace=True, device=device)
  File "C:\Users\sdp\miniforge3\envs\ipex\lib\site-packages\intel_extension_for_pytorch\transformers\optimize.py", line 1662, in optimize_transformers
    _model = model_convert_lowering(
  File "C:\Users\sdp\miniforge3\envs\ipex\lib\site-packages\intel_extension_for_pytorch\transformers\optimize.py", line 1226, in model_convert_lowering
    _model = converter.convert_model(_model, dtype)
  File "C:\Users\sdp\miniforge3\envs\ipex\lib\site-packages\intel_extension_for_pytorch\transformers\models\xpu\optimize_transformers\Converter.py", line 220, in convert_model
    model = model.to(device).to(dtype)
  File "C:\Users\sdp\miniforge3\envs\ipex\lib\site-packages\accelerate\big_modeling.py", line 457, in wrapper
    return fn(*args, **kwargs)
  File "C:\Users\sdp\miniforge3\envs\ipex\lib\site-packages\transformers\modeling_utils.py", line 3136, in to
    raise ValueError(
ValueError: You cannot cast a bitsandbytes model in a new `dtype`. Make sure to load the model using `from_pretrained` using the desired `dtype` by passing the correct `torch_dtype` argument.

**Second try:**

```
from transformers import AutoModelForCausalLM
import intel_extension_for_pytorch as ipex
import torch

device = "xpu"
model_name = "microsoft/Phi-3-mini-4k-instruct"
model = AutoModelForCausalLM.from_pretrained(model_name, device_map=device, trust_remote_code=True)
qconfig = ipex.quantization.get_weight_only_quant_qconfig_mapping(weight_dtype=2, group_size=64)
qmodel = ipex.optimize_transformers(model, inplace=True, dtype=torch.float16, quantization_config=qconfig, device=device)

```
**Error:**

Traceback (most recent call last):
  File "C:\Users\sdp\shira\ipex_example\run.py", line 9, in <module>
    qmodel = ipex.optimize_transformers(model, inplace=True, dtype=torch.float16, quantization_config=qconfig, device=device)
  File "C:\Users\sdp\miniforge3\envs\ipex\lib\site-packages\intel_extension_for_pytorch\transformers\optimize.py", line 1662, in optimize_transformers
    _model = model_convert_lowering(
  File "C:\Users\sdp\miniforge3\envs\ipex\lib\site-packages\intel_extension_for_pytorch\transformers\optimize.py", line 1226, in model_convert_lowering
    _model = converter.convert_model(_model, dtype)
  File "C:\Users\sdp\miniforge3\envs\ipex\lib\site-packages\intel_extension_for_pytorch\transformers\models\xpu\optimize_transformers\Converter.py", line 229, in convert_model
    is_replace_success = self.module_replacer.replace_module(
  File "C:\Users\sdp\miniforge3\envs\ipex\lib\site-packages\intel_extension_for_pytorch\transformers\models\xpu\optimize_transformers\ModuleReplacer.py", line 242, in replace_module
    self.replace_module(child, dtype, config, module_name + name)
  File "C:\Users\sdp\miniforge3\envs\ipex\lib\site-packages\intel_extension_for_pytorch\transformers\models\xpu\optimize_transformers\ModuleReplacer.py", line 242, in replace_module
    self.replace_module(child, dtype, config, module_name + name)
  File "C:\Users\sdp\miniforge3\envs\ipex\lib\site-packages\intel_extension_for_pytorch\transformers\models\xpu\optimize_transformers\ModuleReplacer.py", line 226, in replace_module
    new_module = NewIPEXPhi3DecoderLayer(
  File "C:\Users\sdp\miniforge3\envs\ipex\lib\site-packages\intel_extension_for_pytorch\transformers\models\xpu\optimize_transformers\modules\phi3.py", line 65, in __init__
    self.port_all_parameters_to_new_module()
  File "C:\Users\sdp\miniforge3\envs\ipex\lib\site-packages\intel_extension_for_pytorch\transformers\models\xpu\optimize_transformers\modules\phi3.py", line 149, in port_all_parameters_to_new_module
    super().port_all_parameters_to_new_module()
  File "C:\Users\sdp\miniforge3\envs\ipex\lib\site-packages\intel_extension_for_pytorch\transformers\models\xpu\optimize_transformers\modules\transformer_modules\DecoderBlock.py", line 82, in port_all_parameters_to_new_module
    self.port_attn_parameter()
  File "C:\Users\sdp\miniforge3\envs\ipex\lib\site-packages\intel_extension_for_pytorch\transformers\models\xpu\optimize_transformers\modules\phi3.py", line 112, in port_attn_parameter
    self.attn.load_parameter(
  File "C:\Users\sdp\miniforge3\envs\ipex\lib\site-packages\intel_extension_for_pytorch\transformers\models\xpu\optimize_transformers\modules\transformer_modules\model_utils.py", line 27, in qwen_load_attn_params_int4
    self.qkv_proj_quant.set_weights_bias(qkv_layer.qweight, qkv_layer.bias)
  File "C:\Users\sdp\miniforge3\envs\ipex\lib\site-packages\torch\nn\modules\module.py", line 1709, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'Linear' object has no attribute 'qweight'. Did you mean: 'weight'?

**System:**
Windows 11
Intel(R) Core(TM) Ultra 7 263V 2.20GHz
Intel(R) Arc(TM) 140V GPU

**Ipex Installation:**
command retrived from: https://intel.github.io/intel-extension-for-pytorch/#installation?platform=gpu&version=v2.3.110%2bxpu&os=windows&package=pip :

conda install libuv
python -m pip install torch==2.3.1.post0+cxx11.abi torchvision==0.18.1.post0+cxx11.abi torchaudio==2.3.1.post0+cxx11.abi intel-extension-for-pytorch==2.3.110.post0+xpu --extra-index-url https://pytorch-extension.intel.com/release-whl/stable/lnl/us/

**Comment by ZailiWang** [comment]
Hi, the support for INT4 WOQ requires `intel_extension_for_transformers` and `intel_neural_compressor` packages in ipex 2.3.110+xpu. Please follow [this instruction](https://github.com/intel/intel-extension-for-pytorch/tree/release/xpu/2.3.110/examples/gpu/llm/inference#weight-only-quantization-with-low-precision-checkpoint-prototype).

**Comment by shira-g** [comment]
Thank you, is this true also for int8?
Also- will int4 be supported in the future (without requiring intel_extension_for_transformers and intel_neural_compressor) ?

**Comment by shira-g** [comment]
> this instruction

I tried it and installation step for intel_extension_for_transformers fails with:
".
.
.
byte-compiling build\bdist.win-amd64\egg\intel_extension_for_transformers\transformers\runtime\compile\sub_graph\attention_output_layer_norm_length_adaptive_keep_indices.py to attention_output_layer_norm_length_adaptive_keep_indices.cpython-310.pyc
error: [Errno 2] No such file or directory: 'build\\bdist.win-amd64\\egg\\intel_extension_for_transformers\\transformers\\runtime\\compile\\sub_graph\\__pycache__\\attention_output_layer_norm_length_adaptive_keep_indices.cpython-310.pyc.2534996854704'
"

**Comment by ZailiWang** [comment]
> Thank you, is this also relevant for int8? Also- will int4 be supported in the future (without requiring intel_extension_for_transformers and intel_neural_compressor) ?

IPEX WOQ only supports INT4 but not INT8 for now.
and I'm afraid the support within stock PyTorch (without ipex/inc/itrex) is not available in short term, as PyTorch uses `auto-gptq` package for WOQ quant, which is binded with cuda for now.

**Comment by ZailiWang** [comment]
> > Hi, the support for INT4 WOQ requires `intel_extension_for_transformers` and `intel_neural_compressor` packages in ipex 2.3.110+xpu. Please follow [this instruction](https://github.com/intel/intel-extension-for-pytorch/tree/release/xpu/2.3.110/examples/gpu/llm/inference#weight-only-quantization-with-low-precision-checkpoint-prototype).
> 
> I tried it and installation step for intel_extension_for_transformers fails with: ". . . byte-compiling build\bdist.win-amd64\egg\intel_extension_for_transformers\transformers\runtime\compile\sub_graph\attention_output_layer_norm_length_adaptive_keep_indices.py to attention_output_layer_norm_length_adaptive_keep_indices.cpython-310.pyc error: [Errno 2] No such file or directory: 'build\bdist.win-amd64\egg\intel_extension_for_transformers\transformers\runtime\compile\sub_graph\**pycache**\attention_output_layer_norm_length_adaptive_keep_indices.cpython-310.pyc.2534996854704' "
> 
> here is a screenshot of the relevant file tree: ![Screenshot 2024-12-05 at 10 43 37](https://private-user-images.githubusercontent.com/30695324/392725718-38ec2cff-7366-4664-873f-4525ed48b766.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NzI5MzcsIm5iZiI6MTczMzQ3MjYzNywicGF0aCI6Ii8zMDY5NTMyNC8zOTI3MjU3MTgtMzhlYzJjZmYtNzM2Ni00NjY0LTg3M2YtNDUyNWVkNDhiNzY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDA4MTAzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0YjE3NGI1MTgyMzBlMjViZTE1YjYxNjZmZjkwYzkzYzRlMDcxMTE4YThlODA5N2E3MGE1YzIzZTA5MjA3YjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tMFj1tDDCkkT3AXF08UimxNafOkY4zeB4Q5vsgsXVNM)

I failed to reproduce such error message. Would you paste your env information here? (output of `pip list`)

**Comment by ZailiWang** [comment]
Suspect that some package files in the env were corrupted. Would you create a new env from scratch and test again?

**Comment by shira-g** [comment]
correct, I am now able to install.
I get an error now for loading the model.

Here is my code:

```
import intel_extension_for_pytorch as ipex
from intel_extension_for_transformers.transformers.modeling import AutoModelForCausalLM
from transformers import AutoTokenizer
import torch

device = "xpu"
model_name = "microsoft/Phi-3-mini-4k-instruct"
tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
prompt = "Once upon a time, there existed a little girl,"
inputs = tokenizer(prompt, return_tensors="pt").input_ids.to(device)
qmodel = AutoModelForCausalLM.from_pretrained(model_name, load_in_4bit=True, device_map="xpu", trust_remote_code=True)
qmodel = ipex.optimize_transformers(qmodel, inplace=True, dtype=torch.float16, quantization_config={}, device="xpu")
output = qmodel.generate(inputs)
```

**Error:**
```
Traceback (most recent call last):
  File "C:\Users\sdp\shira\ipex_generate.py", line 16, in <module>
    qmodel = AutoModelForCausalLM.from_pretrained(model_name, load_in_4bit=True, device_map="xpu", trust_remote_code=True)
  File "C:\Users\sdp\shira\intel-extension-for-transformers\intel_extension_for_transformers\transformers\modeling\modeling_auto.py", line 750, in from_pretrained
    model = cls.ORIG_MODEL.from_pretrained(
  File "C:\Users\sdp\miniforge3\envs\ipex_new\lib\site-packages\transformers\models\auto\auto_factory.py", line 553, in from_pretrained
    model_class = get_class_from_dynamic_module(
  File "C:\Users\sdp\miniforge3\envs\ipex_new\lib\site-packages\intel_extension_for_pytorch\llm\utils.py", line 430, in _get_class_from_dynamic_module
    return get_class_in_module(
  File "C:\Users\sdp\miniforge3\envs\ipex_new\lib\site-packages\transformers\dynamic_module_utils.py", line 238, in get_class_in_module
    module_files: List[Path] = [module_file] + sorted(map(Path, get_relative_import_files(module_file)))
  File "C:\Users\sdp\miniforge3\envs\ipex_new\lib\site-packages\transformers\dynamic_module_utils.py", line 128, in get_relative_import_files
    new_imports.extend(get_relative_imports(f))
  File "C:\Users\sdp\miniforge3\envs\ipex_new\lib\site-packages\intel_extension_for_pytorch\llm\utils.py", line 31, in _get_relative_imports
    with open(module_file, "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\sdp\\.cache\\huggingface\\modules\\transformers_modules\\microsoft\\Phi_3_mini_4k_instruct\\_a67737cc96d2554230f90338b163bc6380a2a85\\modeling_phi3'
```

<img width="303" alt="Screenshot 2024-12-09 at 11 56 52" src="https://github.com/user-attachments/assets/2537c85c-31f7-4f44-acab-8da62bbc8895">

**Comment by ZailiWang** [comment]
The file name in the reported error indicates that the end part of the file name is missing. But since the name is not exceeding default path name length limit (260), did you change the default `MAX_PATH` value?
Please try with [the instructions](https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry) and see if the problem can be passed.

**Comment by shira-g** [comment]
I set registry to "LongPathsEnabled"=dword:00000001 and restarted but the issue still persists.

**Comment by ZailiWang** [comment]
Would you check the version of packages in your env? Are they aligned with these:
```
huggingface-hub                  0.26.3
intel_extension_for_pytorch      2.3.110+xpu
intel-extension-for-transformers 1.6.dev11+gc263d09f089.gpu
neural_compressor                3.0
safetensors                      0.4.5
sentencepiece                    0.2.0
torch                            2.3.1+cxx11.abi
transformers                     4.38.1
transformers-stream-generator    0.0.5
```
I assume some interface conflict due to package version misalignment is the root cause, and these are the most suspicious ones.

**Comment by shira-g** [comment]
Hi,
I found that the issue is gone once moving the import ipex command to be after the import of transformers (a bit strange):
```
from transformers import AutoTokenizer, AutoModelForCausalLM
import intel_extension_for_pytorch as ipex
from intel_extension_for_transformers.transformers.modeling import AutoModelForCausalLM
import torch

device = "xpu"
model_name = "microsoft/Phi-3-mini-4k-instruct"
qmodel = AutoModelForCausalLM.from_pretrained(model_name, load_in_4bit=True, device_map="xpu", trust_remote_code=True)
qmodel = ipex.optimize_transformers(qmodel, inplace=True, dtype=torch.float16, quantization_config={}, device="xpu")
```
Now I can run phi3 optimization successfully.

Thank you!

**Comment by ZailiWang** [comment]
No problem, good to hear that!
