### ISSUE TITLE
ipexrun fails on Windows

### ISSUE THREAD

**Issue by pessimism** [intel/intel-extension-for-pytorch#743]
### Describe the bug

the extension supports windows but the ipexrun script has a code block preventing it from running on windows:

(comfy) C:\devgit\ComfyUI>ipexrun main.py --use-pytorch-cross-attention --highvram
C:\Users\steve\miniconda3\envs\comfy\lib\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: 'Could not find module 'C:\Users\steve\miniconda3\envs\comfy\Lib\site-packages\torchvision\image.pyd' (or one of its dependencies). Try using the full path with constructor syntax.'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
Traceback (most recent call last):
  File "C:\Users\steve\miniconda3\envs\comfy\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\steve\miniconda3\envs\comfy\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\steve\miniconda3\envs\comfy\Scripts\ipexrun.exe\__main__.py", line 7, in <module>
  File "C:\Users\steve\miniconda3\envs\comfy\lib\site-packages\intel_extension_for_pytorch\launcher.py", line 85, in main
    parser, cpu_parser, xpu_parser = init_parser()
  File "C:\Users\steve\miniconda3\envs\comfy\lib\site-packages\intel_extension_for_pytorch\launcher.py", line 67, in init_parser
    cpu_init_parser(cpu_parser)
  File "C:\Users\steve\miniconda3\envs\comfy\lib\site-packages\intel_extension_for_pytorch\cpu\launch\launch.py", line 404, in init_parser
    launcher_distributed = DistributedTrainingLauncher()
  File "C:\Users\steve\miniconda3\envs\comfy\lib\site-packages\intel_extension_for_pytorch\cpu\launch\launcher_base.py", line 15, in __init__
    self.cpuinfo = CPUPoolList(self.logger, lscpu_txt)
  File "C:\Users\steve\miniconda3\envs\comfy\lib\site-packages\intel_extension_for_pytorch\cpu\launch\cpu_info.py", line 143, in __init__
    raise RuntimeError("Windows platform is not supported!!!")
RuntimeError: Windows platform is not supported!!!

The code block is viewable in this repository:
https://github.com/intel/intel-extension-for-pytorch/blob/main/intel_extension_for_pytorch/cpu/launch/cpu_info.py#L142

If this is by design, documentation should be updated to reflect the incomplete support on Windows.

### Versions

intel_extension_for_pytorch==2.3.110.post0+xpu

**Comment by ZailiWang** [comment]
Hi, as the error message indicates, `ipexrun` is designated for Linux so does not support Windows.
