### ISSUE TITLE
error ablout inner product:RuntimeError: could not create a primitive descriptor for an inner product forward propagation primitive

### ISSUE THREAD

**Issue by shawnnjupt** [intel/intel-extension-for-pytorch#748]
when i run llama2 model(this is the source code from meta),when i do not enable ipex ,only run in torch ,it can be run correctly
but when i enable ipex ,it happens error
in attention module

```
class Attention(nn.Module):
    def __init__(self, args: ModelArgs):
        super().__init__()
        self.n_kv_heads = args.n_heads if args.n_kv_heads is None else args.n_kv_heads
        # model_parallel_size = fs_init.get_model_parallel_world_size()
        self.n_local_heads = args.n_heads 
        self.n_local_kv_heads = self.n_kv_heads 
        self.n_rep = self.n_local_heads // self.n_local_kv_heads
        self.head_dim = args.dim // args.n_heads

        self.wq = nn.Linear(args.dim,args.n_heads * self.head_dim,bias=False)
        self.wk = nn.Linear(args.dim,self.n_kv_heads * self.head_dim,bias=False)
        self.wv = nn.Linear(args.dim,self.n_kv_heads * self.head_dim,bias=False)
        self.wo = nn.Linear(args.n_heads * self.head_dim,args.dim,bias=False)

        self.cache_k = torch.zeros(
            (
                args.max_batch_size,
                args.max_seq_len,
                self.n_local_kv_heads,
                self.head_dim,
            )
        )
        self.cache_v = torch.zeros(
            (
                args.max_batch_size,
                args.max_seq_len,
                self.n_local_kv_heads,
                self.head_dim,
            )
        )
```
in forward def 
```
        bsz, seqlen, _ = x.shape
        # print("x_size=",x.size())
        xq= self.wq(x)
        xk = self.wk(x)
        xv = self.wv(x)
        # print("xq_size=",xq.size())

        xq = xq.view(bsz, seqlen, self.n_local_heads, self.head_dim)
        xk = xk.view(bsz, seqlen, self.n_local_kv_heads, self.head_dim)
        xv = xv.view(bsz, seqlen, self.n_local_kv_heads, self.head_dim)
```
this is very normal
but i use
` model = ipex.optimize(model.eval(),dtype=torch.bfloat16) `

report error is   in    xq= self.wq(x)   ,  
RuntimeError: could not create a primitive descriptor for an inner product forward propagation primitive
```
Traceback (most recent call last):
  File "/home/congxiao/code/python/llama2/2-7b/vtune_llama/amx_version/example_text_completion.py", line 65, in <module>
    main(ckpt_dir=checkpoints_dir,
  File "/home/congxiao/code/python/llama2/2-7b/vtune_llama/amx_version/example_text_completion.py", line 46, in main
    results = model.text_completion(
  File "/home/congxiao/code/python/llama2/2-7b/vtune_llama/amx_version/generation.py", line 285, in text_completion
    generation_tokens, generation_logprobs = self.generate(
  File "/home/congxiao/.conda/envs/ipex/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/congxiao/code/python/llama2/2-7b/vtune_llama/amx_version/generation.py", line 207, in generate
    logits = self.model.forward(tokens[:, prev_pos:cur_pos], prev_pos)
  File "/home/congxiao/.conda/envs/ipex/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/congxiao/code/python/llama2/2-7b/vtune_llama/amx_version/model.py", line 467, in forward
    h = layer(h, start_pos, freqs_cis, mask)
  File "/home/congxiao/.conda/envs/ipex/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/congxiao/.conda/envs/ipex/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/congxiao/code/python/llama2/2-7b/vtune_llama/amx_version/model.py", line 382, in forward
    h = x + self.attention(
  File "/home/congxiao/.conda/envs/ipex/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/congxiao/.conda/envs/ipex/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/congxiao/code/python/llama2/2-7b/vtune_llama/amx_version/model.py", line 247, in forward
    xq= self.wq(x)
  File "/home/congxiao/.conda/envs/ipex/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/congxiao/.conda/envs/ipex/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/congxiao/.conda/envs/ipex/lib/python3.9/site-packages/intel_extension_for_pytorch/nn/utils/_weight_prepack.py", line 271, in forward
    output = torch.ops.torch_ipex.ipex_linear(
  File "/home/congxiao/.conda/envs/ipex/lib/python3.9/site-packages/torch/_ops.py", line 1061, in __call__
    return self_._op(*args, **(kwargs or {}))
RuntimeError: could not create a primitive descriptor for an inner product forward propagation primitive
```

here is my env list
```
Package                     Version
--------------------------- -----------
accelerate                  0.26.0
asttokens                   3.0.0
attrs                       24.2.0
certifi                     2024.8.30
charset-normalizer          3.4.0
cmake                       3.28.4
comm                        0.2.2
contourpy                   1.3.0
cycler                      0.12.1
debugpy                     1.8.9
decorator                   5.1.1
Deprecated                  1.2.15
exceptiongroup              1.2.2
executing                   2.1.0
expecttest                  0.3.0
fairscale                   0.4.13
filelock                    3.16.1
fire                        0.7.0
fonttools                   4.55.3
fsspec                      2024.10.0
huggingface-hub             0.26.5
hypothesis                  6.122.3
idna                        3.10
importlib_metadata          8.5.0
importlib_resources         6.4.5
intel_extension_for_pytorch 2.4.0
ipykernel                   6.29.5
ipython                     8.18.1
jedi                        0.19.2
Jinja2                      3.1.4
joblib                      1.4.2
jupyter_client              8.6.3
jupyter_core                5.7.2
kiwisolver                  1.4.7
MarkupSafe                  3.0.2
matplotlib                  3.9.3
matplotlib-inline           0.1.7
mpmath                      1.3.0
nest_asyncio                1.6.0
networkx                    3.2.1
neural-compressor           2.4.1
ninja                       1.11.1.2
numpy                       2.0.2
nvidia-cublas-cu12          12.1.3.1
nvidia-cuda-cupti-cu12      12.1.105
nvidia-cuda-nvrtc-cu12      12.1.105
nvidia-cuda-runtime-cu12    12.1.105
nvidia-cudnn-cu12           9.1.0.70
nvidia-cufft-cu12           11.0.2.54
nvidia-curand-cu12          10.3.2.106
nvidia-cusolver-cu12        11.4.5.107
nvidia-cusparse-cu12        12.1.0.106
nvidia-nccl-cu12            2.20.5
nvidia-nvjitlink-cu12       12.4.127
nvidia-nvtx-cu12            12.1.105
opencv-python-headless      4.10.0.84
packaging                   24.2
pandas                      2.2.3
parso                       0.8.4
pexpect                     4.9.0
pickleshare                 0.7.5
pillow                      11.0.0
pip                         24.2
platformdirs                4.3.6
prettytable                 3.12.0
prompt_toolkit              3.0.48
psutil                      6.1.0
ptyprocess                  0.7.0
pure_eval                   0.2.3
py-cpuinfo                  9.0.0
pycocotools                 2.0.8
Pygments                    2.18.0
pyitt                       1.7.2
pyparsing                   3.2.0
python-dateutil             2.9.0.post0
pytz                        2024.2
PyYAML                      6.0.2
pyzmq                       26.2.0
regex                       2024.11.6
requests                    2.32.3
safetensors                 0.4.5
schema                      0.7.7
scikit-learn                1.6.0
scipy                       1.13.1
sentencepiece               0.2.0
setuptools                  75.1.0
six                         1.17.0
sortedcontainers            2.4.0
stack_data                  0.6.3
sympy                       1.13.1
termcolor                   2.5.0
threadpoolctl               3.5.0
tokenizers                  0.19.1
torch                       2.4.0
tornado                     6.4.2
tqdm                        4.67.1
traitlets                   5.14.3
transformers                4.44.0
triton                      3.0.0
typing_extensions           4.12.2
tzdata                      2024.2
urllib3                     2.2.3
wcwidth                     0.2.13
wheel                       0.44.0
wrapt                       1.17.0
zipp                        3.21.0
```
i also try ipex 2.5.0 and torch 2.5.0+cpu
So do ipex not support nn.linear? why this happen?

**Comment by shawnnjupt** [comment]
> Could you give your full test code ?

thanks for relpying, here is my repo 
https://github.com/shawnnjupt/ipex_error_code

**Comment by shawnnjupt** [comment]
> What's your cpu name? $ lscpu |grep name

my cpu is  Intel(R) Xeon(R) Platinum 8458P ,i think it can use ipex
```
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         46 bits physical, 57 bits virtual
  Byte Order:            Little Endian
CPU(s):                  176
  On-line CPU(s) list:   0-175
Vendor ID:               GenuineIntel
  Model name:            Intel(R) Xeon(R) Platinum 8458P
    CPU family:          6
    Model:               143
    Thread(s) per core:  2
    Core(s) per socket:  44
    Socket(s):           2
    Stepping:            8
    CPU max MHz:         3800.0000
    CPU min MHz:         800.0000
    BogoMIPS:            5400.00
```

**Comment by shawnnjupt** [comment]
> You can add `with torch.no_grad(), torch.cpu.amp.autocast(enabled=True):` before your generate. https://github.com/shawnnjupt/ipex_error_code/blob/master/generation.py#L285
> 
> ```
> @@ -282,14 +284,15 @@ class Llama(nn.Module):
>          if max_gen_len is None:
>              max_gen_len = self.model.params.max_seq_len - 1
>          prompt_tokens = [self.tokenizer.encode(x, bos=True, eos=False) for x in prompts]
> -        generation_tokens, generation_logprobs = self.generate(
> -            prompt_tokens=prompt_tokens,
> -            max_gen_len=max_gen_len,
> -            temperature=temperature,
> -            top_p=top_p,
> -            logprobs=logprobs,
> -            echo=echo,
> -        )
> +        with torch.no_grad(), torch.cpu.amp.autocast(enabled=True):
> +            generation_tokens, generation_logprobs = self.generate(
> +                prompt_tokens=prompt_tokens,
> +                max_gen_len=max_gen_len,
> +                temperature=temperature,
> +                top_p=top_p,
> +                logprobs=logprobs,
> +                echo=echo,
> +            )
> ```
> 
> The dtype of input and weights may be not bfloat16, so it's better add this autocast when you run bfloat16.

It can solve my problem. thanks for your reply.
Best wishes to you.
