### ISSUE TITLE
Error while doing Intel ipex install

### ISSUE THREAD

**Issue by ammu7887** [intel/intel-extension-for-pytorch#751]
### Describe the bug

While executing compile_bundle.bat encountering below error. Some help please. 

[718/1130] Building CXX object csrc\gpu\CMakeFiles\intel-ext-pt-gpu.dir\aten\operators\BinaryOps_numeric.cpp.obj
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "C:\Users\umamm\ipex_bundle\intel-extension-for-pytorch\setup.py", line 1172, in <module>
    setup(
  File "C:\Users\umamm\anaconda3\envs\ipexintel\lib\site-packages\setuptools\__init__.py", line 104, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\umamm\anaconda3\envs\ipexintel\lib\site-packages\setuptools\_distutils\core.py", line 184, in setup
    return run_commands(dist)
  File "C:\Users\umamm\anaconda3\envs\ipexintel\lib\site-packages\setuptools\_distutils\core.py", line 200, in run_commands
    dist.run_commands()
  File "C:\Users\umamm\anaconda3\envs\ipexintel\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "C:\Users\umamm\anaconda3\envs\ipexintel\lib\site-packages\setuptools\dist.py", line 967, in run_command
    super().run_command(command)
  File "C:\Users\umamm\anaconda3\envs\ipexintel\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "C:\Users\umamm\anaconda3\envs\ipexintel\lib\site-packages\wheel\_bdist_wheel.py", line 378, in run
    self.run_command("build")
  File "C:\Users\umamm\anaconda3\envs\ipexintel\lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "C:\Users\umamm\anaconda3\envs\ipexintel\lib\site-packages\setuptools\dist.py", line 967, in run_command
    super().run_command(command)
  File "C:\Users\umamm\anaconda3\envs\ipexintel\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "C:\Users\umamm\anaconda3\envs\ipexintel\lib\site-packages\setuptools\_distutils\command\build.py", line 132, in run
    self.run_command(cmd_name)
  File "C:\Users\umamm\anaconda3\envs\ipexintel\lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "C:\Users\umamm\anaconda3\envs\ipexintel\lib\site-packages\setuptools\dist.py", line 967, in run_command
    super().run_command(command)
  File "C:\Users\umamm\anaconda3\envs\ipexintel\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "C:\Users\umamm\ipex_bundle\intel-extension-for-pytorch\setup.py", line 1141, in run
    self.run_command("build_clib")
  File "C:\Users\umamm\anaconda3\envs\ipexintel\lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "C:\Users\umamm\anaconda3\envs\ipexintel\lib\site-packages\setuptools\dist.py", line 967, in run_command
    super().run_command(command)
  File "C:\Users\umamm\anaconda3\envs\ipexintel\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "C:\Users\umamm\ipex_bundle\intel-extension-for-pytorch\setup.py", line 838, in run
    _build_project(build_args, ipex_xpu_build_dir, my_env, use_ninja)
  File "C:\Users\umamm\ipex_bundle\intel-extension-for-pytorch\setup.py", line 592, in _build_project
    check_call(["ninja"] + build_args, cwd=build_dir, env=build_env)
  File "C:\Users\umamm\anaconda3\envs\ipexintel\lib\subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ninja', '-j', '22', 'install']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'intel_extension_for_pytorch'

### Versions

Python 3.10.6 in conda following the steps in documentation

**Comment by huiyan2021** [comment]
Hi @ammu7887 , could you let me know the link of documentation that you are referring to?

**Comment by ammu7887** [comment]
Sure. It's the official intel document 
![Screenshot_2024-12-19-11-59-25-691_com android chrome](https://github.com/user-attachments/assets/2dee5e71-2160-48c2-9c23-161e20246afc)

https://pytorch-extension.intel.com/installation?platform=gpu&version=v2.5.10%2Bxpu&os=windows&package=source
![Uploading Screenshot_2024-12-19-11-59-25-691_com.android.chrome.jpg…]()

**Comment by huiyan2021** [comment]
The fix has been merged, please try https://github.com/intel/intel-extension-for-pytorch/blob/release/xpu/2.5.10 again.

**Comment by ammu7887** [comment]
After using the above link to install having below error, please help

ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\umamm\anaconda3\envs\ipexBundleForWholeSysytemAccerlation\lib\site-packages\pip\_vendor\urllib3\response.py", line 438, in _error_catcher
    yield
  File "C:\Users\umamm\anaconda3\envs\ipexBundleForWholeSysytemAccerlation\lib\site-packages\pip\_vendor\urllib3\response.py", line 561, in read
    data = self._fp_read(amt) if not fp_closed else b""
  File "C:\Users\umamm\anaconda3\envs\ipexBundleForWholeSysytemAccerlation\lib\site-packages\pip\_vendor\urllib3\response.py", line 527, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
  File "C:\Users\umamm\anaconda3\envs\ipexBundleForWholeSysytemAccerlation\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 98, in read
    data: bytes = self.__fp.read(amt)
  File "C:\Users\umamm\anaconda3\envs\ipexBundleForWholeSysytemAccerlation\lib\http\client.py", line 465, in read
    s = self.fp.read(amt)
  File "C:\Users\umamm\anaconda3\envs\ipexBundleForWholeSysytemAccerlation\lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\umamm\anaconda3\envs\ipexBundleForWholeSysytemAccerlation\lib\ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\umamm\anaconda3\envs\ipexBundleForWholeSysytemAccerlation\lib\ssl.py", line 1130, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\umamm\anaconda3\envs\ipexBundleForWholeSysytemAccerlation\lib\site-packages\pip\_internal\cli\base_command.py", line 105, in _run_wrapper
    status = _inner_run()
  File "C:\Users\umamm\anaconda3\envs\ipexBundleForWholeSysytemAccerlation\lib\site-packages\pip\_internal\cli\base_command.py", line 96, in _inner_run
    return self.run(options, args)
  File "C:\Users\umamm\anaconda3\envs\ipexBundleForWholeSysytemAccerlation\lib\site-packages\pip\_internal\cli\req_command.py", line 67, in wrapper
    return func(self, options, args)
  File "C:\Users\umamm\anaconda3\envs\ipexBundleForWholeSysytemAccerlation\lib\site-packages\pip\_internal\commands\install.py", line 379, in run
    requirement_set = resolver.resolve(
  File "C:\Users\umamm\anaconda3\envs\ipexBundleForWholeSysytemAccerlation\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 179, in resolve
    self.factory.preparer.prepare_linked_requirements_more(reqs)
  File "C:\Users\umamm\anaconda3\envs\ipexBundleForWholeSysytemAccerlation\lib\site-packages\pip\_internal\operations\prepare.py", line 554, in prepare_linked_requirements_more
    self._complete_partial_requirements(
  File "C:\Users\umamm\anaconda3\envs\ipexBundleForWholeSysytemAccerlation\lib\site-packages\pip\_internal\operations\prepare.py", line 469, in _complete_partial_requirements
    for link, (filepath, _) in batch_download:
  File "C:\Users\umamm\anaconda3\envs\ipexBundleForWholeSysytemAccerlation\lib\site-packages\pip\_internal\network\download.py", line 184, in __call__
    for chunk in chunks:
  File "C:\Users\umamm\anaconda3\envs\ipexBundleForWholeSysytemAccerlation\lib\site-packages\pip\_internal\cli\progress_bars.py", line 55, in _rich_progress_bar
    for chunk in iterable:
  File "C:\Users\umamm\anaconda3\envs\ipexBundleForWholeSysytemAccerlation\lib\site-packages\pip\_internal\network\utils.py", line 65, in response_chunks
    for chunk in response.raw.stream(
  File "C:\Users\umamm\anaconda3\envs\ipexBundleForWholeSysytemAccerlation\lib\site-packages\pip\_vendor\urllib3\response.py", line 622, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\Users\umamm\anaconda3\envs\ipexBundleForWholeSysytemAccerlation\lib\site-packages\pip\_vendor\urllib3\response.py", line 560, in read
    with self._error_catcher():
  File "C:\Users\umamm\anaconda3\envs\ipexBundleForWholeSysytemAccerlation\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\umamm\anaconda3\envs\ipexBundleForWholeSysytemAccerlation\lib\site-packages\pip\_vendor\urllib3\response.py", line 443, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'intel_extension_for_pytorch'

**Comment by ammu7887** [comment]
Re-run again got stopped in same place. Please find the logs. Internet connection was good. 


Requirement already satisfied: ruamel.yaml.clib>=0.2.7 in c:\users\umamm\anaconda3\envs\ipexbundleforwholesysytemaccerlation\lib\site-packages (from ruamel.yaml->intel-extension-for-pytorch==2.5.10+git2bca097) (0.2.12)
Using cached dpcpp_cpp_rt-2025.0.4-py2.py3-none-win_amd64.whl (58 kB)
Using cached mkl_dpcpp-2025.0.1-py2.py3-none-win_amd64.whl (3.8 kB)
Downloading intel_opencl_rt-2025.0.4-py2.py3-none-win_amd64.whl (108.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━ 67.1/108.8 MB 5.8 MB/s eta 0:00:08
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\umamm\anaconda3\envs\ipexBundleForWholeSysytemAccerlation\lib\site-packages\pip\_vendor\urllib3\response.py", line 438, in _error_catcher
    yield
  File "C:\Users\umamm\anaconda3\envs\ipexBundleForWholeSysytemAccerlation\lib\site-packages\pip\_vendor\urllib3\response.py", line 561, in read
    data = self._fp_read(amt) if not fp_closed else b""
  File "C:\Users\umamm\anaconda3\envs\ipexBundleForWholeSysytemAccerlation\lib\site-packages\pip\_vendor\urllib3\response.py", line 527, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
  File "C:\Users\umamm\anaconda3\envs\ipexBundleForWholeSysytemAccerlation\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 98, in read
    data: bytes = self.__fp.read(amt)
  File "C:\Users\umamm\anaconda3\envs\ipexBundleForWholeSysytemAccerlation\lib\http\client.py", line 465, in read
    s = self.fp.read(amt)
  File "C:\Users\umamm\anaconda3\envs\ipexBundleForWholeSysytemAccerlation\lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\umamm\anaconda3\envs\ipexBundleForWholeSysytemAccerlation\lib\ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\umamm\anaconda3\envs\ipexBundleForWholeSysytemAccerlation\lib\ssl.py", line 1130, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\umamm\anaconda3\envs\ipexBundleForWholeSysytemAccerlation\lib\site-packages\pip\_internal\cli\base_command.py", line 105, in _run_wrapper
    status = _inner_run()
  File "C:\Users\umamm\anaconda3\envs\ipexBundleForWholeSysytemAccerlation\lib\site-packages\pip\_internal\cli\base_command.py", line 96, in _inner_run
    return self.run(options, args)
  File "C:\Users\umamm\anaconda3\envs\ipexBundleForWholeSysytemAccerlation\lib\site-packages\pip\_internal\cli\req_command.py", line 67, in wrapper
    return func(self, options, args)
  File "C:\Users\umamm\anaconda3\envs\ipexBundleForWholeSysytemAccerlation\lib\site-packages\pip\_internal\commands\install.py", line 379, in run
    requirement_set = resolver.resolve(
  File "C:\Users\umamm\anaconda3\envs\ipexBundleForWholeSysytemAccerlation\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 179, in resolve
    self.factory.preparer.prepare_linked_requirements_more(reqs)
  File "C:\Users\umamm\anaconda3\envs\ipexBundleForWholeSysytemAccerlation\lib\site-packages\pip\_internal\operations\prepare.py", line 554, in prepare_linked_requirements_more
    self._complete_partial_requirements(
  File "C:\Users\umamm\anaconda3\envs\ipexBundleForWholeSysytemAccerlation\lib\site-packages\pip\_internal\operations\prepare.py", line 469, in _complete_partial_requirements
    for link, (filepath, _) in batch_download:
  File "C:\Users\umamm\anaconda3\envs\ipexBundleForWholeSysytemAccerlation\lib\site-packages\pip\_internal\network\download.py", line 184, in __call__
    for chunk in chunks:
  File "C:\Users\umamm\anaconda3\envs\ipexBundleForWholeSysytemAccerlation\lib\site-packages\pip\_internal\cli\progress_bars.py", line 55, in _rich_progress_bar
    for chunk in iterable:
  File "C:\Users\umamm\anaconda3\envs\ipexBundleForWholeSysytemAccerlation\lib\site-packages\pip\_internal\network\utils.py", line 65, in response_chunks
    for chunk in response.raw.stream(
  File "C:\Users\umamm\anaconda3\envs\ipexBundleForWholeSysytemAccerlation\lib\site-packages\pip\_vendor\urllib3\response.py", line 622, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\Users\umamm\anaconda3\envs\ipexBundleForWholeSysytemAccerlation\lib\site-packages\pip\_vendor\urllib3\response.py", line 560, in read
    with self._error_catcher():
  File "C:\Users\umamm\anaconda3\envs\ipexBundleForWholeSysytemAccerlation\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\umamm\anaconda3\envs\ipexBundleForWholeSysytemAccerlation\lib\site-packages\pip\_vendor\urllib3\response.py", line 443, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'intel_extension_for_pytorch'

**Comment by huiyan2021** [comment]
Seems a network issue from the log

**Comment by huiyan2021** [comment]
@ammu7887 , any updates?
