### ISSUE TITLE
Ipex install fails (v2.3.110) in windows

### ISSUE THREAD

**Issue by ammu7887** [intel/intel-extension-for-pytorch#759]
### Describe the bug

Please find the details below. Kindly help me resolve. Feel free any questions.
 

Followed instruction given in https://pytorch-extension.intel.com/installation?platform=gpu&version=v2.3.110%2Bxpu&os=windows&package=source

My laptop specs:
intel ultra 9 with intel arc a370m

Command Used:
compile_bundle.bat "c:\program files (x86)\intel\oneapi\compiler\latest" "c:\program files (x86)\intel\oneapi\mkl\latest" mtl-h

Steps:
installed MSVC and Windows SDK
installed one api
Set the env using vcvar64 in conda environment

![image](https://github.com/user-attachments/assets/d37eb131-e9d5-4654-b546-2d93097fd916)

Error faced:
1 warning and 13 errors generated.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "C:\Users\umamm\ipex_bundle\intel-extension-for-pytorch\setup.py", line 1218, in <module>
    setup(
  File "C:\Users\umamm\anaconda3\envs\intelAcclForLaptop\lib\site-packages\setuptools\__init__.py", line 108, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\umamm\anaconda3\envs\intelAcclForLaptop\lib\site-packages\setuptools\_distutils\core.py", line 184, in setup
    return run_commands(dist)
  File "C:\Users\umamm\anaconda3\envs\intelAcclForLaptop\lib\site-packages\setuptools\_distutils\core.py", line 200, in run_commands
    dist.run_commands()
  File "C:\Users\umamm\anaconda3\envs\intelAcclForLaptop\lib\site-packages\setuptools\_distutils\dist.py", line 970, in run_commands
    self.run_command(cmd)
  File "C:\Users\umamm\anaconda3\envs\intelAcclForLaptop\lib\site-packages\setuptools\dist.py", line 945, in run_command
    super().run_command(command)
  File "C:\Users\umamm\anaconda3\envs\intelAcclForLaptop\lib\site-packages\setuptools\_distutils\dist.py", line 989, in run_command
    cmd_obj.run()
  File "C:\Users\umamm\anaconda3\envs\intelAcclForLaptop\lib\site-packages\setuptools\command\bdist_wheel.py", line 373, in run
    self.run_command("build")
  File "C:\Users\umamm\anaconda3\envs\intelAcclForLaptop\lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "C:\Users\umamm\anaconda3\envs\intelAcclForLaptop\lib\site-packages\setuptools\dist.py", line 945, in run_command
    super().run_command(command)
  File "C:\Users\umamm\anaconda3\envs\intelAcclForLaptop\lib\site-packages\setuptools\_distutils\dist.py", line 989, in run_command
    cmd_obj.run()
  File "C:\Users\umamm\anaconda3\envs\intelAcclForLaptop\lib\site-packages\setuptools\_distutils\command\build.py", line 135, in run
    self.run_command(cmd_name)
  File "C:\Users\umamm\anaconda3\envs\intelAcclForLaptop\lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "C:\Users\umamm\anaconda3\envs\intelAcclForLaptop\lib\site-packages\setuptools\dist.py", line 945, in run_command
    super().run_command(command)
  File "C:\Users\umamm\anaconda3\envs\intelAcclForLaptop\lib\site-packages\setuptools\_distutils\dist.py", line 989, in run_command
    cmd_obj.run()
  File "C:\Users\umamm\ipex_bundle\intel-extension-for-pytorch\setup.py", line 1187, in run
    self.run_command("build_clib")
  File "C:\Users\umamm\anaconda3\envs\intelAcclForLaptop\lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "C:\Users\umamm\anaconda3\envs\intelAcclForLaptop\lib\site-packages\setuptools\dist.py", line 945, in run_command
    super().run_command(command)
  File "C:\Users\umamm\anaconda3\envs\intelAcclForLaptop\lib\site-packages\setuptools\_distutils\dist.py", line 989, in run_command
    cmd_obj.run()
  File "C:\Users\umamm\ipex_bundle\intel-extension-for-pytorch\setup.py", line 872, in run
    _build_project(build_args, ipex_xpu_build_dir, my_env, use_ninja)
  File "C:\Users\umamm\ipex_bundle\intel-extension-for-pytorch\setup.py", line 613, in _build_project
    check_call(["ninja"] + build_args, cwd=build_dir, env=build_env)
  File "C:\Users\umamm\anaconda3\envs\intelAcclForLaptop\lib\subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ninja', '-j', '22', 'install']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'intel_extension_for_pytorch'

### Versions

python 3.10

**Comment by ZhaoqiongZ** [comment]
Hi @ammu7887 , the error log is not included in the part of  log you've shared, maybe in the earlier log.
And if you compile again, please have a try on latest v2.5.10

**Comment by ZhaoqiongZ** [comment]
close since no further information, feel free to reopen if you still face it
